### ISSUE TITLE
Posts should be in redux

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#10]
Because when you click a post, technically you get a new version (with potentially more votes).

The original summary feed item should get updated when this happens, because they should pull from the same data source.

**Comment by burakcan** [comment]
Does this refer to fetching and keeping posts/comments in the slice instead of using `fetchFn` functions passed from top and keeping results locally?

**Comment by aeharding** [comment]
Yeah. I think it's OK to keep the objects in the fetchFn for the infinite pagination, but the post component should use data in the redux store as the source of truth for render.
