### ISSUE TITLE
Ability to order or group communities

### ISSUE THREAD

**Issue by fievel** [aeharding/voyager#1016]
**Is your feature request related to a problem? Please describe.**

The communities list is currently sorted by name. It's sometimes difficult to remember what communities are about one topic of interest for you. 

**Describe the solution you'd like**

It could be nice to be able to choose the order in which the communities are displayed, allow to sort on name but also to provide a custom user-defined ordering. Cherry on the cake would be to be able to group communities under a user-defined label. 

For example:

- Books group
> -  books@lemmyworld.com
> -  chat@litterature.cafe
   ...

- Programming group
> - cpp@programming.dev
> - python@bla.com

There is also a very interesting feature request on lemmy project but it goes beyond this request (but would be very nice too): 
https://github.com/LemmyNet/lemmy/issues/818

**Comment by aeharding** [comment]
Hi there! So, we could allow favorites to be sorted. Beyond that though, I think the best approach would be to wait until this feature is baked into Lemmy.

If customizing sort order of favorites sounds like something you'd be interested, feel free to create a ticket for that! Thanks!
