### ISSUE TITLE
Close image by tapping empty space when in compact mode

### ISSUE THREAD

**Issue by concur1** [aeharding/voyager#102]
#### Currently:
When I am using compact mode and I open an image I need to follow these steps to close the image an resume scrolling:
1. Tap empty space so that the cross on the top right of the screen is visible
2. Tap the cross in the top right of the screen to close the image.

#### Potential improvement:
I would like to be able to tap the empty space around a picture to.close the pictute and resume scrolling.

**Comment by aeharding** [comment]
If you are zoomed out, you can also swipe up or down to dismiss :)

I agree though, the dismiss buttons are not properly positioned!

**Comment by concur1** [comment]
Ahhh cool, I didn't realise that. Thank you!
