### ISSUE TITLE
Overview of communites statistics

### ISSUE THREAD

**Issue by ismailghedamsi** [aeharding/voyager#1032]
An appealing way to see how many new users,  number of new posts/comment over a period of time etc

**Comment by sallyFoster** [comment]
@ismailghedamsi Doesn't the sidebar already do that? ![image](https://github.com/aeharding/voyager/assets/104597302/253ca9c3-5fc9-4aab-af99-0e0c7a3e386a)

**Comment by aeharding** [comment]
Yes, this can be seen in the sidebar :)

If you are looking for a visualization - Lemmy doesn't expose that info, but if they do in the future, it can be added to Voyager then.
