### ISSUE TITLE
Take over read status from server

### ISSUE THREAD

**Issue by bjoern-tantau** [aeharding/voyager#1033]
**Is your feature request related to a problem? Please describe.**

When I read posts using the web app or another app they will get marked as read and disappear when I disable "shoe read posts" in the profile settings. But if "show read posts" is enabled on the server (to work around https://github.com/LemmyNet/lemmy-ui/issues/1186) those read posts will appear in Voyager even when read posts are hidden in the app.

**Describe the solution you'd like**

When posts are retrieved from the server and they are marked as read they should also be marked as read in Voyager and hidden accordingly. 

**Describe alternatives you've considered**

Disabling "show read posts" on the server is a workaround, but then you run into https://github.com/LemmyNet/lemmy-ui/issues/1186

**Comment by aeharding** [comment]
Hi! I recommend never unchecking "show read posts" through lemmy-ui with Voyager. It wreaks all sorts of havok that cannot be avoided due to https://github.com/LemmyNet/lemmy/issues/4124. Once that is resolved this will no longer be a problem.
