### ISSUE TITLE
Default post sort unexpected behavior

### ISSUE THREAD

**Issue by mrnetops** [aeharding/voyager#1035]
**Describe the bug**
[1.29.0](https://github.com/aeharding/voyager/releases/tag/1.29.0) added `Default post sort`.

However, if you haven't read the release notes closely (like I did just before filing this bug), it seems like voyager has has a bug where default sort order is forgotten or overridden.

I would suggest 
a) there should be a default sort order options that is simply "last sort used".  for myself I tend to alternate Hot and Top (6 hours), and I'd like it to stay with whatever I have most recently chosen.
b) to preserve end user expected behavior, "last sort used" should be default
c) the option to default or sticky the sort order (and display of the current default) should probably be in the sort order dropdown, and not settings.  possibly longpress or star to default a sort order?

**Comment by aeharding** [comment]
Hi there! https://github.com/aeharding/voyager/issues/1008 will persist your selected sort per feed (per community, but also all/local/home).

Hopefully that helps. It'll be in the next release.
