### ISSUE TITLE
Swiping Regression

### ISSUE THREAD

**Issue by jeff-hykin** [aeharding/voyager#1038]
Not as much a bug as a behavior regression

I'll call the image below "window swiping"

![Screenshot_20231208-224728](https://github.com/aeharding/voyager/assets/17692058/4d3f7a89-2d91-4402-a7a6-55e4cec583b2)

I'll call the image below post swiping

![Screenshot_20231208-224735](https://github.com/aeharding/voyager/assets/17692058/fcb48621-4758-4fa5-ad72-a0a9cc4ff4e2)

Finger movements that previously triggered post swiping now trigger window swiping. And it's really annoying because I do the gesture reflexively. 

Can there be some option to disable window swiping or is there a way for me to downgrade voyager versions?

**Comment by aeharding** [comment]
You can download old Android releases using Obtainium. As for disabling navigation gestures, I've created https://github.com/aeharding/voyager/issues/1040, thanks!

**Comment by jeff-hykin** [comment]
Thanks for the quick response and the new issue. I appreciate it!
