### ISSUE TITLE
Moderated communities default feed option

### ISSUE THREAD

**Issue by hungryca-t** [aeharding/voyager#1044]
**Describe the solution you'd like**
Add a default feed option for communities a user moderates.

**Describe alternatives you've considered**
Visit each moderated community individually to view posts.

Add “Moderated” to the feed filter drop-down list indicated in attached image. 

![IMG_1748](https://github.com/aeharding/voyager/assets/138980525/a9495c46-5650-48af-b51b-6eef93b7bcff)

**Comment by hungryca-t** [comment]
I saw this issue was closed as completed, but I’m just not seeing the option in the feed quick switcher. Am I doing something wrong? Using v1.31.1. @aeharding  

![IMG_1757](https://github.com/aeharding/voyager/assets/138980525/e7305014-8aa4-43a4-9abf-79e68a902dbb)

**Comment by aeharding** [comment]
It should be showing up as "Moderator Posts" under "Local". It will only show if you have moderated communities and your instance is on lemmy v0.19.

**Comment by hungryca-t** [comment]
Unfortunately I’m not seeing that. Viewing the Communities pane, I do have
a Moderated communities breakout, as shown in the screenshot below.



However, I do not have a Moderated Posts selection in the quick feed
switcher. Only “Home,” “All,” and “Local.” I am a moderator of two
communities—one hosted at lemmy.ml which I believe runs v0.19; one hosted
at lemmy.world which I think runs v0.18.5.

**Comment by aeharding** [comment]
What's your instance? If it isn't running 0.19 you will not see the moderator posts section.

**Comment by hungryca-t** [comment]
My account is on the lemmy.world instance, which I suppose doesn’t meet the
criteria. Sorry, I misunderstood.
