### ISSUE TITLE
Allowing moderators to add reasons when removing posts

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1045]
**Is your feature request related to a problem? Please describe.**

As a moderator, I would like to let the members of the community know why a post was deleted.

**Describe the solution you'd like**

Once I tap on the Remove button from the Moderation Zone, the app will display a pop-up that will allow me to write my reasons

![image](https://github.com/aeharding/voyager/assets/104597302/d0b78736-10f7-411e-8ad4-c300d0d627d5)

**Describe alternatives you've considered**

Currently mods can only add reason for posts removals on web.

**Additional context**

This would be a great way to not keep the members of the community in the dark as to why a post was removed.

**Comment by sallyFoster** [comment]
@0xCmdrKeen I see that you referenced another issue to this one, but the other one is asking to show reasons in the mod log and I am asking to be able to add reason as a mod when I delete a post.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster yes, I understand, that's why I made a separate issue. I just tagged this one as related, because if a mod cannot add a reason for deleting a post because they're using Voyager, then Voyager also can't show the user why their post was deleted. Make sense?

**Comment by 0xCmdrKeen** [comment]
@aeharding do you have any concrete plans for this? I currently don't have a Lemmy account with mod rights, so I can't test it, but from reading the code it looks like currently, posts or comments are removed right away when clicking the "Remove" button.

If all this requires is a simple alert popup with a text input field for the reason, I'd be happy to take care of it.

**Comment by aeharding** [comment]
@0xCmdrKeen I am thinking it will probably be a separate action - "Remove with reason". We'll probably need a custom icon for this, too (trash bin with something overlaid).

(I don't want to increase the number of taps to remove troll/spam comments)

**Comment by aeharding** [comment]
If you do want to take this, I am happy to assign it, but first try to get a moderator test environment set up. It can be done fairly quickly at voyager.lemmy.ml.

**Comment by 0xCmdrKeen** [comment]
@aeharding yeah that makes sense. There IS another trash icon in ionicons, `trash-bin-outline`, but not sure if that's sufficiently descriptive or helpful here.

<img alt="trash-bin-outline" width="32" src="https://github.com/aeharding/voyager/assets/98132670/0e9f0f5f-33fe-4151-baa2-219c59af8b43">

I don't see any built-in support on `IonIcon` for composing icons with overlays, so I guess the only alternative would be creating a custom SVG manually.

As for the test environment, how do I get a mod account at `voyager.lemmy.ml`? Do I need to create an account on that instance first or will any account do?

**Comment by 0xCmdrKeen** [comment]
@sallyFoster thanks. I just created one on my home instance, so far nobody stopped me. So I got mod rights there now, all I need is an icon for "Remove with reason".

Here are some half-assed attempts at making one myself, but I don't find them super convincing. 

<img alt="trash-ellipsis-outline" width="96" src="https://github.com/aeharding/voyager/assets/98132670/c7e63e71-2113-4e76-8922-8e8a893da296">
<img alt="trash-bin-ellipsis-outline" width="96" src="https://github.com/aeharding/voyager/assets/98132670/d23fedb6-45f9-4883-83ba-d46dfbd6b359">

**Comment by sallyFoster** [comment]
The one on the left looks cooler to me 😎

**Comment by sallyFoster** [comment]
@aeharding Did you add this one in the latest release?
