### ISSUE TITLE
Modlog should show moderation reason

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1046]
**Is your feature request related to a problem? Please describe.**
As mentioned by @s38b35M5 in #995, the modlog currently only shows WHAT was moderated, but not WHY. The Lemmy API *does* provide a `reason` for each moderation item (unless the moderator didn't or couldn't add one, see #1045).

Additionally, many moderation items also leave out other important information (see [comment below](https://github.com/aeharding/voyager/issues/1046#issuecomment-1849228927)).

**Describe the solution you'd like**
Modlog entries should display the reason for each item, if available. Also, other relevant information, such as the community a post was deleted from, should be shown as well in order to make the modlog more useful and easier to understand.

**Describe alternatives you've considered**
Just don't show the moderation reason? IDK seems silly not to. It would help users to know what rule(s) they've broken so they can avoid further actions in the future.

**Additional context**
Voyager already seems to extract the `reason` from the API (see `src/features/moderation/logs/types/shared.ts:9`), but for some reason does not make use of it in `ModLogItem`. This shouldn't be very difficult from a technical point of view.

**Comment by sallyFoster** [comment]
@0xCmdrKeen For some reason, for me, the community where the post was deleted from and the mod who deleted the post are not showing. The only things that are showing are the post title and the action taken. 

![image](https://github.com/aeharding/voyager/assets/104597302/57c63455-152d-4dae-9104-52cc0153ecb9)

**Comment by 0xCmdrKeen** [comment]
@aeharding happy to do some work on this one next week, unless you already have a plan for how you want to attack this.

I don't really have a good idea of how it might look like just yet, so probably just gonna play with a few variations until I find something that seems to click.

**Comment by aeharding** [comment]
I've assigned it to you! I don't have many thoughts, other than I want to keep the general look and feel of it the same.

**Comment by sallyFoster** [comment]
@0xCmdrKeen Did you get a chance to work on these?

**Comment by 0xCmdrKeen** [comment]
@sallyFoster yeah I played around some but haven't really had any brilliant ideas other than simply sticking the reason at the bottom like this:

![Screenshot](https://github.com/aeharding/voyager/assets/98132670/accdc106-0fe5-4f40-b68f-8fd557f610e9)

**Comment by sallyFoster** [comment]
@0xCmdrKeen That looks fine to me.

**Comment by sallyFoster** [comment]
@0xCmdrKeen  Is it possible to say where the user was banned from?

**Comment by 0xCmdrKeen** [comment]
@sallyFoster I didn't like the way instance bans showed up as "Banned User [instance]", so I removed that part. If a user was banned from a community, it says so on the second line (see second example from the bottom), but I could make this more obvious by changing the title to "Banned User from Community". 

My goal was to make this page look somewhat more similar to the original Lemmy client, which looks like this: 
![image](https://github.com/aeharding/voyager/assets/98132670/242743bc-0573-4e17-9481-82fb57541084)

Note how instance bans just show up as "banned <user>" while community bans have additional detail. But I could certainly also make it more explicit by changing the title for instance bans to something like "Banned User from Instance".

**Comment by sallyFoster** [comment]
@0xCmdrKeen Yes, I think the more detail the better

**Comment by 0xCmdrKeen** [comment]
Weird, for some reason Voyager just started showing the mod name in the title line as well (I didn't change anything, it was already coded in), but it looks really awkward and confusing:

![image](https://github.com/aeharding/voyager/assets/98132670/88f55ea1-5cb1-4027-9e22-10616c1d624f)

Is that something that's really necessary? The info is there (at least sometimes), but even Lemmy doesn't seem to show it by default. If it should stay, then we should probably find a better place for it.

On the other hand, temporary bans are currently indistinguishable in Voyager from permanent ones, but that seems like useful info.

**Comment by 0xCmdrKeen** [comment]
Honestly, I think the biggest question I have though is whether to stick to a hierarchically structured format (title, detail, reason) or a more story-based format like Lemmy uses.

Or, perhaps the most fitting approach would be to make it look more like the Inbox page. I think I might give that a try.

**Comment by sallyFoster** [comment]
@0xCmdrKeen I think that the prettiest it looks, the better, and the lemmy modlog currently looks more aesthetically pleasant.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster well, I'm assuming the use of color is probably out of the question so as to keep in line with the rest of the app design, so I gotta find a way to make it easily readable using black and white only.

**Comment by 0xCmdrKeen** [comment]
Yeah, I think I'm onto something here. It's definitely going in the right direction:

![image](https://github.com/aeharding/voyager/assets/98132670/3f0807ef-2958-4e10-9c20-14a4f1e59957)

**Comment by 0xCmdrKeen** [comment]
I think I'm just going to leave out the mod/admin name entirely and make tapping the item link to the responsible mod/admin's profile instead. Currently it links to the item that was affected (i.e. user that was banned or comment/post that was removed), which isn't really helpful since that won't exist anymore (unless it has been restored). 

Or maybe it should open an action sheet that shows individual links to all affected entities (mod/admin, affected user, community, post/comment).

**Comment by sallyFoster** [comment]
@0xCmdrKeen I think knowing the admin/mod name is important to know who the user would need to contact to ask for clarification. 

Also, it would be great to know which community a post was removed from and who removed it.

**Comment by 0xCmdrKeen** [comment]
@sallyFoster yes I don't want to remove it entirely but I can't really figure out a good way to show it here without making it look awkward. If it stays in the title line, it will interfere with longer titles, making it difficult to even clearly distinguish between community and instance bans:

![image](https://github.com/aeharding/voyager/assets/98132670/77429e1f-a7da-494a-8f4c-999d193a7ddf)

Also, keep in mind that this is not a required field, it's not guaranteed to be present on every item, making it difficult to find a good place for it that wouldn't be wasted if it's missing. It's also not easily distinguishable as the mod name — consider the instance ban (second item), can you tell ad hoc which username is the mod and which the banned user?

Currently, I'm working with this:

<img alt="screenshot" width="330" src="https://github.com/aeharding/voyager/assets/98132670/38caf991-62eb-4992-8d99-bbb3cb8b71f4">
<img alt="screenshot" width="330" src="https://github.com/aeharding/voyager/assets/98132670/1ba7a6b7-b384-4c2e-82d4-f6fd450a7f35">

I added an ellipsis menu to give the user direct access to any of the entities involved in the mod action. Tapping the entire item will still go to the item link like it did before (even though that item will usually no longer be available), but tapping on the ellipsis will give them big and easy to hit links to access the community, user, and admin/mod. 

I'm still experimenting with various ideas but I do like the direction it's going. I'll post more updates when I have them.

**Comment by 0xCmdrKeen** [comment]
Okay, here's another variation I came up with:

<img alt="screenshot" width="330" src="https://github.com/aeharding/voyager/assets/98132670/dbcbebfe-083d-48d4-9b0a-0eb0a31eaa1a">
<img alt="screenshot" width="330" src="https://github.com/aeharding/voyager/assets/98132670/7f204093-859f-4e44-8c1e-35971b54a3eb">

I added the mod/admin name back in, but moved it to the bottom and colored it according to their role and added a mod icon next to it so it's no longer easily confused with the affected user. The idea is sorta making it look like a signature. If the admin/mod name is not available, it will simply say "Administrator" or "Moderator" instead. Also replaced the text "expires in" with a timer icon so it can still fit in the same line if the moderator name is very long (see second to last item, it would not fit there).

The admin/mod item in the action sheet is also now colored according to their role, but it seems a bit superfluous now because the admin name is technically big enough to be clickable. I think this is probably about as much information as I can reasonably fit there, and also, it's a little more colorful, just like the original, while still being distinctly Voyager style.

**Comment by 0xCmdrKeen** [comment]
Since it's now starting to get a little busy with all the icons, I also made a version without the left icon:

<img alt="screenshot" width="330" src="https://github.com/aeharding/voyager/assets/98132670/885ace0c-31e3-4e5a-8307-33d0eec1e7af">

@aeharding would love to hear your opinion on this as well.

**Comment by sallyFoster** [comment]
@0xCmdrKeen When a user is banned from an instance, is there a way to add which one?

![image](https://github.com/aeharding/voyager/assets/104597302/691dc22d-4d5a-445f-bc70-a812a5dd18ad)

**Comment by 0xCmdrKeen** [comment]
> When a user is banned from an instance, is there a way to add which one?

@sallyFoster I'm not entirely sure, since that information is not explicitly given in the modlog item (unless the id in `ModBan` is an instance id, but the docs do not say whether that is the case):

https://join-lemmy.org/api/interfaces/ModBanView.html
https://join-lemmy.org/api/interfaces/ModBan.html

**Comment by sallyFoster** [comment]
@0xCmdrKeen 😍 it looks great! But why is stickied post on red?

**Comment by sallyFoster** [comment]
@0xCmdrKeen Also why doesn't purge community say which community was purged? Actually, most of the actions don't mention the community or the instance. Aren't those provided for purge, unlock and stickied?

**Comment by 0xCmdrKeen** [comment]
> 😍 it looks great! But why is stickied post on red?

Because this one was made by an admin. Just added another screenshot there, you can see it's not always red.

> Also why doesn't purge community say which community was purged? Actually, most of the actions don't mention the community or the instance. Aren't those provided for purge, unlock and stickied?

None of the purge actions include information about the specific item that was purged, I'm assuming these are meant as a "last resort" kind of weapon to get rid of stuff without leaving any traces (in case it's illegal and you could be prosecuted for hosting it). All of the regular mod action leave the removed item visible in the modlog.

https://join-lemmy.org/api/interfaces/AdminPurgeComment.html
https://join-lemmy.org/api/interfaces/AdminPurgeCommunity.html
https://join-lemmy.org/api/interfaces/AdminPurgePerson.html
https://join-lemmy.org/api/interfaces/AdminPurgePost.html

**Comment by sallyFoster** [comment]
@0xCmdrKeen All that makes sense. Thanks for the explanation! And thanks for all the cool work you put into this! Let's hope @aeharding likes it, fingers crossed🤞.

**Comment by 0xCmdrKeen** [comment]
Unfortunately the admin detection still isn't perfect, because remote admins can't be detected reliably without making additional requests, and Voyager currently doesn't fetch or store the necessary data, leading to the possibility for situations like this:

![image](https://github.com/aeharding/voyager/assets/98132670/9e9403bd-0849-489f-b413-a3ad686d0ee9)

Not sure if it's worth the extra effort required to make this work, but I think I've done enough for today. Definitely want to hear Alex's thoughts first.

**Comment by sallyFoster** [comment]
@aeharding What are your thoughts on this?

**Comment by s38b35M5** [comment]
My wholly unqualified opinion: It looks great and does exactly what you'd expect as a user

**Comment by sallyFoster** [comment]
@0xCmdrKeen @aeharding Did you guys decide anything about this internally?

**Comment by 0xCmdrKeen** [comment]
@sallyFoster I haven't heard anything outside of this discussion.

**Comment by aeharding** [comment]
@0xCmdrKeen Do you have a branch that I can look at this? I would like to add reasons to the mod log, especially now that this is supported in Voyager.

> Unfortunately the admin detection still isn't perfect, because remote admins can't be detected reliably without making additional requests, and Voyager currently doesn't fetch or store the necessary data, leading to the possibility for situations like this:

I'm not too worried about this, as long as its accurate for local admins. But I do wonder if Lemmy could expose this information.

**Comment by sallyFoster** [comment]
@0xCmdrKeen Any updates on this?

**Comment by 0xCmdrKeen** [comment]
@aeharding I do have a local branch for this but I never made a PR for it. Of course it's rather outdated by now (it was based on version 1.32.6), so I'll have to see if I can get it rebased on the current version before I'll be able to share it.

**Comment by aeharding** [comment]
@0xCmdrKeen np, and if you don't have time feel free to push in its current state and I can rebase and whatnot.
