### ISSUE TITLE
Inline code in post titles doesn't render

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1051]
**Describe the bug**
Apparently,  Lemmy allows Markdown to be used in post titles ([example](https://programming.dev/post/6973774)). This renders properly on the web client, but in Voyager, the Markdown part is simply ignored, making the title read funny.

**To Reproduce**

1. Go to search tab
2. Paste this post URL: https://programming.dev/post/6973774
3. Tap on "Visit post"

**Expected behavior**
Markdown should be rendered properly, not simply ignored.

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/98132670/43024306-dff8-4373-ac39-2f1de60244c9)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Brave 1.61.101
- Voyager 1.30.2

**Smartphone (please complete the following information):**

- Device: iPhone XS
- OS: iOS 16.6.1
- Voyager 1.30.2

**Additional context**
I'm not sure WHAT subset of Markdown exactly is allowed here, but inline code clearly is. It appears that there already is a `InlineMarkdown` component to handle this exact scenario, but the current configuration does not appear to allow inline code.

I tried adding `"code"` to the `allowedElements` and `code: "code"` to `components` and it seems to solve the issue reasonably well (at least in the browser, can't test the native app as I don't have the toolchain set up for that). Can send a PR but not sure if it's worth the effort for just those 2 lines.

**Comment by aeharding** [comment]
You're welcome to send a PR, but I'm pretty sure this will be fixed in lemmy v0.19

**Comment by 0xCmdrKeen** [comment]
@aeharding how does Lemmy v0.19 solve this?

**Comment by aeharding** [comment]
This: https://github.com/LemmyNet/lemmy/issues/3828 but it looks like it's still not working for your post in lemmy.ml, so reopening!

**Comment by 0xCmdrKeen** [comment]
Ok no worries. I'll send a PR then.
