### ISSUE TITLE
When editing a comment with unsaved changes, pressing "Cancel" asks to confirm deletion

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1059]
**Describe the bug**
See title. When editing a comment and some changes have been made, pressing the "Cancel" button or swiping down shows a confirmation message asking to confirm deletion. This makes sense when canceling a new comment in progress, but it is somewhat confusing when editing a comment since the user might think their comment will end up getting deleted if they go ahead. It's also red which implies a potentially destructive action, thus heightening the sense of danger.

It would be less confusing if the button said "Discard" instead. This would in fact be clear and unambiguous in all situations (new comment or editing comment), so it would not need any special case handling.

**To Reproduce**

1. Go to Profile page
2. Click on ellipsis button next to a comment
3. Select "Edit"
4. Type some text
5. Press cancel (or swipe down)

**Expected behavior**
Instead of "Delete", the confirmation button should say "Discard".

**Screenshots**
<img alt="screenshot" width="300" src="https://github.com/aeharding/voyager/assets/98132670/fb3f9779-69ab-4f53-93a6-c513f7a9fd0b">

**Additional context**
For even more clarity, the button could say "Discard comment" if it's a new comment and "Discard changes" when editing.

**Comment by aeharding** [comment]
Makes sense! PR welcome.

**Comment by 0xCmdrKeen** [comment]
@aeharding would have sent it already, but it's literally just a single line (a single word, even), so I thought I'd wait and see if I come up with something to address #1060 as well since it's somewhat related. But before I waste my time there, could you let me know if there's any plans regarding that?
