### ISSUE TITLE
Ability to save a comment in progress as a draft

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1060]
**Is your feature request related to a problem? Please describe.**
When writing a comment in Voyager, I sometimes have the need to refer back not just to the comment I'm replying to, but perhaps to another comment further up the thread. But I cannot dismiss the comment screen without either saving or discarding my comment entirely.

**Describe the solution you'd like**
When clicking the cancel button or swiping down, Voyager could show a "Save as draft" option. Selecting this option would bring up the comment editor with the same text pre-filled the next time it is opened.

**Describe alternatives you've considered**
The only alternative at the moment appears to be using the device clipboard. However, on mobile, that's not only time consuming, since it requires at least three taps (one to bring up the context menu, one to "Select All", one to "Cut" or "Copy"), plus two more to cancel the comment, but it also means I cannot use the clipboard to copy anything from another comment (such as a link to it).

**Comment by 0xCmdrKeen** [comment]
I did some experiments on this and realized that while this is relatively easy and straightforward for new posts or comments, it's rather tricky for editing existing ones, since the app would have to remember *which* comment the draft belongs to (it's not particularly useful if you abandon a comment edit with a draft and then go write a new reply, only for that edit draft to come up again).

Come to think of it, I wonder how GitHub does it? I noticed that if I type something here and don't submit it, not only does it survive a reload, it even comes back if I navigate away and come back later. And it remembers what issue I've been commenting on. If I go to another issue, the new comment field will be empty, but if I come back here, my previous text shows up again. Amazing.

**Comment by aeharding** [comment]
Voyager saves progress in localstorage if you accidentally restart the device, crash etc.

I think drafts are a bit out of scope for Voyager. If the user wants to compose a long post, there are great markdown notes apps for that. And if the user is spending so much time writing that they want to save a draft, it's really not too much more work to compose in another app.

**Comment by 0xCmdrKeen** [comment]
@aeharding would you consider a PR if I implemented it myself?

**Comment by aeharding** [comment]
Not currently, sorry; it's not a matter of implementation but UX scope.
