### ISSUE TITLE
Markdown editor user autosuggest

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1061]
**Is your feature request related to a problem? Please describe.**
There's some bots that are very useful to mention like the PostWatchBot and Remindme bot but its hard to remember the exact username and instance name when I want to mention them to use them.

**Describe the solution you'd like**
I'd like to be able to click a button or for when i type @ for Voyager to list users I've saved to a list.

**Describe alternatives you've considered**
Currently the only solution is to use the ios text replacement feature and name them something i can remember but it still requires I remember what I named the shortcut. It'd be much more convenient if the list of saved users appeared after I typed @ or if I clicked a button for saved usernames

**Comment by aeharding** [comment]
Hi there! Voyager definitely should have an autosuggest. In terms of "pinning" or highlighting certain users in the autosuggest, I think this would be a feature for lemmy to add the concept of "friends" (like reddit).

**Comment by slrgt** [comment]
The form that the auto suggest uses doesn't properly mention the user so it doesn't let us mention bots so they work. The format that works would be something like @postwatchbkt@lemy.lol instead if including a link to them

**Comment by aeharding** [comment]
@slrgt it does properly mention, I tested. Link is needed because you can mention non Lemmy users which url isn’t necessarily in the u/ form, like mastodon.

**Comment by aeharding** [comment]
If bots aren’t picking that up I’d file a bug with the bot author.

**Comment by slrgt** [comment]
Im confused, I've tested mentioning a separate account using this and the account get no notification? Its only using the @ of the user without the server so it doesnt work for mastodon or lemmy?

**Comment by aeharding** [comment]
I see, it works with remote users but not when mentioning local users. I'll get this fixed shortly.

**Comment by slrgt** [comment]
Oh i meant the opposite. It doesnt include the @ of the server so it doesn’t work for users on a different server then the one you’re on
