### ISSUE TITLE
Sort resets to "active" and doesn't keep setting

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#1063]
**Describe the bug**

**To Reproduce**
- set sort in the posts tab/home to "new"
- go back to communities 
- go back to "home" 
- sort is back to "active"

**Expected behavior**
Sorting should stay the same

**Screenshots**
https://github.com/aeharding/voyager/assets/20093825/c4186e69-ac29-4a2b-8ffa-74ecf4c6d30a

- OS: iOS 17.1.2 (TestFlight)
- Version 1.30.2
- Device: iPhone 12 Pro

**Comment by aeharding** [comment]
Do you have "Remember community sort" enabled in Settings?

**Comment by fer0n** [comment]
That was turned off, is that a new setting? I'm assuming it works as intended then?

**Comment by aeharding** [comment]
Yes, it's a new feature and off by default.
