### ISSUE TITLE
DX Enhancement: Replace Prettier and ESLint with Biome?

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#1067]
[Biome](https://biomejs.dev/) does the job of both Prettier and ESLint and is faster than both

It also [won the Prettier Challenge](https://biomejs.dev/blog/biome-wins-prettier-challenge/)

Reference Video: https://www.youtube.com/watch?v=KI7mbm-BxqA

**Comment by aeharding** [comment]
Biome is a cool project, but currently Prettier is working well and is quite fast. So at the moment this is not something I am looking to change. :)
