### ISSUE TITLE
Graphical glitch using iOS Shortcut from built-in browser 

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#1069]
**Describe the bug**
_Disclaimer: This could be due to an iOS Shortcut bug, but it worked recently from Voyager, so I am thinking it may not be._ 

While using the built-in browser on the iOS native app version 1.31.0, launching an iOS Shortcut that leverages the "Show Web View" Shortcut Action overlays a browser that covers only half the screen, and doesn't load any content (screenshot below). 

If the original browser is dismissed with the Done button, the overlayed iOS Shortcut browser remains (screenshot below). 

The overlayed browser disappears when launching the app switcher (screenshot below). 

As an iOS user, I do this somewhat regularly with a few Shortcuts that use archive.is to bypass paywalls. All Shortcuts that use the "Show Web View" step have this behavior (screenshot below). 

Here's example Shortcut:
https://www.icloud.com/shortcuts/267a9ef9830f416484145f007b919ede

This worked as expected from Voyager until recently, but I can't recall exactly how many versions back.

**To Reproduce**

1. Go to a post with a URL on the iOS native app
2. Open the Share Sheet for the URL directly or load the built-in browser and then launch the Share Sheet. 
3. Open a Shortcut that uses "Show Web View"

**Expected behavior**
The Shortcut overlays a browser that fills the whole screen. 

**Screenshots**
Before opening post, on All feed:
![IMG_4407](https://github.com/aeharding/voyager/assets/86916654/ba67b16e-fe6f-4a7c-b0d1-11a65f0340d8)

Built-in browser before launching Shortcut:
![IMG_4409](https://github.com/aeharding/voyager/assets/86916654/67a784ff-e0bc-4a52-8034-cdb264b9b675)

After launching Shortcut:
![IMG_4408](https://github.com/aeharding/voyager/assets/86916654/ffaf610b-f5b5-487b-bace-14eb817ad5f7)

After dismissing built-in browser, back on All feed:
![IMG_4406](https://github.com/aeharding/voyager/assets/86916654/5fa5f9f7-edc6-4c54-ac5c-e627ebabd856)

Likely culprit Action in iOS Shortcut, from example iCloud link above:
![IMG_4410](https://github.com/aeharding/voyager/assets/86916654/41de0fce-a006-4c3d-9139-ccdd69b2e72e)

- Device: iPhone 13 Mini
- OS: iOS 17.1.2
- Browser: N/A
- Version 1.31.0

Thanks for reading!

**Comment by aeharding** [comment]
Have you tried restarting your phone? If it was working recently, it is unlikely it is a Voyager bug because the in-app browser hasn't been updated/modified for quite some time.

**Comment by gobbledygoober** [comment]
Hi Alexander,

I just restarted my phone and confirmed that the issue unfortunately still occurs. 

Thanks for the speedy reply!

**Comment by gobbledygoober** [comment]
This can be closed with no change required. Sorry for the trouble @aeharding. 

It does indeed appear to be an iOS 17 bug (not fixed as of iOS 17.2.1). 

I applied the workaround described at https://www.reddit.com/r/shortcuts/comments/17koojf/action_show_web_view_at_bug/ to the affected Shortcut, which involves inserting a "Go To Homescreen" step before "Show Web View" step. 

This worked, so I seems unlikely there is anything afoul with Voyager.

**Comment by aeharding** [comment]
OK thanks for sharing your solution!
