### ISSUE TITLE
Biometric unlocking security vulnerability

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1075]
**Describe the bug**
For Face unlocking if the user exceeds the limit and then taps on cancel, one can access the app.

**To Reproduce**

Exceeds the number of attempts for Face unlocking and then tap on cancel.

**Expected behavior**

The app should ask for the iPhone Pin/password

**Screenshots**

https://github.com/aeharding/voyager/assets/104597302/560f537e-59fd-4b60-8563-77a2f8588f52

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.2.1
- Version: 1.31.0

**Comment by aeharding** [comment]
Thanks for the report!
