### ISSUE TITLE
iOS webview and tap to scrolltop

### ISSUE THREAD

**Issue by charroma** [aeharding/voyager#1082]
**Describe the bug**
When you open a post in a webview, if you tap the top of the screen and the browser is already scrolled up, the posts list behind the webview is scrolled to the top.

When you return to the posts list, you are now at the top of the list and lost your previous post position.

It often happends to me by mistake on iPad when trying to tap the "done" button and tapping too high.

**To Reproduce**
- Scroll down in the posts list.
- Open a post that open a webview.
- Tap the top of the screen. (twice if webview is scrolled down)
- Close the webview
- You should now be at the start of the post list.

It's easier to reproduce on an iPad as the top bar has easier access

**Expected behavior**
The scrolltop function of the webview should not affect the posts list behind.

**Device:**
- Device: iPhoneXS, iPad (8th gen)
- iOS: 17.2
- Version 1.31, 1.31.1

**Comment by 9Rk1ng** [comment]
I’ve noticed this today.
