### ISSUE TITLE
Disable auto hide posts in communities not working

### ISSUE THREAD

**Issue by mdelarioja** [aeharding/voyager#1083]
**Describe the bug**
Post that I scroll through don’t get marked as read, but posts that I open do, even with the disable auto hide in communities enabled. 

**To Reproduce**

1. Enable autohide, and activate "disable in communities"
2. Go to a community and select a post
3. Refresh feed, and the post will be marked as read and therefore hidden

**Expected behavior**
When marking read is disabled in communities, post should remain unread and therefore not hidden

**Smartphone (please complete the following information):**

- OS: iOS 17.2
- Version 1.31.2

**Comment by aeharding** [comment]
Quick clarification: Disable auto hide in communities will still mark posts as read, it just shouldn't auto-hide them

**Comment by mdelarioja** [comment]
@aeharding, sorry for bringing this up again, but I have noticed that while posts opened directly in the community feed remained unread, when opened (or seen, as I have it set to mark read on scroll) in the "home" feed, they are marked read and then disappear when opening the community feed. I moderate a couple of communities, so being able to see all the posts is important. Any chance this could be changed?

**Comment by aeharding** [comment]
@mdelarioja Yes please enable this https://user-images.githubusercontent.com/2166114/297949615-e8e24b11-9973-445e-bd81-65c40aceac64.png

**Comment by mdelarioja** [comment]
> @mdelarioja Yes please enable this https://user-images.githubusercontent.com/2166114/297949615-e8e24b11-9973-445e-bd81-65c40aceac64.png

That was easy :) thank you for the prompt response, and awesome job with voyager!
