### ISSUE TITLE
Sorting option to get local communities as top results of searches

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1088]
**Is your feature request related to a problem? Please describe.**

I would like a sorting option to get local communities as top search results 

**Describe the solution you'd like**

Having an option in the current sorting menu to have local communities on top

![image](https://github.com/aeharding/voyager/assets/104597302/309c43af-42d7-4398-9597-9f50ad95c7dc)

**Describe alternatives you've considered**

The only alternative is to look for it around all the search results

**Additional context**

Currently it is difficult to find local communities in search results because the order of the results is kind of random by default

**Comment by aeharding** [comment]
Voyager's sort is controlled by Lemmy. So any sort changes should be requested there.

Thanks!
