### ISSUE TITLE
Highlight users who are also moderators in a given community

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1098]
**Is your feature request related to a problem? Please describe.**
When reading the comments on a post, it would be helpful to know which users also happen to be moderating the community, so you don't accidentally hit them with your spiciest takes.

I believe Apollo did something like this, I think mods where highlighted in yellow? Not sure if there was an icon for it, too. Reddit does this also I think, but using green. 

**Describe the solution you'd like**
Comments or posts from users made in a community for which they have moderator rights should have their username highlighted, similar to OP, but another color (perhaps yellow or green). 

**Describe alternatives you've considered**
There currently doesn't seem to be any way of finding this out within Voyager, since mod rights aren't shown on the user's profile either. The only way to find out would likely be the Lemmy web app.

**Additional Context**
Come to think of it, Voyager should probably also display this information on a user's profile. Like underneath the posts/comments options there could be another one that says "Moderates" or "Moderator of" and when clicked, shows a list of communities they are a mod of. 

I believe all the required information is already part of the standard API responses and cached in Redux, so this shouldn't require any additional backend requests.

**Comment by aeharding** [comment]
Thanks for the issue. In Voyager mods are green. If they choose not to distinguish their comments as mods, then they will appear as normal users. This is a feature, not a bug, so that mods can participate in the conversation as normal users without appearing as a mod.

In this regard, I actually disagree with lemmy-ui implementation where mods are always shown as mods, I like the reddit approach better.

Thanks!

**Comment by 0xCmdrKeen** [comment]
Okay, thanks for clarifying. What about showing moderated communities on their profile though? Is that a possibility?

Would you accept a PR if I implemented it?
