### ISSUE TITLE
Setting for choosing the default post type

### ISSUE THREAD

**Issue by 0xCmdrKeen** [aeharding/voyager#1102]
**Is your feature request related to a problem? Please describe.**
Based on an idea [found here](https://aussie.zone/comment/5155904). Some users make more text or link posts than image posts, so it should be possible to configure a default post type instead of having it always be photo.

**Describe the solution you'd like**
There should be a setting to let users decide which post type is the default when making a new post.

**Describe alternatives you've considered**
Don't change anything? It only saves a single tap, not the end of the world.

**Additional context**
The question with such a feature is whether it would simply change which tab is open by default when you bring up the new post editor, or whether it would change the order of the tabs to make the default one first. And in the latter case, how should the other two be ordered?

It would be easy enough to add a setting to choose the default type because a component for that already exists. But there isn't one that lets users put things in order of priority.

**Comment by aeharding** [comment]
I've thought about this, but I don't think it's worth the overhead. It is quite easy to tap to change. Thanks though!
