### ISSUE TITLE
Repeatedly getting logged out of accounts on some instances since the update to 0.19

### ISSUE THREAD

**Issue by SrivatsanSenthilkumar** [aeharding/voyager#1113]
**Describe the bug**
I and others using the feddit.de instance are repeatedly getting logged out of our accounts since the instance updated to 0.19 (issue remains even with 0.19.1). I face no log out issues with my lemmy.one account (which is also on 0.19.x). Also my account is being not logged out on the photon client that I use on desktop. These lead me to believe that this is something specific to how voyager is interacting with feddit.de.

Edit 1 : One user suggests this happens potentially when the instance has a spike or momentarily failure in response time. i have not verified this but looking at https://lemmy-status.org/, it does seem that the logging out coincides with the response time spike.

Edit 2 : Seems to be affecting other instances as well

**To Reproduce**

1. Login using feddit.de
2. Use app as normal
3. Randonly logged out at a later time

**Expected behavior**
That the account should not be logged out

**Screenshots**

**Smartphone (please complete the following information):**

- Device: Moto G60
- OS: Android 13 (LineageOS 20)
- Native app version 1.31.2

**Additional context**
As far I can tell from the comments on the [post](https://feddit.de/post/6874269) about this on the voyager community, this seems to only affecting feddit.de users. If it turns out to be affecting more instances, I will edit this issue.

**Comment by 0xCmdrKeen** [comment]
My home instance just upgraded to 0.19 this morning, and this has been happening there too ever since, so this issue does not appear to be unique to feddit.de.

**Comment by aeharding** [comment]
0.19 is working fine in my testing, so this is likely a server misconfiguration issue. If the instance returns `not_logged_in`
`incorrect_login` for the inbox count endpoint, Voyager will log you out because the instance explicitly told Voyager that it is logged out.

**Comment by SrivatsanSenthilkumar** [comment]
I will check if the lemmy-ui runs into the same issue as i assume they too use `not_logged_in` `incorrect_login` for inbox count. Are there any other indicators for the login status??

**Comment by aeharding** [comment]
It looks like lemmy on feddit.de is returning `incorrect_login` to the inbox endpoint, despite the correct JWT provided (I checked).

I'm not really sure what to do here. Lemmy is telling us something that is completely false.

<img width="576" alt="image" src="https://github.com/aeharding/voyager/assets/2166114/4164f22e-6e9e-4f4e-a8f9-0d899c10b545">

If someone can make a lemmy bug that would be helpful. We could just not log the user out, but that is a poor user experience for when tokens are actually revoked.

Lemmy should never return incorrect_login unless the JWT is actually incorrect.

**Comment by SrivatsanSenthilkumar** [comment]
I will make the bug report if it isn't there already

**Comment by aeharding** [comment]
Created https://github.com/LemmyNet/lemmy/issues/4319

**Comment by SrivatsanSenthilkumar** [comment]
> Created https://github.com/LemmyNet/lemmy/issues/4319

Thank you. It was night here so I went to sleep after our last interaction with the plan of doing it today.

**Comment by aeharding** [comment]
I have disabled the logic in Voyager that logs out if lemmy says that the token is invalid.

This means that Voyager will not function correctly if the token is actually invalid. Users will need to manually logout and log back in. But, this should fix false positive sporadic logouts.

**Comment by SrivatsanSenthilkumar** [comment]
While it is nice of you to provide this temporary solution, hopefully the issue is resolved on lemmy's side.

**Comment by 0xCmdrKeen** [comment]
@aeharding perhaps a better fix for this issue, rather than removing the auto-logout altogether, would be adding a failure counter and only logging the user out automatically after, say, 3 failed attempts in a row?

This would make it so that sporadic token errors don't end up logging the user out right away, but more permanent ones do. It's not perfect but perhaps a worthwhile improvement.

**Comment by aeharding** [comment]
It’ll come back. ’ll revert once Lemmy fixes it on their end 👍
