### ISSUE TITLE
Community image broken

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#1114]
**Describe the bug**
Community image of !technology@lemmy.world is not showing properly 

**To Reproduce**
- search for communities, e.g. "technology"
- community image of multiple are broken

**Expected behavior**
Images showing property or fallback image showing

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/20093825/8db8346c-8854-4823-b499-58b53138939c)

**Smartphone:**

- Device: iPhone 12 Pro
- iOS 17.2.1
- Version 1.32.2 (196) TestFlight

**Additional context**
Mlem is showing an image, but maybe that's a fallback image? There's a few communities that have the same broken image, communities without an image have a single letter as a fallback.

**Comment by 0xCmdrKeen** [comment]
It appears there is something wrong with their PictRS backend. 

The icon URL for that community is `https://fry.gs/pictrs/image/c6832070-8625-4688-b9e5-5d519541e092.png`, when I plug that in my browser, I'm getting the following message:

    Request error: error sending request for url (http://pictrs:8080/image/original/c6832070-8625-4688-b9e5-5d519541e092.png): error trying to connect: dns error: failed to lookup address information: Try again

That looks like a misconfigured reverse proxy to me, might want to talk to the admin of Lemmy.world about that.

**Comment by aeharding** [comment]
Yeah, looks like a Lemmy instance issue.
