### ISSUE TITLE
URL/Link Preview is Hidden Under Finger on Long Press

### ISSUE THREAD

**Issue by Brendan-D15** [aeharding/voyager#1123]
**Describe the bug**
I am unable to view the preview of any link because it becomes hidden underneath my finger as I long press on any link.

**To Reproduce**

1. Go to any comment/post description where a link is somewhere in the text.
2. Hold down on the link to get a preview of where it leads
3. Link preview appears directly under finger, I am unable to read the preview unless I take a screenshot.

**Expected behavior**
The preview should be offset above or below the point of contact so that the user can read the preview without their finger blocking their view.

**Screenshots**
![blur1703342323113](https://github.com/aeharding/voyager/assets/66277419/24bec496-d860-43f0-bc08-ff165f62955a)

**Smartphone (please complete the following information):**

- Device: Pixel 7 Pro
- OS: Android 14 (GrapheneOS)

**Additional context**
It would be great if the full preview was shown as well.

**Comment by aeharding** [comment]
@Brendan-D15 this is a native iOS thing, nothing Voyager controls unfortunately.
