### ISSUE TITLE
Duplicate posts across instances/communities

### ISSUE THREAD

**Issue by HorseChandelier2023** [aeharding/voyager#1128]
**Is your feature request related to a problem? Please describe.**
As a user I see many posts on my feeds that have exactly the same title and, usually, content. These may be in different communities and/or instances. 

**Describe the solution you'd like**
Voyager to flag(with some text) the titles of posts, after the first in the feed, with duplicate titles so that one could use client side filtering to block duplicates.

Voyager would need an "enable duplicate detection" switch, an option to determine what is "first" (newest, oldest, subscribed instance, home instance?) and perhaps a switch to automatically filter "duplicate title" posts.

For example a post with the title 
"really important post" posted to lemmy@lemmyworld, idiot@spamcentralinstance and ohnoesdontmissthis@kbin

Would appear in the feed once as 
"really important post" 
And subsequently as
"[d] really important post" 

Which would  enable users bothered by such things to set up a filter for all posts whose title contained [d] and consequently only see one post. 

**Describe alternatives you've considered**
Thought about having Voyager generate a post that collects links to all the duplicates but that would be tricky to implement and would require more work/load server side. 

**Additional context**
Note this request does not relate to content (which would be a nightmare to do) , just post titles.

**Comment by HorseChandelier2023** [comment]
This screenshot illustrates the issue 

![Screenshot_20231228_050103_app vger voyager](https://github.com/aeharding/voyager/assets/154963582/f9e4cfdd-6214-44d9-88e7-7c02e2d6ebb3)

**Comment by 0xCmdrKeen** [comment]
This is called crossposting, and figuring out how to deal with this problem is probably the reason @aeharding [blocked my PR here](https://github.com/aeharding/voyager/pull/1068#issuecomment-1852187298).

**Comment by HorseChandelier2023** [comment]
Ah OK. 
Didn't realise there was a PR (I guess  because I didn't search for "crosspost" ... But did for "duplicate" - doh!)

**Comment by 0xCmdrKeen** [comment]
@HorseChandelier2023 well, I'm not sure if there already is an open issue about this particular problem with crossposting, and the PR doesn't address that (in fact, it would probably make it worse by allowing Voyager users to crosspost as well).

Also @aeharding didn't mention what he meant by "a more comprehensive approach to crossposting" but I think addressing the problem you've described would be a fairly good guess.

**Comment by aeharding** [comment]
Hi! Thanks for the issue. I think this should be fixed in Lemmy core. Once it is fixed there Voyager should add support.

**Comment by 0xCmdrKeen** [comment]
@aeharding I'm not sure when this was added, but it looks like `GetPostResponse` has an array of crossposts: https://join-lemmy.org/api/interfaces/GetPostResponse.html#cross_posts

Unfortunately, since it's not on `PostView`, this information is not available when fetching an entire feed.
