### ISSUE TITLE
Optimizing URL Structure for Integration with Lemmy

### ISSUE THREAD

**Issue by paulo-roger** [aeharding/voyager#1134]
**Is your feature request related to a problem? Please describe.**
Right now the domain of the instance is repeated in the URL, even when forcing the UI into single instance mode.

**Describe the solution you'd like**
Ideally, we'd like Voyager to operate directly on `domain.tld`. Is this a possible configuration?

**Comment by aeharding** [comment]
Hi there! Thanks for the issue. However, Voyager URL structure is needed due to the unique nonlinear tab navigation.

**Comment by paulo-roger** [comment]
Hi! I appreciate the prompt response. Thank you for this software.
