### ISSUE TITLE
On feed have the community name clickable but not the instance name

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1142]
**Is your feature request related to a problem? Please describe.**
At least twice a day i accidentally go into the community instead of opening the thread.

**Describe the solution you'd like**
I would love if only the community name was clickable and not the instance name that is next to it. 

The instance name is already darker which would be understood as not being clickable compared to the brighter color of the community name

**Describe alternatives you've considered**
Smaller thumbs😅

**Additional context**
Voyager is the best Lemmy client thank you for making it! It would be nice if I could subscribe to voyager for $.99 a month and be able to choose a little icon that appears next to my username to show other Voyager users I support Voyager :)

**Comment by slrgt** [comment]
@aeharding  will this be implemented? Everyday I open the community instead of clicking the thread 😅

**Comment by aeharding** [comment]
It does bother me every now and then too. As a workaround before it is fixed you can disable the post buttons for more tap space, if you mostly use gestures anyways.

The best way to get something prioritized is more upvotes on the issue :) Because roughly that is how I prioritize issues
