### ISSUE TITLE
Ability to save User profiles as communities

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#1144]
**Is your feature request related to a problem? Please describe.**
There are times when I find it easier to look for the latest posts from specific users (I have done this for aeharding for Voyager updates on occasion, and sunaurus for lemm.ee updates). One use case is when ... I've accidentally hidden announcement posts in Voyager. 

**Describe the solution you'd like**
I believe Reddit and Apollo would allow saving `/u/<username>` pages just like any other community. I'm not sure if Lemmy allows this currently. 

**Describe alternatives you've considered**
Searching for a user of interest each time works, but is somewhat tedious. 

**Additional context**
Apologies for accidentally posting this request before I had all of the details typed up.

**Comment by gobbledygoober** [comment]
If this is possible, also having a share sheet option on user profiles (e.g. to open in a browser or send a link to a friend) would be a good addition.

**Comment by aeharding** [comment]
Hi there. If Lemmy adds support for "friends" then it would be possible to have a list of users like this.

However, this is more a question for Lemmy. Once its implemented in Voyager we can add support.

**Comment by gobbledygoober** [comment]
Understood, thanks for the consideration. 

Is this the right place to peruse for existing requests and/or submit a new one?

https://github.com/LemmyNet/lemmy/issues

**Comment by aeharding** [comment]
Yes that's right

**Comment by gobbledygoober** [comment]
Thanks. 

It looks like it was suggested in August and subsequently closed, for fear of consuming extra disk space on the server (if I understood it correctly):
https://github.com/LemmyNet/lemmy/issues/3792
