### ISSUE TITLE
Conditional hiding options for announcements 

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#1145]
**Is your feature request related to a problem? Please describe.**
I enjoy using the Hide button to hide all posts that have been marked as read. Recently however, a few times I have accidentally hidden sticky/announcement posts unintentionally. For now I have disabled auto-hiding read posts. 

**Describe the solution you'd like**
It would be great to have the option to handle announcements with additional controls, e.g. if auto-hide posts is enabled, keep announcements visible unless explicitly marked hidden, or equivalent. 

**Describe alternatives you've considered**
#1144 describes an alternative, but having both features would be ideal. 

**Additional context**
N/A

**Comment by aeharding** [comment]
Hi! Voyager already doesn't mark posts as read on scroll if they are announcements of your current feed.

If you tap into it explicitly, it will be auto hidden, but you can then unhide in the post options if you want.

**Comment by gobbledygoober** [comment]
Hi Alex,

Can you provide more details for the workflow for unhiding a post? When inside a post, the "..." pea menu does not list hide/unhide options. When in a community, the pea menu for a post shows Hide, but not Unhide. 

Thanks.

**Comment by aeharding** [comment]
If you view the post then swipe back, it should have "unhide" in the ... menu if you post was auto hidden.

**Comment by gobbledygoober** [comment]
Aha, I had "Disable in communities" enabled. With that option turned off, I see the Unhide option. Thanks!
