### ISSUE TITLE
Clicking on toolbar scrolls to top

### ISSUE THREAD

**Issue by DakshG07** [aeharding/voyager#1146]
**Describe the bug**
Clicking on the toolbar in the PWA scrolls to the top, without performing any action.

**To Reproduce**

1. Install Voyager App (v1.33.0)
2. Click on toolbar icons
3. Voyager will scroll to the top

**Expected behavior**
Voyager doesn’t scroll to the top, and instead performs the correct action.

**Screenshots**
Screenshots don’t really show the problem here.
**Desktop (please complete the following information):**

- OS: iOS
- Browser Safari
- Version 33

**Smartphone (please complete the following information):**

- Device: iPhone 15 PM
- OS: iOS 17.1.2
- Browser safari
- Version 33

**Additional context**

**Comment by aeharding** [comment]
Hi! This is intended behavior. It will go back if you're already at the top.

**Comment by DakshG07** [comment]
@aeharding 
Sorry, that's on me, I wasn't really clear here.

Voyager scrolls to the top when I click on the *bottom* toolbar. 
![image](https://github.com/aeharding/voyager/assets/48651837/d9fbc5d1-6268-4d95-9917-429eaee834c6)

I can't open my inbox, check my settings, etc. *at all*.

**Comment by DakshG07** [comment]
Additionally, this issue only exists on the PWA; I don't have this issue on the web version.

**Comment by aeharding** [comment]
Yes, that's intended. If its not happening in the web version that seems like it's probably a bug.

**Comment by DakshG07** [comment]
That’s intended? To be clear: I can’t press the buttons on the toolbar: I’m completely unable to open my settings/inbox AT ALL.

**Comment by aeharding** [comment]
Oh, I see! I am unable to reproduce that using your reproduction steps however. Perhaps try restarting your device, and reinstalling the app.

**Comment by DakshG07** [comment]
I’m going to update and try again. I get a weird keyboard bug when opening pages embedded in apps, I’m guessing something with PWAs broke.

**Comment by DakshG07** [comment]
Ah, sorry, it seems to have been an iOS bug! Anyways, updating solved my issue.
