### ISSUE TITLE
UP/DOWN vote buttons on comments small tap target

### ISSUE THREAD

**Issue by s38b35M5** [aeharding/voyager#1157]
**Is your feature request related to a problem? Please describe.**
On my device, when gestures are disabled and individual vote counts are visible, voting on comments is quite difficult, and often results in collapsing the comment or tapping other nearby elements.

**Describe the solution you'd like**
Perhaps larger and/or relocated vote buttons.

**Describe alternatives you've considered**
None known

**Additional context**
[Lemmy Post](https://lemmy.world/comment/6523453)
![VoyVoteButSm](https://github.com/aeharding/voyager/assets/138058715/76407995-c845-447d-b688-d58f18d0dd68)

**Comment by aeharding** [comment]
I increased the tap target (without visual changes). Hopefully that helps somewhat!
