### ISSUE TITLE
Change default open page

### ISSUE THREAD

**Issue by csm10495** [aeharding/voyager#117]
Right now it's home. Can it be user customizable? Like if I want (random community) or all, that should be possible and ok.

**Comment by bdonvr** [comment]
+1, I usually always want to go to All.

**Comment by httpjamesm** [comment]
@aeharding Is this a feature you want to pursue? I can add this in

**Comment by aeharding** [comment]
It is - but not right now.

Desktop users can add a bookmark, and mobile users should have the app persistently open most of the time so it shouldn't matter.

Therefore, this is currently a low priority.

**Comment by appel** [comment]
@aeharding It didn't matter for me when I had the PWA, but it is an issue for me now that I switched to the Android app. I can only assume the same applies to users of the iOS app.
