### ISSUE TITLE
Blank screens in latest update on iOS 17.3

### ISSUE THREAD

**Issue by matthewpritchett** [aeharding/voyager#1181]
**Describe the bug**
Open app and it just shows the bottom bar.

**To Reproduce**

1. Open app
2. See blank screens
3. Force close app
4. Still blank screens

**Expected behavior**
Load the app

**Screenshots**
![IMG_4072](https://github.com/aeharding/voyager/assets/34951520/95c16995-2377-4359-b934-5b71b230247d)

**Smartphone (please complete the following information):**

- Device: iPhone 15 Pro Max
- OS: iOS17.3
- App
- Version 1.37.0

**Additional context**

**Comment by aeharding** [comment]
Hi,

Thanks for the report. Please let me know if this is fixed in https://github.com/aeharding/voyager/releases/tag/1.37.2, to be released to the app store shortly!

**Comment by matthewpritchett** [comment]
Yep, that fixed it, thanks!
