### ISSUE TITLE
View Local/All feed of an instance without account.

### ISSUE THREAD

**Issue by UmBottesWillen** [aeharding/voyager#1190]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to browse the Local and All feeds of instances without account.

**Describe the solution you'd like**
Please add the ability to browse instances without account, for example by adding an 'anonymous' option when adding a new instance to the Accounts tab.
Additionally, a 'open thread with account' option would be nice, which would allow me to open the thread I viewed anonymously, with an account of my choosing. Alternatively, an 'open community with account' button would be much simpler to implement.

**Describe alternatives you've considered**
Creating an account on those instances. This is not an option for me.

**Additional context**
None.

**Comment by aeharding** [comment]
This is already a feature with guest accounts - please see https://github.com/aeharding/voyager/releases/tag/1.37.0 🙂
