### ISSUE TITLE
Long hold Inbox tab to show an option to mark all messages as read

### ISSUE THREAD

**Issue by SocietasEvanescentes** [aeharding/voyager#1194]
As Lemmy doesn't have an option to disable notifications for comments on your posts, a feature that I loved about Apollo and tried doing in Voyager is long holding the inbox icon, and then pressing "Mark all as read". 

I believe adding this feature will enhance the user experience, and remove the amount of taps to do this, while also keeping the user on the tab they selected.

**Comment by aeharding** [comment]
@SocietasEvanescentes, the double check in the header of the inbox page should mark all read. Is that what you're looking for?

**Comment by SocietasEvanescentes** [comment]
> @SocietasEvanescentes, the double check in the header of the inbox page should mark all read. Is that what you're looking for?

It's similar, but this would activate the same menu option by long pressing the inbox button.

**Comment by aeharding** [comment]
Hmm. I looked at apollo and I am not able to reproduce this feature. Could you make a screen recording, if you have time?

Thanks!

**Comment by SocietasEvanescentes** [comment]
Unfortunately, I am unable to reproduce the issue either due to the app
only showing how to support the dev.
