### ISSUE TITLE
Support for links to aguppe groups

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1197]
**Is your feature request related to a problem? Please describe.**
A.gup.pe groups are now available to use in Lemmy but clicking on them in voyager opens the links instead of displaying them within the app

**Describe the solution you'd like**
Clicking one of the links to open them within voyager would be great here are examples of them linked like any community would be https://slrpnk.net/comment/5806726

**Comment by aeharding** [comment]
Thanks, I'll try to get this fixed tonight.
