### ISSUE TITLE
Can't swipe to mark messages as read

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1219]
**Describe the bug**
When viewing a new direct message in the inbox (all) section its impossible to swipe to mark as read

**To Reproduce**

1. Recieve a direct message 
2. Try to mark it as read by swiping like you normally do for comments

**Expected behavior**
Its expected you to be able to mark the direct message as read like you do for replies.

**Comment by aeharding** [comment]
Hi!

This is intentional, but I think we should add support!

**Comment by slrgt** [comment]
Sweet, thanks!
