### ISSUE TITLE
Text selection without additional taps

### ISSUE THREAD

**Issue by mikhirev** [aeharding/voyager#1229]
**Is your feature request related to a problem? Please describe.**
It is very inconvenient to open menu and tap "select text" each time I want to copy something.

**Describe the solution you'd like**
Allow to select text of messages by long tap as in most apps.

**Comment by aeharding** [comment]
Hi!

Thanks for the issue. Sorry, long tap brings up the options menu. So it can't be used for that.

**Comment by mikhirev** [comment]
> long tap brings up the options menu

But there's a "…" button for that.
