### ISSUE TITLE
[Feature Request] "Sync" migration tool

### ISSUE THREAD

**Issue by XaeroDegreaz** [aeharding/voyager#125]
I see there is an Apollo migration tool for the app. It would be nice to see a migration tool for Sync as well.

**Comment by aeharding** [comment]
Does sync have a JSON export? If you could provide in the issue or email hello@wefwef.app I'll take a look.

**Comment by Briaoeuidhtns** [comment]
Sync doesn't have an export option, but it subscribed with your reddit account so we could use the official reddit steps discribed [here](https://support.reddithelp.com/hc/en-us/articles/205243365) and import a multireddit url?

**Comment by aeharding** [comment]
Because we now have the reddit import, this should no longer be needed. Try it out and let me know what you think :)

**Comment by XaeroDegreaz** [comment]
It doesn't try to save them though. It just puts them in a list once you paste.
