### ISSUE TITLE
Voyager does not respect account level show read setting.

### ISSUE THREAD

**Issue by Pome-ro** [aeharding/voyager#1259]
**Describe the bug**
When the "show read" setting is unchecked on your profile it overrides voyagers hide read option.

**To Reproduce**

1. Go to your instance via a browser and sign in
2. Go to your profile settings and uncheck show read. Save the settings.
3. Open Voyager and reload your feed. 
4. Regardless of what the Voyager setting is set to, the profile setting overrides it.

**Expected behavior**
The hide read option should control your profile setting. 

**Smartphone (please complete the following information):**

- Device: Pixel 4a
- OS: Android 13
- Version Voyager 1.39

**Additional context**

The hide read setting I believe augments what is returned from the api. Which is why the setting in Voyager is impacted.

**Comment by aeharding** [comment]
Thanks for the bug report. This is being tracked here: https://github.com/LemmyNet/lemmy/issues/4124

Please upvote that for visibility :)
