### ISSUE TITLE
Body Text (descriptions) in Voyager are not showing for crossposts

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1264]
**Describe the bug**
Every time a cross post is made, the description text is not shown. One needs to go back to the original post to see the description body.

**To Reproduce**

1. Cross post an image or a link 

**Expected behavior**
The body text should still be visible in the crosspost

**Screenshots**

![image](https://github.com/aeharding/voyager/assets/104597302/b7843237-8658-495e-b2c5-2345c1211375)

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.3.1
- Version: 1.41.0

**Comment by aeharding** [comment]
Hi! This is expected. If you prefer the old crosspost functionality, you can turn it off in the Settings.
