### ISSUE TITLE
Manual cache clearing

### ISSUE THREAD

**Issue by niklasbogensperger** [aeharding/voyager#1305]
**Is your feature request related to a problem? Please describe.**
Sometimes it would be nice to be able to manually clear Voyager's cache, especially if you are running devices with lower storage capacity.
Normally I am not running out of storage space but if there is e.g. a large iOS update I sometimes have to delete some files or apps (or even just reboot and clear out some temporary files) in order to be able to dowload and install it.
During that process, Voyager is routinely near the top of the list of largest apps in the iOS storage settings screen, even though its install size is only 12.8 MB. Most of the storage is taken up by "Documents & Data" - about 530 MB after some recurring usage over a few weeks.

**Describe the solution you'd like**
A manual button in the settings to delete Voyager's temporary files, similar to what Apollo used to have IIRC, would solve this issue. iOS sadly does not allow users to delete caches or temp files from the settings like on Android.
Maybe some greyed-out text displaying the current size of the cache next to the clear button or a popup saying how much space was freed up would also be a great addition to this feature, but that is more of a nice-to-have than necessary.

**Describe alternatives you've considered**
So far, I deleted and subsequently reinstalled (redoing all the app settings every time) Voyager two times when I wanted to (temporarily at least) reclaim the 0.5 GB of space. While this is slightly annoying, this workaround does result in the same end-state of storage space on my device.

**Additional context**
I am using Voyager to browse the default all feed and i am not logged in.
I have confirmed that a reboot changes nothing about the amount of storage Voyager takes up.

**Comment by aeharding** [comment]
Hi! I will add a button to manually clear. However it doesn't clear everything and there seems to be a stubborn 100MB that Voyager cannot clear. IDK why. But it appears that other apps like Apollo have the same problem :(

**Comment by niklasbogensperger** [comment]
Thanks for the quick reply and fast implementation; looking forward to the next app update! 🚀
