### ISSUE TITLE
iOS deep linking not working correctly

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1321]
**Describe the bug**
IOS deep linking is not working on long press menu

**To Reproduce**

1. Long press a URL to get the menu
2. Tap on share
3. Tap on Open in Voyager
4. The deep link does nothing

**Expected behavior**
It should open the link on voyager 

**Screenshots**
https://github.com/aeharding/voyager/assets/104597302/1e5fe39b-a1f4-4c12-884e-23b3477b5887

**Comment by aeharding** [comment]
Unfortunately I'm pretty sure this is just how iOS deep link via action extensions works. If you test "Open in Apollo", "Open in Ice Cubes App" or "Open in Mastodon" you will see the same behavior. It only works from Safari share menu.

If you find an example of other apps following the same pattern where it works there, I'm happy to reopen and take another look.
