### ISSUE TITLE
Feature Request : Export / Import settings for backups or moving devices

### ISSUE THREAD

**Issue by tfuerholzer** [aeharding/voyager#1329]
**Is your feature request related to a problem? Please describe.**

I'm moving to a new phone and I have been looking through the App (PWA Version in my case) to find a way to export all the user settings like themes, blocklists, gesture settings to a file. As to my surprise I didn't find anything. Many other Apps, especially on Android offer such features (Newpipe, K9 Mail, Syncthing, ...). That way you have a simple file (xml, json, zip, ...) that contains all the users settings that you can backup to whatever backup solution one uses - be it a Network drive, One Drive, Google Drive, ... the flexibility is endless.

**Describe the solution you'd like**
As mentioned I simply would live a option that exports all settings from the App into a file and then a way to restore these settings from the same file. I really wouldn't mind if you had to log in to Lemmy again, after a restore, as that takes a few seconds, but manually restoring all the other settings can take way more time.

**Describe alternatives you've considered**
Probably the easiest alternative would be to use the App version of the App and use the Operating Systems Backup System. However that looks you into your Ecosystem's backup solution and for example prohibits changing between iOS and Android or different Browsers. I also don't think this would work for people who use the App on a Android phone without Google Play Services.

**Comment by aeharding** [comment]
Hi thanks for the issue!

This is currently being tracked in #366.
