### ISSUE TITLE
Allow hiding scores

### ISSUE THREAD

**Issue by httpjamesm** [aeharding/voyager#135]
Lemmy has an option that removes all counts of votes from posts and comments. I'd like to see a toggle in wefwef for this too. It would hide counts for posts, comments and profile pages as well. 

Related: https://lemmy.world/post/911284

**Comment by rsammelson** [comment]
I'm going to implement this and add it on to #185.

@aeharding Would you rather the hidden score get replaced by nothing or an en-dash ("–")?

**Comment by SocietasEvanescentes** [comment]
> I'm going to implement at least part of this and add it on to #185.
> 
> @aeharding Would you rather the hidden score get replaced by nothing or a dash ("–")?
> 
> <img alt="" width="150" src="https://user-images.githubusercontent.com/20521763/250717862-35a2d438-0e5b-4dfa-bf1d-32bf6c5a3854.png"> vs <img alt="" width="150" src="https://user-images.githubusercontent.com/20521763/250717935-23400659-249c-4200-95cb-001ba1bb4320.png">

OP didn't reply, but I'd go with it the number or any indicator being absent to be in unison with Lemmy instances; this way the score/voting system experience is carried across.

**Comment by rsammelson** [comment]
Yeah that's what I put in my draft PR, which is blocked by a settings storage change PR.
