### ISSUE TITLE
[Feature Request] Hide read posts

### ISSUE THREAD

**Issue by bagfatnick** [aeharding/voyager#136]
Hey all, firstly thanks so much for the hard work I can see being put into this. 

One of my most used features in Apollo was the hide read posts button. This was great when changing views / sorts to quickly find new posts. 

I think this will probably require some way of tracking what posts were already read / scrolled past, which I’m not sure is available in the Lemmy API. 

I can see there’s a PR to allow hiding posts. I wonder if that could be a starting point for this feature. 

Thanks again!

**Comment by aeharding** [comment]
Hi there. Thanks for the issue. Yes, once we get in #63 I can look into this.

**Comment by aperson** [comment]
Also, how about the ability to just hide posts that have been voted on?

**Comment by Daneish** [comment]
> Also, how about the ability to just hide posts that have been voted on?

As a work around, that feature is available through your Lemmy instance’s profile settings, which will then be reflected in wefwef.

- Login to your instance’s homepage in your browser (not Wefwef)
- Tap your account > Settings
- Untick Show Read Posts
- Save

<img width="575" alt="image" src="https://github.com/aeharding/wefwef/assets/26273432/53217a29-3b55-4937-8d64-a005ad87aece">

**Comment by aeharding** [comment]
Should be resolved :)

**Comment by bagfatnick** [comment]
Amazing work. I’m very pleased it works the same as it did in Apollo! 

Thanks again for everyone’s quick work on this.
