### ISSUE TITLE
Markdown tables decide if they need to wrap text before other markdown is processed

### ISSUE THREAD

**Issue by dandroid126** [aeharding/voyager#1380]
**Describe the bug**
If there is a table in markdown, and the contents of a cell contains markdown that is very long before being rendered, but not very long after it is rendered, the text in the cell is wrapped even when it shouldn't be.

**To Reproduce**

Create a table in a comment or post with this text:

```
| Match up | Time | Link |
|:-:|:-:|:-:|
| ![NJD](https://lemmy.ca/pictrs/image/eb1a001e-6e70-4cee-b412-6ffc41755d51.png) NJD 2 - ![BUF](https://lemmy.ca/pictrs/image/7c7d2a09-9283-4b2c-b66a-902ce43e4c6f.png) BUF 2 | 2nd - INT | https://lemmy.ca/comment/8289857 |
```

Or visit this page to see what it looks like: 

https://voyager.lemmy.ca/search/lemmy.ca/c/hockey/comments/18358886

**Expected behavior**
I expect that if the text can fit *after* all markdown is processed, that the text should not be wrapped.

**Screenshots**
Current behavior (cell with team logos is wrapped):
![image](https://github.com/aeharding/voyager/assets/11216025/b3860a77-0a87-420d-ab0f-d3a66c4d16c2)

What it looks like on other lemmy front-ends (cell with team logos is all on one line):
![image](https://github.com/aeharding/voyager/assets/11216025/77bf40ec-fa36-478d-b518-c6a5d3cc15b4)
![image](https://github.com/aeharding/voyager/assets/11216025/b6f55d33-1a85-4223-915f-1575470e35b4)
![image](https://github.com/aeharding/voyager/assets/11216025/4da5ede2-a950-4f83-ad1c-5bedebeb253a)

**Desktop (please complete the following information):**

- OS: Linux
- Browser: Chrome
- Version: 123.0.6312.86

**Smartphone (please complete the following information):**

- Device: Pixel 7
- OS: Android 14
- Browser: Voyager app
- Version: 2.2.5

**Additional context**
None to provide.

**Comment by aeharding** [comment]
Hi! Thanks for the report. How does this look to you?

<img width="455" alt="image" src="https://github.com/aeharding/voyager/assets/2166114/a0148506-25e7-4bb7-8638-b6bb5e2eafc5">
