### ISSUE TITLE
Select text button shows up when there's no text to select

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#140]
@httpjamesm, can you take a look at this? Mainly for URL posts.

Other issues:

 1. Select text dialog scrolls up/down when trying to select text. We should disable gestures for the dialog I think
 2. Select text contents needs a bit of padding
 3. Select text should use a text area or something that behaves a bit better on desktop. Right now, it's just text in the HTML

**Comment by httpjamesm** [comment]
I've addressed the first two. I don't understand the need for the third. On desktop I'm able to select just fine

**Comment by aeharding** [comment]
Thanks!

When I tap once on desktop Firefox, the headers are also selected.

<img width="915" alt="image" src="https://github.com/aeharding/wefwef/assets/2166114/c3dc5df2-d117-4cf3-94cc-1a7242b3bafa">

A text area would ensure you can only drag to select the text within the text area.

**Comment by httpjamesm** [comment]
Got it. I haven't tested it on Firefox.

**Comment by aeharding** [comment]
Should be resolved :)
