### ISSUE TITLE
Blocked communities still show if crossposted

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1401]
**Describe the bug**
I block meme communities but if i community i dont block has someone cross post a post from the community i block i see the post

**To Reproduce**

Block a community
Have someone crosspost a post from that community to one you dont block
You will see the post in your home/all feed

**Expected behavior**
All posts from communities you block should be blocked even if crossposted.

**Comment by sallyFoster** [comment]
To add to this, defederated communities still show in the results and in crossposting

**Comment by aeharding** [comment]
Hi, thanks for the issue!

All blocking logic is done by Lemmy, so this would be best asked there. Thanks.
