### ISSUE TITLE
Messages keeps crashing. 

### ISSUE THREAD

**Issue by KnottyLorri** [aeharding/voyager#1405]
If I take too long writing a message (I can get maybe 3 sentences out) the screen crashes and brings me back to the main feed.  It’s happened the last few days.  Maybe a week?

voyager app
Version 2.3.1
iPhone OS version 17.3.1
iPhone 15

Can’t screen shot a black screen.  It’s a BSOD (black not blue) :(

**Comment by aeharding** [comment]
By messages do you mean writing a DM? Can you provide a screenshot pre-crash?

**Comment by aeharding** [comment]
I was able to reproduce and I think I have a fix in the next release. Once its available please check it out and let me know! Thanks!
