### ISSUE TITLE
Crossposted text isnt showing up

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#1409]
**Describe the bug**
I crossposted a post to a different community but the text I wrote doesnt show up on voyager on the crossposted post even though if I edit it it shows up.

**To Reproduce**

1. Make a link post with text
2. Crosspost it
3. You wont see the text in the post

**Expected behavior**
Youd see the text like the original post

**Screenshots**

![image](https://github.com/aeharding/voyager/assets/114287507/3a91b66c-166b-4873-80a1-e3159e7940ed)

![image](https://github.com/aeharding/voyager/assets/114287507/27ec54a7-4589-4a45-ba4d-00eb1652dbcd)

![image](https://github.com/aeharding/voyager/assets/114287507/ba43e17a-c701-4051-8744-5494b468d860)

**Comment by aeharding** [comment]
Hey, thanks for the issue!

This is intentional. In this case, you should tap the crosspost to view full text.

Alternatively if you don't prefer this behavior, you can disable crosspost embed in Settings to get the normal Lemmy behavior.
