### ISSUE TITLE
Optional Voting Account for Privacy

### ISSUE THREAD

**Issue by Brendan-D15** [aeharding/voyager#1410]
**Is your feature request related to a problem? Please describe.**
Lemmy (and the fediverse) by nature is very public with our accounts and voting actions. All votes are essentially public info to anyone that knows how to pull that info (kbin users, dataminers/profilers, etc).

**Describe the solution you'd like**
I have a solution for Voyager. It's probably a big ask but it could potentially set Voyager above other apps in terms of fediverse privacy features.

If we had an option to setup a "voting account" Voyager could default to using that account for all voting actions no matter which active account has been selected (for commenting and Home view).

This would allow us to separate out voting information from commenting information, with the added benefit of helping us avoid instances of accidental double voting when switching across accounts.

There are a number of users who are used to anonymous voting (Redditors) who would appreciate a feature such as this. So having this as an option may help to draw more of their users into the fediverse and keep them around longer.

An initial implementation of this could default to displaying and executing votes through this account for all federated instances. If the user has a commenting account to an instance which is not federated with the voting account, then any votes made there would be done with the commenting account.

Possible future iterations of this would allow us to have multiple fallback accounts for voting. That way, if the main voting account is not federated with the instance currently being viewed, a fallback account which is federated with the instance could handle that vote action/display of votes.

**Describe alternatives you've considered**
Manually creating a voting account and only voting on comments/posts by switching to that account. It's not an ideal solution because it would require constant switching between accounts and I wouldn't be able to see any votes during normal browsing... alternatively I could browse exclusively with a voting account and only switch to a commenting account for posts/comments.

**Comment by aeharding** [comment]
Hi there! I've thought about this before, but it is not possible because when viewing a feed/thread, we dont know the vote status for each item. We could fetch from server, but Lemmy IDs don't correspond between servers.

As a workaround, what I recommend is you have an account you use for voting/browsing. Then, if you want to comment with a different account, you tap the header of the comment editor, and switch to a different account to post with.
