### ISSUE TITLE
Direct messages with multiple consecutive line breaks don't show the multiple line breaks.

### ISSUE THREAD

**Issue by dandroid126** [aeharding/voyager#1416]
**Describe the bug**
If you send a direct message on lemmy with multiple line breaks in a row, like for a paragraph break, after the message sends, the multiple line breaks are missing. This makes the formatting difficult to read when sending or receiving messages with paragraphs.

**To Reproduce**

1. Write a direct message with two or more line breaks in a row
2. Send the message
3. View the sent message in the conversation

**Expected behavior**
Multiple line breaks in a row should be visible after the message is sent. I suppose I expect it to look the same as lemmy-ui (screenshot included below)

**Screenshots**
Before sending:
![image](https://github.com/aeharding/voyager/assets/11216025/44fb02e4-bd62-4a0c-841f-1474016290d6)

After sending:
![image](https://github.com/aeharding/voyager/assets/11216025/b92f7060-2f14-45b3-8020-f0e70fcbf6bf)

How it looks on lemmy-ui. Even when there are 5 line breaks, they show at max two in a row: 
![image](https://github.com/aeharding/voyager/assets/11216025/70982ce8-3f39-4d0c-a57c-dd27f9299271)

**Desktop (please complete the following information):**

- OS: OpenSuse Tumbleweed
- Browser Chrome
- Version 123.0.6312.122

**Smartphone (please complete the following information):**

- Device: Pixel 7
- OS: Android 14
- Browser: Voyager app
- Version 2.4.0

**Comment by aeharding** [comment]
Thanks, should be fixed next release!
