### ISSUE TITLE
Text scrolling doesn't behave as it should while editing

### ISSUE THREAD

**Issue by Lightfire228** [aeharding/voyager#1442]
**Describe the bug**
If editing a large enough comment, the text scrolling / viewport will behave weirdly

**Expected behavior**

- The viewport should naturally scroll down as you add more text
- The viewport should snap to your cursor if
  - it's off screen
  - and you start typing

**Screenshots**
<details><summary>screen recording</summary>

https://github.com/aeharding/voyager/assets/15241322/1fc4fc4d-f92d-4b5d-8eca-4d541142d24d

</details>

**Smartphone:**

- Device: Samsung S23 Ultra
- OS: Android 13
- App Version: 1.32.7 (native)

**Additional Details**
It's consistent across phone reboots
It's consistent between writing a new comment and editing an old comment
It's consistent across keyboards (Swiftkey, Samsung, and Gboard)

**Comment by aeharding** [comment]
Hi there! Unfortunately I cannot reproduce. It is working fine for me. Can you provide any more information? Are you using the PWA or the native app? If the PWA, what browser + version?

**Comment by Lightfire228** [comment]
I'm using the native app, from F-Droid

**Comment by Lightfire228** [comment]
I just updated the app to 2.6.0, and the issue has been resolved

I keep forgetting that F-Droid doesn't automatically update apps
