### ISSUE TITLE
Some inbox notifications get truncated

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1444]
**Describe the bug**
Some inbox notifications are getting truncated

**To Reproduce**

None

**Expected behavior**
The notifications in inbox shouldn't be truncated

**Screenshots**

![image](https://github.com/aeharding/voyager/assets/104597302/2dc6096d-675f-4fae-a00b-1990aaf797ee)

![image](https://github.com/aeharding/voyager/assets/104597302/77b9e21b-6a3f-4a6e-82fa-2a5454c52790)

**Comment by aeharding** [comment]
Thanks, I was finally able to reproduce. This will be fixed in next release of Voyager!
