### ISSUE TITLE
Auto Embed YouTube Links

### ISSUE THREAD

**Issue by airjer** [aeharding/voyager#1449]
**Is your feature request related to a problem? Please describe.**

YouTube links have to be played out of the app in browser or directly in YouTube. 

**Describe the solution you'd like**

I would prefer that YouTube links get auto converted into an embedded video. Tesseract/Photon/Arctic/Lemmynade do this now.

**Comment by aeharding** [comment]
Hi!

This is not something I am willing to add to Voyager, for privacy and maintainability reasons.

As an alternative, I recommend linking to content on PeerTube. In the future, I plan on making this play very nicely in-app.
