### ISSUE TITLE
Default Sort setting doesn't include "Scaled"

### ISSUE THREAD

**Issue by zevdg** [aeharding/voyager#1456]
**Describe the bug**
Several new sorting methods were added in lemmy v0.19

PR #838 added them to voyager, but it only added one of them (controversial) to the default sort setting for some reason.

**To Reproduce**
1. Go to Settings
2. Click on "Default Sort"
3. See that "Scaled" is not listed as an option.

**Expected behavior**
Scaled should be a default sort option.
*Time-based Top sorts should probably be supported as well, but I care less about that.*

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/568234/8893da9d-9413-409c-b5e8-79491952ca4b)

tested on both desktop and mobile

**Desktop:**

- OS: ChromeOS
- Browser: Chrome
- Version: 2.7.1

**Smartphone:**

- Device: Pixel 7 Pro
- OS: Android
- Browser: App
- Version: 2.7.1

**Comment by aeharding** [comment]
Hi! I think you are viewing the default *comment* sort. Double check and let me know!

**Comment by zevdg** [comment]
Doh, you're totally correct. Feel free to close this issue, and sorry for the noise!

---

That said, consider repurposing this issue as a feature request (not a bug) to make the UX clearer, as other people may be making the same mistake.

Here's 2 UX suggestions that would help.

1. Change the label from "Default Sort" in both sections to "Default Post Sort" and "Default Comment Sort". 
    Add a test ensuring that no 2 settings on the same page have exactly the same label text.  "Default Sort" seems to be the only setting that appears twice in different sub-sections, but I would expect any 2 settings with the same exact name to cause confusion. 
    
2. Put each setting subsection into an "accordion" that are all collapsed by default.  Having the user actively tap into the "Posts" or "Comments" subsections would anchor the context in their user journey.
   Optionally, one could also configure the accordions so that only 1 would be expanded at any time, which would be another way of ensuring that 2 settings with the same name are not ever displayed on the screen simultaneously.

**Comment by aeharding** [comment]
Good to hear! And thanks for the potential ways to make it clearer. I'll add "post" and "comment" to title when action sheet is open to select the sort. However I want to avoid adding it to the settings list for now (it will make things more wordy/redundant, and while it does fit, it probably won't for some other labels).

However if others are also confused I'll try to further improve this. :)

Thanks!
