### ISSUE TITLE
Error when clicking on "Cancel" when starting a Private Message

### ISSUE THREAD

**Issue by azalty** [aeharding/voyager#1466]
**Describe the bug**
When starting a private message conversation, clicking on "Cancel" will display an error message indicating that the user is invalid, which could mean the OK and Cancel button both act like the OK button.

**To Reproduce**

1. Go to the Inbox tab
2. Click on Messages
3. Click on the top right icon to start a new conversation 
4. Don't enter anything and click Cancel

**Expected behavior**
Dismiss / hide the bar instead of evaluating what the user writes and displaying an error.

**Screenshots**
Probably not needed

**Smartphone (please complete the following information):**

- Device: Probably N/A
- OS: Probably N/A
- Browser: N/A
- Version: 2.8.1

**Additional context**
None

**Comment by aeharding** [comment]
Thanks! This will be fixed in the next release.
