### ISSUE TITLE
Toast messages should not appear over tab bar

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#147]
In Apollo, toast messages come up from *below* the tab bar and move up to appear right above it, instead of on top of it in wefwef (which is super annoying since you cannot dismiss).

This will likely require some CSS ionic hacking to change what a toast considers the bottom of the page, along with z-index hacking.

But this is absolutely a quality of life thing. :)

Anyone is welcome to take a shot at this.

Bonus points for making an ionic feature request (or finding one) to swipe away toast messages

**Comment by rsammelson** [comment]
See https://github.com/ionic-team/ionic-framework/issues/21769, it looks like a PR to add swipable toasts has been languishing for a couple years.
