### ISSUE TITLE
This specific image post doesn't load

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#1472]
Post in question: https://vger.app/profile/lemmy.ml/c/196@lemmy.blahaj.zone/comments/15488079

![image](https://github.com/aeharding/voyager/assets/715417/4379b51f-8a3f-4ce8-abe8-02b37f013874)

### Observations

- The post loads in web view: https://pawb.social/post/9689361
  - Thumbnail link: https://pawb.social/pictrs/image/2060d98d-fb9e-47bf-9074-cdf0f8a77199.jpeg?format=webp&thumbnail=256
  - Image Link: https://pawb.social/pictrs/image/2060d98d-fb9e-47bf-9074-cdf0f8a77199.jpeg
- The `post` data that we received is having the `thumbnail_url` as https://lemmy.blahaj.zone/pictrs/image/cc19d66b-2837-4f33-9480-ceac04bc7f8b.jpeg, which seems to be the cause of failure (link seems to be a 400 - bad request)

In `src/features/media/gallery/Media.tsx#getPostMedia`, the `if (post.post.thumbnail_url) return post.post.thumbnail_url` seems to be repeated

![image](https://github.com/aeharding/voyager/assets/715417/3c8070bc-79a0-4eb5-b6d1-20ec8ea27d1a)

I guess the idea was to load the thumbnail if its available or fall back to the post url. but in this specific case, the `thumbnail_url` seems to be invalid (pawb.social seems to be using a different link for displaying the thumbnail)

**Comment by sharunkumar** [comment]
Removing the line at 42 solves it but unsure if its the right way to fix this (basically use thumbnail as the fallback)

**Comment by aeharding** [comment]
This appears to be an instance misconfiguration/failure of https://lemmy.blahaj.zone/pictrs/image/cc19d66b-2837-4f33-9480-ceac04bc7f8b.jpeg (operation timed out).

There might be a workaround, but it's probably best to reach out to the instance admins.

**Comment by aeharding** [comment]
I just checked and lemmy-ui has the same problem: https://lemmy.ml/post/15488079?scrollToComments=true

Image is broken on lemmy.ml, but works on the fedilink (pawb.social) https://pawb.social/post/9689361

**Comment by aeharding** [comment]
I have a potential fix in #1477, let me know what you think of that approach.
