### ISSUE TITLE
After hiding read posts, they cannot be unhidden

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1476]
**Describe the bug**
After hiding the read posts, no option for making them visible again shows up

**To Reproduce**

1. Go to the ellipsis 
2. Tap on hide posts
3. Repeat step 1
4. Try to find an option to unhide the read posts

**Expected behavior**
One should be able to unhide already read posts after hiding them.

**Screenshots**
https://github.com/aeharding/voyager/assets/104597302/55d02c7c-b3d0-4708-959d-ce8da4c5fcae

**Comment by aeharding** [comment]
You can go to Profile -> Hidden Posts -> Reset to unhide.
