### ISSUE TITLE
Usernames overlap with header text when Always Show Author is enabled

### ISSUE THREAD

**Issue by InterstellarOne** [aeharding/voyager#1479]
**Describe the bug**
When Always Show Author is enabled in settings, the instance will overlap with the **Posts** or **Comments** header text.

**To Reproduce**

1. Turn on Always Show Author in Appearance settings
2. Go to the profile of a user on a remote instance, preferably with a long name
3. Click on either Comments or Posts
4. If on desktop, resize / zoom the browser window to a mobile aspect ratio

**Expected behavior**
The text should not overlap.

**Screenshots**
![Screenshot_20240512_210231](https://github.com/aeharding/voyager/assets/63889949/46026f48-0748-4041-80ce-1f86f830dfe8)

**Desktop (please complete the following information):**

- OS: [tested on Fedora with Firefox and Chrome]
- Version [2.9.1]

**Smartphone (please complete the following information):**

- Device: [Android]
- OS: [14]
- Version [2.9.1]

**Additional context**

**Comment by aeharding** [comment]
Thanks for the report, this is being tracked in https://github.com/aeharding/voyager/issues/313#issuecomment-1626369229
