### ISSUE TITLE
App pauses other audio, even when content is muted

### ISSUE THREAD

**Issue by DaveAlton** [aeharding/voyager#1480]
**Describe the bug**
Users can't play music while scrolling on Voyager. This is because any auto playing content pauses the background audio from other apps. Even when the content in Voyager is muted

**To Reproduce**

1. Play music 
2. Open Voyager
3. Scroll down to a gif or video that is normally already muted
4. Music pauses, even though Voyager isn't playing audio. 

**Expected behavior**
Music should only pause when audio in Voyager is unmuted

- OS: iOS
- Version 2.9.1

**Smartphone (please complete the following information):**

- Device: iPhone 15 Pro Max
- OS: iOS 17.4.1

**Comment by aeharding** [comment]
Hi there! I just checked and it is working fine for me. It will only pause background music when tapping muted button on the video.

Can you try restarting your device? If you could try another device and see if there's specific reproduction steps that cause this, that would help too. Thanks.

**Comment by DaveAlton** [comment]
Thanks so much for even looking. I force quit the app and it started working fine. 

Just for future recordkeeping, this was when browsing gifs@lemmy.world
