### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DhvcaqDew** [aeharding/voyager#1486]
### Crash description

 i must admit i forgot what i was doing specifically because it took me a few minutes to set up a github account... I think i was zooming around an image. Sorry about that, hope this is still helpful

### Device and app metadata

  - window.location.href: `https://localhost/posts/lemmy.zip/c/gonewild@lemmynsfw.com/comments/15604532`
  - react-router location.pathname: `/posts/lemmy.zip/c/gonewild@lemmynsfw.com/comments/15604532`
  - Logged in? `true`
  - Native app? `true`
  - Installed to home screen? `true`
  - Voyager version: `2.10.0`
  - BUILD_FOSS_ONLY: `false`
  - User agent: `Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/AP1A.240505.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.53 Mobile Safari/537.36`

### Crash data

Error: ``TypeError: Cannot read properties of undefined (reading 'split')``

#### Stack trace

```
TypeError: Cannot read properties of undefined (reading 'split')
    at T$ (https://localhost/index.js:219:345893)
    at YU (https://localhost/index.js:244:58537)
    at https://localhost/index.js:244:57627
    at https://localhost/index.js:212:46536
    at s (https://localhost/index.js:212:45775)
    at https://localhost/index.js:212:46620
    at s (https://localhost/index.js:212:45775)
    at s (https://localhost/index.js:244:1561)
    at c (https://localhost/index.js:244:535)
    at https://localhost/index.js:244:636

**Comment by aeharding** [comment]
Thanks for the bug report! This should be fixed in an upcoming release of Voyager.
