### ISSUE TITLE
Mod tools temporary ban with remove content doesn't work

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#1494]
**Describe the bug**
As a mod, I tried temporarily banning a user (banning them for 14 days) and removing their content. It didn't work. 

**Expected behavior**
The user should be banned for 14 days and their content removed.

**Comment by aeharding** [comment]
Hi!

I just checked, and it worked for me. If there's any more information you can provide, that would be helpful.

<img width="530" alt="image" src="https://github.com/aeharding/voyager/assets/2166114/6be2b36a-0d9c-4097-a10d-9d267c516e15">

**Comment by sallyFoster** [comment]
Yeah, I was using the Lemmy.ml instance and added 14 days and didn't select "permanent", but did select "remove content"

**Comment by sallyFoster** [comment]
It says banned on top, but when you check the mod log, nothing shows up

**Comment by sallyFoster** [comment]
@aeharding This still doesn't work properly for me on lemmy.ml
