### ISSUE TITLE
Option to show text of collapsed comment 

### ISSUE THREAD

**Issue by GitBarns** [aeharding/voyager#152]
Simple as it sounds, please add the to option to show the text of the comment I collapsed. In other words, when tapping on a comment to collapse it, it will collapse the child comments, not the tapped comment.

Many of the reddit apps had this behavior and now Jerboa also added it ("show content for collapsed comment")

**Comment by rsammelson** [comment]
I'll work on this

**Comment by rsammelson** [comment]
I have a patch figured out but I'm waiting on #246

**Comment by rsammelson** [comment]
This is done but waiting on #209 because I did some cleanup there and didn't want this to cause merge conflicts.

**Comment by aeharding** [comment]
I don't believe this is an Apollo feature, but if anyone can confirm I would appreciate it.

**Comment by rsammelson** [comment]
Does that stop us from adding it?
