### ISSUE TITLE
GIFs are converted to JPEGs on upload

### ISSUE THREAD

**Issue by bjoern-tantau** [aeharding/voyager#1524]
**Describe the bug**

When I upload a gif to a comment or a post it's converted to a jpeg.

**To Reproduce**

1. Go to a post
2. Add comment
3. Add image
4. Select an animated gif
5. See that the URL of the uploaded image ends in .jpeg

**Expected behavior**

Every file should be uploaded without any changes.

**Smartphone (please complete the following information):**

- Device: Fairphone 3
- OS: Android 13
- Native App
- Version: 2.12.1

**Additional context**

You can see it at https://swg-empire.de/post/1121002

The gif in https://swg-empire.de/comment/2854984 was uploaded via Lemmy's web interface.

The gif in https://swg-empire.de/comment/2854990 was uploaded via Voyager.

**Comment by bjoern-tantau** [comment]
Also happens with Voyager web version 2.5.0.

**Comment by aeharding** [comment]
Hi! I have a fix for the next release of Voyager.

Please note, that if your instance doesn't allow uploading large images (> 1MB), large animated GIFs will fail to upload.
