### ISSUE TITLE
It struggles with some urls ending in mp4 where browser doesn't

### ISSUE THREAD

**Issue by fusir** [aeharding/voyager#1537]
It seems that the browser is able to view some posts that Voyager isn't.

### To Reproduce
Visit this post both in the browser and in Voyager:  
https://lemmy.world/post/17667634

### Expected behavior
Let's the user navigate to the video

Or perhapse because it ends in .mp4 it might be a hybrid url and a sec-fetch-dest:video header might need to be sent.

**Comment by aeharding** [comment]
Thanks, this should be fixed for that URL in the next release of Voyager.
