### ISSUE TITLE
Decrement comment count for blocked user comments

### ISSUE THREAD

**Issue by hungryca-t** [aeharding/voyager#1550]
**Is your feature request related to a problem? Please describe.**
The feed comment count under a post accounts for blocked user comments, though on viewing the post, the comment is not visible. For example, if a post has a single comment according to the comment counter, and that comment was posted by a blocked user, opening the post will reveal there are no comments.

This is particularly noticeable since I have blocked a media bias checker bot, which is frequently the first if not the only commenter on news-related posts. When scrolling through my feed, the comment count will be 1, but when loading the post, I discover there are no visible comments and realize the counter is considering the bot’s comment.

**Describe the solution you'd like**
Decrement the feed comment counter for posts with comments posted by blocked users.

**Describe alternatives you've considered**
Open a post with a comment and find there is actually no visible comment, repeatedly. Sigh.

**Additional context**
Feed:
<img width="375" alt="image" src="https://github.com/user-attachments/assets/b78e23b8-495d-4a0f-abac-84e711c20e81">

Post:
<img width="375" alt="image" src="https://github.com/user-attachments/assets/f0e5c0d2-fd1a-40e8-9c45-438388b14e55">

**Comment by aeharding** [comment]
Hi!

This is a Lemmy bug. If you look at the same post in lemmy-ui, you should see the same issue.

Can you search for/or create a new issue with Lemmy?

Thanks!
