### ISSUE TITLE
Subscribe button on top right of a Post

### ISSUE THREAD

**Issue by brdrquack** [aeharding/voyager#1564]
**Is your feature request related to a problem? Please describe.**

As a new User of Lemmy i have to subscribe to a lot of communitys to build my Subscription Tab where i only see what i am interested in. 
But to do that i allways have to click on the community->click on the three dots inside the community->click subscribe. 

**Describe the solution you'd like**

I want a button on the top right of the post i am seeing that says "Subscribe" ONLY if i am not only subscribed to that community.

**Describe alternatives you've considered**

An Alternative would be to have the option of subing in the three dots to the left of the "Upvote" button.

**Additional context**

**Comment by aeharding** [comment]
Hi!

Thanks for the report, but you can tap and hold the community name to subscribe in-feed. LMK if you are having issues with that!

Also there is a separate issue somewhere to add subscribe status to the community label.
