### ISSUE TITLE
Make it easier to run Playwright tests

### ISSUE THREAD

**Issue by aashu16** [aeharding/voyager#1576]
**Is your feature request related to a problem? Please describe.**

I am trying to update the e2e GH action to set up a local Lemmy stack in order to allow Playwright tests to make real API calls instead of mocking them.

To make this work,
- The local Lemmy API server needs TLS configuration (using a reverse proxy and self-signed certificates) since the url builder always prepends `https://` to server names provided.
- Custom Lemmy servers can only be provided by configuring the `/_config` endpoint.

These problems are not insurmountable and I have managed to come up with a solution that works but not without adding unnecessary complexity to the testing stack without improving the quality of the tests. In the interest of simplifying the testing environment, I would like to suggest a couple of changes.

These changes could possibly allow users to misconfigure Voyager instances. It should, however, be easy enough to ensure that one would have to go out of their way to be able to do so.

**Describe the solution you'd like**

The following changes should be restricted to development and CI environments.
1. An easier way to provide Voyager with a list of Lemmy servers - either hardcoded or via an env var.
2. Base URL builder should be able to use `http://`.

Happy to discuss alternatives and/or concerns.

**Comment by aeharding** [comment]
Seems totally reasonable! However 2 will be a bit harder - right now, it is assumed https. I will have to research a bit further.

**Comment by aashu16** [comment]
Sure. Thanks for the prompt response. 

I don’t remember exactly where but there is a function that builds the base URL that the app then uses to make all API calls. Just out of curiosity, and this might be a bit of a stupid question, does #2 require introducing more complexity than updating the said function to conditionally build the URL based on the values of a couple of env vars?

**Comment by aeharding** [comment]
It's not too bad if we can force all lemmy connections to http for testing purposes. Made a PR (#1577) so let me know what you think about that approach.

**Comment by aashu16** [comment]
Thanks. I will take a look later this evening.
