### ISSUE TITLE
Search: all instance posts

### ISSUE THREAD

**Issue by jujubeja** [aeharding/voyager#1588]
**Is your feature request related to a problem? Please describe.**
As user
I want to add multiple instances of lemmy
So that you can view posts from all instances that do not follow each other

**Describe the solution you'd like**

Enable full instance search
https://lemmy.world/search?q=%s
https://lemm.ee/search?q=%s

Load List: import instance list by url .txt and .toml and .json
```
https://raw.githubusercontent.com/aeharding/voyager/main/instances.toml
https://github.com/aeharding/voyager/blob/main/instances.toml
```

**Additional context**
full instance list
https://data.lemmyverse.net/
https://lemmy.fediverse.observer/list

**Comment by aeharding** [comment]
Hi there!

As mentioned on #1600 unfortunately Play Store limits the number of domains on the list, so I can't add everything.
