### ISSUE TITLE
Android app crashes on Windows path click

### ISSUE THREAD

**Issue by jim3692** [aeharding/voyager#1598]
**Describe the bug**
The Android app crashes if an embedded file with a Windows path is clicked.

**To Reproduce**
Go to this comment with Android app: https://lemmy.world/comment/12259665

Click the URL

**Expected behavior**
An error message showing that the path does not exist, or do not show the path as embedded link.

**Screenshots**
![Screenshot_20240909-173337_Voyager.png](https://github.com/user-attachments/assets/f5efb0cd-7abf-44d6-80e0-7f690d445388)

**Smartphone (please complete the following information):**

- Device: OnePlus 6T McLaren
- OS: Android 11 (LineageOS 18.1)
- Voyager 2.17.0 from F-Droid

**Comment by aeharding** [comment]
Thanks for the report! This should be fixed in the next release.
