### ISSUE TITLE
Add vegantheoryclub.org to Pick Server List 

### ISSUE THREAD

**Issue by Ralimbahere** [aeharding/voyager#1603]
It would really improve the ease of use for VCT users to start using Voyager if the option was there.

The instance could go under the Niche category. The description: Vegan Theory Club: Lemmy for Vegans.

However the instance will have to create a legal page listing the terms of service and privacy policy.

**Comment by aeharding** [comment]
Hi there! I'll add this as a login suggestion instance. If you want it added as a signup recommendation instance, get some TOS/privacy info added to /legal and I would be happy to add :)

**Comment by Ralimbahere** [comment]
Hello Aeharding!

The TOS/Privacy information as been added at https://vegantheoryclub.org/legal

Thank you for your great work!

**Comment by Ralimbahere** [comment]
> Hi there! I'll add this as a login suggestion instance. If you want it added as a signup recommendation instance, get some TOS/privacy info added to /legal and I would be happy to add :)

Hello Aeharding!

The TOS/Privacy information as been added at https://vegantheoryclub.org/legal

Thank you for your great work!

**Comment by aeharding** [comment]
Should be added to niche category in next release, thanks!
