### ISSUE TITLE
Favorites missing from communities screen

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#1606]
**Describe the bug**
Twice recently, I have opened the Communities screen and the Favorites section was missing. Below Home/All/Local, the alphabetical list of my subscribed communities was present, without my Favorites visible. Upon force closing the app and re-opening, Favorites was visible once again. 

**To Reproduce**

This has not had a reliable/reproducible trigger, but I will described the typical workflow that I use that has resulted in the problem behavior a few times. 

1. Open Voyager after it being closed for a few hours (the Posts screen is immediately visible -- unsure if this is default behavior or my last-used screen before minimizing the app). 
2. Tap the Posts icon again to open the Communities screen. 
3. Encounter Communities screen with Favorites missing. 

**Expected behavior**
I expect Favorites to be visible every time I open the Communities screen while using an account that has Favorites. 

**Screenshots**
This issue has taken me by surprise and I have reflexively force closed each time. I will add screenshots if I encounter it again. 

**Smartphone (please complete the following information):**

- Device: iPhone 13 Mini
- OS: 17.6.1
- Browser: N/A, native iOS app
- Version: 2.17.1

**Additional context**

**Comment by aeharding** [comment]
Hi there! I believe this is the same issue mentioned in https://github.com/aeharding/voyager/issues/1608#issuecomment-2381435802. Please try the steps I mention and LMK if that temporarily resolves the issue.

I'm going to close this so we can track everythng in one place. But rest assured I am aware. :)

Thanks!
Alex

**Comment by gobbledygoober** [comment]
> Hi there! I believe this is the same issue mentioned in [#1608 (comment)](https://github.com/aeharding/voyager/issues/1608#issuecomment-2381435802). Please try the steps I mention and LMK if that temporarily resolves the issue.
> 
> I'm going to close this so we can track everythng in one place. But rest assured I am aware. :)
> 
> Thanks! Alex

That sounds like it! Thanks for tracking the issue. I’ll subscribe to #1608.
