### ISSUE TITLE
Add Italian translation for the app? (I could do it)

### ISSUE THREAD

**Issue by sudcapitano** [aeharding/voyager#1631]
**Is your feature request related to a problem? Please describe.**
Yes, every app on my phone is in Italian and I thought why not do it for this app too, if it means I have to do then sure. I already translated 3 or 4 apps by now. 

**Describe the solution you'd like**
I can translate the app to Italian, just show me where to do it, since usually they have some site to do it on. 

**Describe alternatives you've considered**
None. I can translate the app. 

**Additional context**
None

**Comment by aeharding** [comment]
Hi there! Thank you for volunteering to help out!

I am tracking this request here: https://github.com/aeharding/voyager/issues/1109 Please cc yourself so you can contribute when the time comes!
