### ISSUE TITLE
[Feature request] Option to toggle NSFW posts per feed (Home / All / Local)

### ISSUE THREAD

**Issue by Rellegeight** [aeharding/voyager#167]
I would like to see the option to quickly toggle the visibility of NSFW posts, especially for the "All" feed. Could be a part of a three-dot menu on the main tab (next to post sorting).

**Comment by aeharding** [comment]
I think the preferred approach is to have multiple accounts. We could hide per feed, but that introduces a lot of configuration complexity. Hopefully that works for you!
