### ISSUE TITLE
[Feature request] Show downvote counter

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#170]
For parity with main Lemmy site

**Comment by RocketRide9** [comment]
![F97369FE-2323-4131-827A-FA6F6E6D3910](https://github.com/aeharding/wefwef/assets/70429241/0e0f5030-453d-40e0-b1fb-9f5b988af235)

**Comment by rsammelson** [comment]
I am working on implementing this

**Comment by aeharding** [comment]
@rsammelson Please hold off on implementing this for now, it needs to be triaged.

**Comment by rsammelson** [comment]
@aeharding Sorry, I didn't see your message before finishing the feature.
