### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [aeharding/voyager#1711]
F-Droid's cleaning step removes non free dep pull line like `INFO: Removing usual suspect 'com.android.billingclient' at node_modules/.pnpm/capacitor-tips@1.0.0_@capacitor+core@6.1.2/node_modules/capacitor-tips/android/build.gradle`

and that was fine until now: 
```
FAILURE: Build failed with an exception.
* What went wrong:
Could not determine the dependencies of task ':app:lintVitalReportRelease'.
> Could not resolve all dependencies for configuration ':app:releaseCompileClasspath'.
   > Could not resolve project :capacitor-tips.
     Required by:
         project :app
      > No matching variant of project :capacitor-tips was found. The consumer was configured to find a library for use during compile-time, preferably optimized for Android, as well as attribute 'com.android.build.api.attributes.AgpVersionAttr' with value '8.7.2', attribute 'com.android.build.api.attributes.BuildTypeAttr' with value 'release', attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' but:
          - No variants exist.
```

any reason `capacitor-tips` is now a dependency even if we want `BUILD_FOSS_ONLY=true` ?

ref: https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/8342346703#L732

**Comment by aeharding** [comment]
Hi there! Thanks for letting me know. This was fixed in #1703, so I just need to cut another release.

**Comment by licaon-kter** [comment]
maybe clean the cache or something? https://gitlab.com/fdroid/fdroiddata/-/jobs/8361075530

difflog: [vay356.log](https://github.com/user-attachments/files/17746722/vay356.log)

**Comment by aeharding** [comment]
ah. looks like the app enviornment isn't being properly set up. I'll try to fix it later.

<img width="2140" alt="Screenshot 2024-11-14 at 11 30 59 AM" src="https://github.com/user-attachments/assets/7c8d97d3-b426-459d-9f1a-7e437a082bca">
