### ISSUE TITLE
Nothing loads after update

### ISSUE THREAD

**Issue by pilotMike** [aeharding/voyager#1713]
<img width="1721" alt="Screenshot 2024-11-13 at 5 02 42 PM" src="https://github.com/user-attachments/assets/a41e9c4f-c66e-451a-800f-33dec7e7bd59">

`ReferenceError: Can't find variable: APP_BUILD`
`Unhandled Promise Rejection: ReferenceError: Cannot access uninitialized variable.`

**Comment by aeharding** [comment]
Sorry, fixed now. Close all vger.app tabs and reopen (maybe 2x) and it should be working again.
