### ISSUE TITLE
iOS dark mode icons not working in >=2.19

### ISSUE THREAD

**Issue by mrtzlbm** [aeharding/voyager#1717]
Since the update to 2.19 the dark mode icons on iOS are no longer working. (installed from TestFlight)

Reinstall & phone reboot as well as switching to light mode and back does not fix the issue.

- Device: iPhone 15 Pro
- OS: iOS 18.1
- Version: 2.19, 2.19.1 (installed from TestFlight)

**Comment by aeharding** [comment]
Thanks for letting me know. Sounds like the github build agent xcode version is just old. Lame
