### ISSUE TITLE
Crash on specific post

### ISSUE THREAD

**Issue by johnyb0y** [aeharding/voyager#1735]
**Describe the bug**
Post: https://startrek.website/post/16492329

This post crashes Voyager. Only when one clicks on the post title. Opening the thumbnail is fine. 
**To Reproduce**

1. Open this post in voyager by clicking on the post title:
https://startrek.website/post/16492329

**Expected behavior**
No crash. 

**Screenshots**
![image](https://github.com/user-attachments/assets/36293b47-eab4-4d9c-8303-fd68f3aac176)
![image](https://github.com/user-attachments/assets/9b5bf904-f436-4c93-bade-3da8db60a561)

**Desktop (please complete the following information):**

- OS: [e.g. iOS] iOS 18.1

**Smartphone (please complete the following information):**

- Device: [e.g. iPhone6] iPhone 14 Pro 
- OS: [e.g. iOS8.1] iOS 18.1

**Additional context**

**Comment by aeharding** [comment]
Hell yeah first bug found from beta track automated deployments! Thank you, I'll fix and get a new build out tonight.

**Comment by johnyb0y** [comment]
> Hell yeah first bug found from beta track automated deployments! Thank you, I'll fix and get a new build out tonight.

Sure thing, thank you 😄
