### ISSUE TITLE
NSFW Blur failing to apply consistently

### ISSUE THREAD

**Issue by kminardo** [aeharding/voyager#1770]
**Describe the bug**
When scrolling a feed (All or Community), occasionally NSFW pictures are not blurred displaying full content.
Scrolling past the image and back to it, or viewing comments and returning to the feed, will blur the image.
It appears to occur most often while displaying crossposted content/images.

**To Reproduce**
1. Ensure "Blur NSFW" set to "In Feed" in Appearance Settings
3. Go to a NSFW community with many crossposts (I found it easy to replicate using NSFW AI image communities)
4. Scroll the feed
5. The first few posts shown will be blurred as expected, further posts as additional images load, will not have blur filter.

**Expected behavior**
I expect all appropriately tagged NSFW posts to be blurred.

**Screenshots**
<details>
<summary><b>!! NSFW !!</b> Image of feed with mixed blurring</summary>
<img src="https://github.com/user-attachments/assets/2002d6c8-9278-4933-84fa-51ae28ec9d0d" />
</details>

**Desktop**
Not tested

**Smartphone**
- Device: Samsung Galaxy S23+
- OS: Android 14 / One UI 6.1
- Browser: Play Store Voyager App
- Version: 2.20.0

**Comment by aeharding** [comment]
Hi there! Thanks for the issue. I am unable to reproduce on my Pixel nor Samsung device unfortunately.

Is this consistently reproducible with the exact same posts? Also, if you have some time, can you let me know the exact version of Voyager where this bug started happening? You can download older versions of Voyager on Github Releases.

Thank you!

**Comment by aeharding** [comment]
Strike that! I wasn't able to reproduce logging onto lemmynsfw.com, but I was when logged in to sh.itjust.works and viewing a lemmynsfw community with crossposts. Fun edge case!
