### ISSUE TITLE
Add a signature to all posts and/or comments

### ISSUE THREAD

**Issue by gragorther** [aeharding/voyager#1774]
**Is your feature request related to a problem? Please describe.**
I'd like to add a non-commercial license to all of my posts and comments, so AI companies can't use it for training. 

**Describe the solution you'd like**
I'd like an option in the settings that can add a link or text to the bottom of posts and comments, maybe even an option that allows you to select specific text to be used for posts and one for comments. Having the option to be able to select where the signature is displayed would also be great. 

**Describe alternatives you've considered**
There could also be a simple toggle that when enabled allows one to select under which license to put posts and comments.

**Comment by aeharding** [comment]
Hi! Have you tried asking Lemmy for this? I think it would be more appropriate there because then it could be separate from the content of the post. Similar to forum software signature section. I'll close this for now.
