### ISSUE TITLE
Account age incorrect

### ISSUE THREAD

**Issue by ItzzCode** [aeharding/voyager#1778]
**Describe the bug**
In the account tab, there is a statistic showing your account's age. At the moment it displays "2y" for me, which is incorrect, since my account was created 2023.

(It does seem like it's rounding the age up, which I'm assuming here is unintended.)

**Expected behavior**
I would expect the counter to say "1y", because that's my account's current age.

**Screenshots**
![image](https://github.com/user-attachments/assets/560e5361-35da-4033-823f-8141856d971a)
![image](https://github.com/user-attachments/assets/b163ab7a-2250-4ac5-ae7b-56ec839731d7)

- Device: iPhone 14
- OS: iOS 18.1.1
- Version: 2.21.0

**Comment by aeharding** [comment]
Hey! Thanks for the issue. This makes sense, I'll look into it soon.
