### ISSUE TITLE
Setting to change how profile tab button label is displayed

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#186]
Should have an option to switch between "show instance URL", "show username" and "hide" (should static "Profile" text)

This is not prioritized, just throwing in a bug to track

**Comment by GobinathAL** [comment]
@aeharding I'm currently working on this. I have a doubt to be clarified. What should be shown as text if the user has selected "show username" option? Should it be the full handle (eg., username@lemmy.ml) or just the username alone? If we have to show the username alone, then it should be the username from activeHandle right?
