### ISSUE TITLE
Feed sort persists globally

### ISSUE THREAD

**Issue by bdonvr** [aeharding/voyager#198]
This provides a bad user experience - after updating to 11.0 I immediately tried out the new "Top" sorting options. Then I searched for a community and only saw one post there as I didn't realize I was still on Top -> Hour

It's also inconsistent with Apollo. 

Ideally, this would eventually be configurable along with default sort method options for the home feed and community feeds, independently.

**Comment by aeharding** [comment]
I believe in apollo comment sort doesn't persist between feeds, but post sort does.

However as you said I think there's an option to configure per-community persisted sort

**Comment by bdonvr** [comment]
> I believe in apollo comment sort doesn't persist between feeds, but post sort does.
> 
> 
> 
> However as you said I think there's an option to configure per-community persisted sort

Well I know for sure in Apollo if you changed your home feed sort to "new" for example, then went to the "search" tab and opened a subreddit, that subreddit would not be sorted by new. You could then change the sort on that sub to "Top -> Hour", switch back to your home feed tab and find the feed still on "New"

Though I can't say for sure if that's all down to the settings I enabled. But it's how I always used it.

As it is on WefWef I could be browsing the home feed, find a comment that links to a community, sort it by "Top -> All Time" to see what that community is all about, then leave the community to return to browsing my home feed. But now my home feed is Top -> All Time and I've lost my place.

**Comment by mdecourcy** [comment]
@aeharding should this wait for the settings overhaul you had mentioned? Or can anyone pick this up

**Comment by aeharding** [comment]
Yeah, let's just rip persistence out. I don't know why I thought it persisted. Maybe I had some option on? I just tried on Apollo and it resets every time I nav to a new sub.

Let's do it similar to comment thread sort for now.

Persist per sub will be a future enhancement.

**Comment by mdecourcy** [comment]
Cool, will also open an issue to pull scrolIUpIfNeeded into a helper function, and call that on sort change. 

As of now, sort will change and new posts will populate, but the user's page will remain at the scroll percentage they were at before changing the sort.

**Comment by mdecourcy** [comment]
Cool, will also open an issue to pull scrolIUpIfNeeded into a helper function, and call that on sort change. 

As of now, sort will change and new posts will populate, but the user's page will remain at the scroll percentage they were at before changing the sort.

**Comment by aeharding** [comment]
agree that's jank and virtuoso doesn't like it either :D

**Comment by bdonvr** [comment]
Definitely one of the biggest things for me, I keep finding cool communities, sorting by top -> all then coming back to the main feed to find everything out of order - losing my place

**Comment by aeharding** [comment]
This will be resolved in the next version. :)

I have created a new issue for an enhancement for an option to persist sort per community here: https://github.com/aeharding/voyager/issues/1008
