### ISSUE TITLE
"Problem fetching posts. Please try again." - Any way to force a retry?

### ISSUE THREAD

**Issue by mbentley** [aeharding/voyager#213]
When browsing posts on a busy instance, sometimes I see the message "Problem fetching posts. Please try again." and the issue is that when I am scrolling through a large number of posts over a period of time, I don't want to have to go back to the top and do a refresh to get the page to retry the loading of the next page.  That means I would have to scroll back down to my previous location to get back to to the previous location.

I didn't see any sort of swipe gesture that worked to do a retry but it seems like maybe a swipe from the bottom up on an empty list might be the sort of gesture I would expect to work on retrying that, if there isn't some other method defined.

**Comment by molkemon** [comment]
Same, the inability to force a reload without scrolling back to top and the behaviour that back on opened pictures navigates back to communities underneath are... Shall we say very stress inducing.

**Comment by aeharding** [comment]
Related to https://github.com/petyosi/react-virtuoso/issues/182. We need smarter logic. I plan on working on this one

**Comment by shyney7** [comment]
I have the same issue. App is unusable the whole day.

**Comment by csm10495** [comment]
I think this is happening to me right now: ![Screenshot_20230721-233820.png](https://github.com/aeharding/voyager/assets/5749838/cc3c41be-e1a8-4454-8d74-b4a390bee1a2)

Tried restarting the app, clearing cache, etc. Cleared site data in Chrome. No dice.

Any workarounds?

**Comment by csm10495** [comment]
@aeharding this doesn't fully seem to be fixed. I still can't reload my profile or subscriptions.

(See profile image on https://github.com/aeharding/voyager/issues/213#issuecomment-1646507951)

Is that a different issue?

**Comment by aeharding** [comment]
Yeah, that's a different issue, but I'm not sure why that's happening for you

**Comment by shyney7** [comment]
I'm also still unable to see any posts:

![Screenshot_20230723_091521_Brave.jpg](https://github.com/aeharding/voyager/assets/17785769/7cd721ad-56a5-4403-a18a-701acd4ffb2b)

![Screenshot_20230723_091459_Brave.jpg](https://github.com/aeharding/voyager/assets/17785769/9becd7ac-865b-4550-9824-da512c98650b)
