### ISSUE TITLE
Bottom nav icons have weird artifacts (tiny spikes)

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#215]
If you look at the bottom navigation icons closely, you can see some tiny spikes which most likely aren't there on purpose:

!["Posts" close up](https://github.com/aeharding/wefwef/assets/20093825/8c990afd-5809-45c3-8a8e-8e965a338a1c)
![Bottom Nav](https://github.com/aeharding/wefwef/assets/20093825/01be43cb-b42e-4b75-8c3f-c5818d531c22)

**Comment by aeharding** [comment]
Phone model and OS version?

**Comment by fer0n** [comment]
Device: iPhone 12 Pro
OS: iOS 16.6
Version: 0.11.1

**Comment by aeharding** [comment]
I can replicate in https://ionic-react-conference-app.firebaseapp.com/about.

Therefore, I believe this is an Ionic or Ion Icons bug. Please make an issue with one of those projects and tag this issue so we can stay informed :)

**Comment by fer0n** [comment]
@aeharding https://github.com/ionic-team/ionicons/issues/1176

**Comment by aeharding** [comment]
Thanks!

If you can confirm that workaround works, feel free to make a pr

**Comment by aeharding** [comment]
Reopening, I still get jagged icons

**Comment by fer0n** [comment]
I'll have another look tomorrow, for it was definitely gone but maybe I was missing something. Sorry for the inconvenience

**Comment by fer0n** [comment]
What device were you testing it on @aeharding?

**Comment by aeharding** [comment]
I'm using an iPhone 13 mini. Should be using latest iOS :)

**Comment by fer0n** [comment]
I had another look, the fix works on the iOS Simulator and on macOS in Safari. 
[Simulator Screen Shot - iPhone 13 mini](https://github.com/aeharding/wefwef/assets/20093825/c49354cc-f74a-4d28-b1b0-dfe6d8aac960).

However, no matter what I do I can't get it to work on the actual iPhone. I guess we'll have to hope that the ionicon issue will be fixed or maybe a newer iOS Version will fix it. In the mean time, if you think it's worth having that line to fix it on desktop safari you could enable it again, but otherwise I think we're out of luck, sorry.

**Comment by fer0n** [comment]
Maybe there's another way to solve this, but it's probably not going to be as clean as the first approach. I'll see what solution I can come up with and then you can decide if it's worth merging

**Comment by fer0n** [comment]
@aeharding I opened a PR (#281) for the new fix, as I mentioned it's not as clean and quick as the first one, but the best solution I could come up with.

**Comment by aeharding** [comment]
@fer0n can you confirm if this is solved for you in latest iOS?

**Comment by fer0n** [comment]
@aeharding Yes, the issue is gone 🎉
Thanks 😊
