### ISSUE TITLE
Feature Request: Allow community block/filter list

### ISSUE THREAD

**Issue by josefwells** [aeharding/voyager#217]
Sometimes you run across a community that you do not ever want to see again

Imagine you are browsing 'All' and run across:
c/spezrulez

Clearly you never want to see posts from here ever again browsing all or not.

Add to Blocklist.  Profit.
Nice if this was tracked across apps/web, but of course that would require (I expect) to Lemmy server code as well.

**Comment by rsammelson** [comment]
Is this a duplicate of #40?

**Comment by josefwells** [comment]
Yes, thank you, looks like it.  Nice that it is already in Lemmy.
