### ISSUE TITLE
Sharing posts from a feed shares the images/links, not the post itself

### ISSUE THREAD

**Issue by JCpac** [aeharding/voyager#255]
**Disclaimer:** I'm not sure if this is intended or not, since I haven't found any issues/discussions on this topic. The closest thing I could find was #202, which I'm not sure if it solves the matter at hand.

**Wefwef version:** 0.12.0 (installed on mobile)

### The Issue
When I use the **Share** button on a post containing an image/link from any feed - whether it's from a specific community's feed or from the Home/All/Local feeds - the shared URL corresponds to the image/link contained in the post, _not_ the post itself.
When I use the **Share** button on a post with no links or from an individual post's page (with or without images/links), the shared URL corresponds to the post itself, as I would expect.
~I made a video showing the different URLs being generated upon sharing a post with an image, followed by a post with only text - both from my Home feed:~
I *was* going to upload the video, but, for some reason, it's completely black when viewed in Github's preview...
To reproduce, you just have to go to any feed and open the sharing menu on:
- Text posts - which will share the post's URL
- Posts with images/links - which will instead share *their* URLs.

This doesn't happen on an individual post's page, where it always shares the post's URL, regardless of any existing images/links.

https://github.com/aeharding/wefwef/assets/61757466/b28a0fff-d1da-4081-b333-a776d40c7bc8

Since sharing the post itself consequentely grants access to the image/link, it seems to me that this action is more useful than sharing whatever link is contained in the post. Especially since it's possible to share the images/links by tap-holding them, whereas that doesn't seem to be an option for the post itself.

### Possible Solution
I've been looking through the code and eventually found [this line](https://github.com/aeharding/wefwef/blob/6b4758de8d1f252f383950693a3385e91309a5fa/src/features/post/shared/MoreActions.tsx#L196C22-L196C22) that I suspect could be the problem (or, at least, closely related to it). I've noticed from Chrome's network inspector that the `post` objects in the response of a simple text post don't contain a `url` property, so the code on the mentioned line is then relying on the `post.post.ap_id` property (which contains the post's URL), instead of `post.post.url` (which only exists when there is an image/link in the post). I believe sharing the `post.post.ap_id` everytime should be the correct fix, if this issue turns out to be relevant.

![screenshot showing lack of URL property on a post object from a text post](https://github.com/aeharding/wefwef/assets/61757466/301561be-28d9-4ca7-b5e7-2f3a62750009)

 Regardless, since this is the first time I've looked at this app's code and since I've never dabbled in React - let alone React on mobile - it would be better if I let someone else tackle this.

**Comment by rsammelson** [comment]
See #202

**Comment by JCpac** [comment]
Yes, I saw that PR. If it's intentional, then nothing I can do about it.

But is there some explanation? Maybe some discussion/issue/PR I didn't find?
It just seems to me like sharing the post itself makes more sense overall...

**Comment by rsammelson** [comment]
In the share code (I think original code from @aeharding), it returns the media/link url unless it is null, otherwise it returns the post url. I would say it's a matter of preference which people want to share, it might also depend on whether the recipient uses Lemmy.

**Comment by JCpac** [comment]
So, it's just been like this from the start. Then, I'm assuming I should leave this issue open until @aeharding states otherwise, right?

> I would say it's a matter of preference which people want to share, it might also depend on whether the recipient uses Lemmy

I like the idea of giving the option to share either the post or the included image/link. Could it maybe be possible to add a modal for that?

**Comment by rsammelson** [comment]
That's what my PR does

**Comment by JCpac** [comment]
I see. I didn't realize it did that already. Thanks, I appreciate it! 👍

**Comment by rsammelson** [comment]
I would leave this open until that is merged.

**Comment by brandonegbert** [comment]
I had actually assumed this behavior was a bug. I want to share a link to the comments on the instant I'm reading on. I share a lot of threads with my wife this way.

**Comment by aeharding** [comment]
Apollo seems to share the thread always. I think it's a reasonable expectation to the user that the same thing is consistently shared.
