### ISSUE TITLE
Implement comment sorting and text formatting options

### ISSUE THREAD

**Issue by AlphaPro06** [aeharding/voyager#27]
Lemmy has the following comment sorting and text formatting options in their native web UI app
![Screenshot 2023-06-26 at 2 12 18 PM](https://github.com/aeharding/wefwef/assets/41750392/48aa3551-fe8c-4feb-8365-fa765e65c30c)

It'd be awesome if this was implemented and Apollo had the comment sorting in the following screenshots and it'd be easier if it was implemented that way 

![IMG_2931](https://github.com/aeharding/wefwef/assets/41750392/4d9f15e1-707e-4085-9461-01b364dbcc65)
![IMG_2930](https://github.com/aeharding/wefwef/assets/41750392/132b08ab-065f-46ad-a55c-a6b14852f309)

**Comment by aeharding** [comment]
I'm going to close this - comment sorting is done and comment formatting is in #367
