### ISSUE TITLE
edit posts 

### ISSUE THREAD

**Issue by TalOrenshtein** [aeharding/voyager#279]
Is there a plan to add edit posts feature? Even if it's just adding an option from outside the post (e.g, from your profile -> post's 3 dots menu) like Jerboa.

**Comment by farline99** [comment]
Yes, we definitely should be able to edit what we posted. Important basic feature.

**Comment by aeharding** [comment]
Working on this now

**Comment by farline99** [comment]
❤️❤️❤️
