### ISSUE TITLE
Unable to login to lemmy.world

### ISSUE THREAD

**Issue by rokejulianlockhart** [aeharding/voyager#280]
I can login directly via lemmy.world.

**Comment by Daneish** [comment]
Hi there, Lemmy.world is currently having [technical issues](https://lemmy.world/post/1035095) so things may not work as expected.

Having said that I used logged into Wefwef with my Lemmy.world account successfully. You could try to force quit your wefwef app or browser and try again.

If it is still not working, please provide more information on the errors that you get, and some information on your device (OS version, browser, if wefwef is installed as an app or is running in your browser).

**Comment by rokejulianlockhart** [comment]
@Daneish,

> You could try to force quit your wefwef app or browser and try again.

What do you mean by “force kill”? `SIGKILL`?

> please provide more information on the errors that you get

What logs do you want?

> OS version

```log
PS /home/rokejulianlockhart> uname -a
Linux RQN6C6 6.3.9-1-default #1 SMP PREEMPT_DYNAMIC Thu Jun 22 03:53:43 UTC 2023 (0df701d) x86_64 x86_64 x86_64 GNU/Linux
PS /home/rokejulianlockhart>
```

> browser

https://software.opensuse.org/package/MozillaFirefox

```log
PS /home/rokejulianlockhart> zypper info MozillaFirefox

Information for package MozillaFirefox:
---------------------------------------
Repository     : Main Repository (OSS)
Name           : MozillaFirefox
Version        : 114.0.2-1.1
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 231.5 MiB
Installed      : Yes
Status         : up-to-date
Source package : MozillaFirefox-114.0.2-1.1.src
Upstream URL   : http://www.mozilla.org/
Summary        : Mozilla Firefox Web Browser

PS /home/rokejulianlockhart>
```

> [whether] wefwef is installed as an app or is running in your browser

I've only tested in the aforementioned browser.

**Comment by Daneish** [comment]
Thanks for providing the additional information and for your patience.

> What do you mean by “force kill”? `SIGKILL`?

I was referring to closing the PWA / browser and ensuring it wasn't still running in the background.

> What logs do you want?

No logs required at this stage. Just any error messages or behaviour that appears on screen when you attempt to login.

I don't currently have access to a Linux box, but I wasn't able to replicate any issues logging into Lemmy.world in Voyger/wefwef in Firefox on iPadOS or Windows.

Sorry for the simplistic suggestion, but to ensure it isn't related to cached data on your device, please clear Firefox's cache; then confirm if you are still having issues and the error message that you get.

**Comment by Daneish** [comment]
If issues are still occurring, some options to help isolate the issue are:
* ensuring that you're on the latest version of Voyager/wefwef (clearing browser cache should do that), but Settings > Check for Updates will confirm (at time of writing it is 0.19.0).
* confirming if you have 2FA turned on for your account, and if temporarily turning it off works around the issue.
* testing login to Voyager via another Lemmy instance.
* testing another web browser.

**Comment by theogravity** [comment]
I'm also having issues where after login, it doesn't keep myself logged in right after. 

I have tried the production app on the website from this repo with no luck. 

I did check that 2FA is not enabled on the account.

**Comment by ObserverObserved** [comment]
Hey, I am facing a similar issue, attempts to login generate error "Connection Error. Please try again". 
Also cannot login using lebeyondcombustionmmy.net

Issue has persisted since 0.19.

Can succesfully log in directly to instances. Changed passwords, tried different browsers. Downloaded new browser to r/o cache issues. Cannot log in using Voyager either in browser or PWA.

**Comment by ObserverObserved** [comment]
> Hey, I am facing a similar issue, attempts to login generate error "Connection Error. Please try again". Also cannot login using lemmy.beyondcombustion.net
> 
> Issue has persisted since 0.19.
> 
> Can succesfully log in directly to instances. Changed passwords, tried different browsers. Downloaded new browser to r/o cache issues. Cannot log in using Voyager either in browser or PWA.
> 
> EDIT am on Android 13

OK, prob not be a Voyager issue. Have now logged in successfully to BC, but not LW

**Comment by aeharding** [comment]
I'm pretty sure this isn't a voyager issue - so I'm going to close this. Feel free to create a Discussion to discuss further!

**Comment by ObserverObserved** [comment]
> I'm pretty sure this isn't a voyager issue - so I'm going to close this. Feel free to create a Discussion to discuss further!

Yep, agreed. Thanks!
