### ISSUE TITLE
Hide previous posts

### ISSUE THREAD

**Issue by AGuyNamedRakkun** [aeharding/voyager#285]
Boost really had this really nice feature that let you to hide previous posts (as a whole). I think having this option with addition to the current ability to hide the particular posts will be useful if there are too many posts that an user wants to hide.

**Comment by mdecourcy** [comment]
Duplicate: #136

**Comment by AGuyNamedRakkun** [comment]
latter, it doesn't have to be read posts but rather posts that were on the top of the post that we have choosen.

**Comment by aeharding** [comment]
I see a "hide read posts" button but not "hide above"

I'm playing around with Apollo right now. There's a feature to mark posts read you scrolled passed automatically and then you can tap a button to hide read. Maybe that's what you're thinking of?

Closing for now - feel free to comment on #136 or create a new issue with detailed screenshots.
