### ISSUE TITLE
Tapping an image near the bottom of the screen in Android scrolls the page

### ISSUE THREAD

**Issue by Takryn** [aeharding/voyager#287]
When tapping a NSFW image that is partially off screen (down feed), rather than unblurring, it scrolls halfway through the next post. All subsequent taps unblur/blur as expected and no longer scroll, even if placed back in the original position on screen. 
![Screenshot_20230705-215122](https://github.com/aeharding/wefwef/assets/71604064/5e45b13c-8282-43aa-8ebe-df16b2c815c5)
![Screenshot_20230705-215132](https://github.com/aeharding/wefwef/assets/71604064/1ad354bd-a8d6-482f-894d-e84eecf0f0bc)

**Comment by aeharding** [comment]
Hi there, can you let me know if this happens on 0.15.0?

**Comment by Takryn** [comment]
Confirmed, still happening in 0.15.0 (also confirm on second tap it is
opening the image per the new handling, rather than unblurring in place)

**Comment by sasuryynala** [comment]
This is happening with all images so it probably doesn't have anything to do with the blur.

**Comment by aeharding** [comment]
I can reproduce in Android when I tap any image near the bottom third-ish of the screen

**Comment by mrnetops** [comment]
I am experiencing this on an android tablet and it doesn't seem to be nfsw specific, but all images.


first image long press will jump up about 1/2 a screen and then resolve, which means I usually get the share/etc menu for the following image

(love the app btw!)

**Comment by aeharding** [comment]
Investigated and created Ionic bug report: https://github.com/ionic-team/ionic-framework/issues/27888

**Comment by aeharding** [comment]
Should be resolved in the next release with a patched ionic build I made :)
