### ISSUE TITLE
Close image viewer upon tapping the backdrop/overlay

### ISSUE THREAD

**Issue by beeb** [aeharding/voyager#291]
At the moment, closing the image viewer implies swiping up or down on the open image, or tapping the small close icon in the top right. I suggest adding a handler for tapping the overlay around the image to close the viewer. This is common practice for modal elements and there is often a large enough area around the image to conveniently do so.

Thanks!

**Comment by beeb** [comment]
Interestingly, this already works on desktop but not on mobile. On mobile, a tap will hide the UI elements. I realize this is also a desired behavior (hiding UI can be nice to show a picture to someone), so I'm not sure what should be done about it.

**Comment by aeharding** [comment]
On mobile swiping will close - I just checked Apollo and tapping black background doesn't dismiss, but toggles the UI action elements. I think that's the route we should go so I'm going to close this issue :)
