### ISSUE TITLE
Stutters while scrolling and swiping a comment at the same time

### ISSUE THREAD

**Issue by 23492** [aeharding/voyager#295]
When scrolling vertically through comments and swiping horizontally at the same time, the horizontal motion of the comment stutters. 

https://github.com/aeharding/wefwef/assets/51166766/36bf338b-d0f4-4a4d-a46e-76741f6a5c36

Phone: S23 Ultra, running One UI 5.1

**Comment by aeharding** [comment]
Can you please try Chrome instead of samsung internet?
