### ISSUE TITLE
Clicking a blurred NSFW image should unblur it - not open it full screen.

### ISSUE THREAD

**Issue by bdonvr** [aeharding/voyager#296]
With the latest update it makes it much less convenient to browse the feed - I have to tap on each blurred image and then dismiss it. Previously I would just tap on them to quickly glance and see if it was something I wanted to look into further.

**Comment by aeharding** [comment]
Hi there!

Thanks for the request. You should still be able to "hide" just as fast by swiping up or down. It's now a swipe rather than a tap. Let me know if that works for you.

**Comment by bdonvr** [comment]
> Hi there!
> 
> 
> 
> Thanks for the request. You should still be able to "hide" just as fast by swiping up or down. It's now a swipe rather than a tap. Let me know if that works for you.

Ah, that's probably fine. Just gotta retune my muscle memory. Just a preference thing.

**Comment by robertafreese** [comment]
I think this is Apollo Parity perhaps? Can't test this, but ISTR this.

**Comment by aeharding** [comment]
I just checked Apollo, and tapping a blurred image opens the gallery component like Voyager does. So I'm closing this since it's consistent. :)
