### ISSUE TITLE
[Could not reproduce] Top off screen blank

### ISSUE THREAD

**Issue by PawanHegde** [aeharding/voyager#298]
![image](https://github.com/aeharding/wefwef/assets/3167291/15ffaaed-c175-4972-b97c-8eb381f8e6bd)

iPhone 12
iOS 16.5.1
Wefwef 0.15.0

I only faced this once and was not able to reproduce it after i restarted the app. This issue is just FYI. 

I was doing something with switching accounts and reading messages. I don't know what triggered it.

The top part of the screen was blank like you see in the screenshot. It looked like wefwef was leaving margin for a non-existent navigation bar. The empty space perfectly matched the height of the navigation bar in default apps.

**Comment by aeharding** [comment]
Thanks for the issue! I can't repro, so I'm closing for now.
