### ISSUE TITLE
Unable to comment on certain communities: "Please select a language in your lemmy profile settings"

### ISSUE THREAD

**Issue by xeger** [aeharding/voyager#299]
Whenever I try to post a comment on topics at `lemmy.blahaj.zone`, I receive an error toast as follows:

![image](https://github.com/aeharding/wefwef/assets/73368/d4b5c5ad-7744-4e01-bbb9-3181e46a3a8a)

This doesn't happen if I use the native Lemmy UI. I notice that UI has a language selector which is "Undetermined" by default and can be changed to English. If I choose English, then my comments succeed with the native UI. If I leave the language as "undetermined" then, even with the native UI, they fail with a different, less useful error (the comment appears to be saving forever). Nevertheless, the native UI has a workaround by virtue of letting me choose the language.

I have some React development skills. I'm not sure of the best way to incorporate language tagging into wefwef, but happy to take a stab at it if anyone's got an idea on how to proceed. The MVP would be to copy Lemmy's native UI, expose a selector, and include language information in whatever request we're making to the server. There might be more enlightened options, however, such as detecting language via a [basic language model](https://github.com/rse/fasttext-lid) or using hints provided by the browser's `Intl` bindings.

**Comment by eat-your-glory** [comment]
I feel like the Lemmy solution is the best one. How, and where could it be implemented?

**Comment by rattboi** [comment]
I'm running into this when trying to post to lemmy.world on the regular. Hope this can be solved soon.

**Comment by holotape** [comment]
I have this same issue on sffpc@lemmy.world

**Comment by aeharding** [comment]
This is a bug in Lemmy that needs to be fixed.

**Comment by eth-p** [comment]
I found that going through my instance's website with `lemmy-ui`, I could specify a language for a comment when writing it. Doing that allowed the comment to post correctly.

Maybe Voyager could add the ability to select the language for posts/comments somewhere in the dialog where you write them? There could even be a general app setting where you set your default language, and it automatically selects that language for you on new comments or posts.

Having that as a feature would also be pretty useful for multilingual users, too.

**Comment by aeharding** [comment]
This may be fixed by https://github.com/LemmyNet/lemmy/pull/3672, so hopefully we don't have to resort to hacks :)

> Maybe Voyager could add the ability to select the language for posts/comments somewhere in the dialog where you write them? There could even be a general app setting where you set your default language, and it automatically selects that language for you on new comments or posts.

Maybe, but that is out of scope for this issue.

**Comment by aeharding** [comment]
Can anyone following this issue confirm if they've seen this issue recently? I believe the latest release of Lemmy resolved it, and I haven't seen it recently.

**Comment by holotape** [comment]
I have not had the issue in a while.

**Comment by aeharding** [comment]
Thanks! I'm going to close it then.
