### ISSUE TITLE
Long press post/comment to bring up action sheet

### ISSUE THREAD

**Issue by jazir555** [aeharding/voyager#303]
Boost had a great feature for hiding posts by long clicking on it and having a pop-up menu with the option, it would be fantastic if you could add that to Wefwef

**Comment by rsammelson** [comment]
You can do this by long swiping to the left.

**Comment by jazir5** [comment]
Would it be possible to add it to a long hold menu on the comment as well? I would appreciate it, I don't use swipe actions at all aside from left swiping on the post to exit.

That's actually another request I have actually, would it be possible to disable to left swipe action on comments entirely so I could back out of the post? As it is now, I can only exit the post with left swipe if I scroll to top and don't swipe on a comment, which negates the usefulness of the left swipe to exit.

**Comment by rsammelson** [comment]
That may be added by the customize swipe options issue, but you can swipe to exit if you start all the way on the left very close to the edge of the screen.

**Comment by aeharding** [comment]
I think we can add long tap to bring up the menu. Apollo did something similar, although they had the "snippet focus" feature or whatever.

It would also be cool if right click triggered this on desktop.

**Comment by aeharding** [comment]
This is now resolved!

**Comment by jazir555** [comment]
Great, thank you!
