### ISSUE TITLE
Scrolling community quick switcher refreshes posts

### ISSUE THREAD

**Issue by sasuryynala** [aeharding/voyager#324]
https://github.com/aeharding/wefwef/assets/32301466/e8a99b30-fc19-4f58-b837-c488211331db

**Comment by aeharding** [comment]
What browser and version? I can't reproduce this with iOS

**Comment by sasuryynala** [comment]
I'm on Android and using Chrome 114.

**Comment by aeharding** [comment]
This should be resolved now :)
