### ISSUE TITLE
Option to turn off infinite scrolling

### ISSUE THREAD

**Issue by DoriNori7** [aeharding/voyager#334]
This was one of my favorite features of Apollo. Instead of scrolling forever, posts would stop after a certain number, similar to how the reddit website works on mobile. It makes it much easier to avoid getting stuck scrolling for hours at a time.

**Comment by KimNorgaard** [comment]
I also miss this option. I am fighting hard against my reptile brain and next to shorts/reels/etc infinite scrolling is one of the worst dark patterns to keep users in a platform. Seeing there is no financial incentive on Lemmy there should be no reason to try to keep users scrolling.
