### ISSUE TITLE
Communities List Should Have the Ability to Favorite by Tapping a Star

### ISSUE THREAD

**Issue by Corb3t** [aeharding/voyager#348]
Loving all the work that has gone into Voyager! Is there any way you could add the option to favorite communities from the Posts > Communities area by tapping a Star, similar to Apollo?

I’ve mocked up what it would look like. ![image](https://github.com/aeharding/wefwef/assets/43692728/782805c9-ad2d-4c84-b451-e8b2d1c5f80c)

**Comment by aeharding** [comment]
Definitely!

**Comment by rsammelson** [comment]
I'm going to work on this
