### ISSUE TITLE
[Feature request] Improve subreddit migration with this sheet of official migrations

### ISSUE THREAD

**Issue by juliloving** [aeharding/voyager#350]
Many subreddits have officially migrated to Lemmy communities, and it has been recorded [here](https://www.quippd.com/writing/2023/06/15/unofficial-subreddit-migration-list-lemmy-kbin-etc.html)

Is it possible to fetch this data while using the "Migrate subreddits" feature to automatically switch over the ones that do have official alternatives?

**Comment by aeharding** [comment]
I don't see why not, assuming there is a well formatted list/API we can pull from.

**Comment by aeharding** [comment]
A CSV or JSON would be best. However I'm curious if maybe there already exists a list on the web? I've seen a good number of reddit -> lemmy community tracker sites :)

**Comment by KairuByte** [comment]
Some of those migrations seem dubious. The one that sticks out the most is r/selfhosted and the listed discourse forum, where there have been a total of 23 posts in the past 27 days. Meanwhile there *is* an active community on lemmy (though I can’t currently connect to verify the name.)

**Comment by aeharding** [comment]
That's a ok list, but I don't think it's something that would be worth the effort to code into Voyager.

That being said, it would be a cool standalone app to help people migrate. :)

I'm closing this ticket as out of scope. Thanks!
