### ISSUE TITLE
Bug: iOS spelling suggestion stays open

### ISSUE THREAD

**Issue by rsammelson** [aeharding/voyager#361]
After writing a comment and submitting it, I had this float stay on the screen:
![image](https://github.com/aeharding/voyager/assets/20521763/3ae1c7b2-0676-4cba-b41a-4b1ca89c5df3)

**Comment by aeharding** [comment]
Unfortunately I'm not sure if there is any way we can solve this, because it is an iOS bug. Hopefully Apple fixes 🤞
