### ISSUE TITLE
Option to reflow text to fill page width in landscape orientation. 

### ISSUE THREAD

**Issue by Polyfun** [aeharding/voyager#364]
When using an IPad in landscape orientation, there is a lot of unused white space in the left and right page margins; some people would prefer to make the most of this space by adding a reflow option.

**Comment by aeharding** [comment]
Thanks. Was this an option in apollo? It could be added as an option but it would add extra code to maintain it.

**Comment by Polyfun** [comment]
I don’t remember if it was an option in Apollo. Memmy does it by default. Web pages generally are responsive and reflow to fit the device.

**Comment by aeharding** [comment]
Closing this in favor of #735
