### ISSUE TITLE
Export/import settings to facilitate new installation

### ISSUE THREAD

**Issue by IonicRain** [aeharding/voyager#366]
If the app needs to be removed and installed again or if the app is used on a new device, a user might want to restore the settings of the original installation. For example the appearance setting such as post size or light/dark mode.

If such settings can be exported and imported, it's easier for users to install the app again and restore their preferences.

**Comment by gobbledygoober** [comment]
I reinstalled for the app rename and icon change and came here to see if an issue like this was logged. Thanks @IonicRain!

**Comment by erikpendragon** [comment]
Import/Export the filter list would be amazing
