### ISSUE TITLE
Show toolbar with markdown options to format text

### ISSUE THREAD

**Issue by IonicRain** [aeharding/voyager#367]
When composing an OP or comment, users can insert markdown to format their text. This is similar to the options presented on GitHub.

For example, a text can be set to italics by adding `*asterisks*` symbols, but mosts users probably are unaware they can format text that way.

It would probably help users if a toolbar is visible when writing an OP or comment from which can be chosen to edit text. Specifically if a user wants to add a hyperlink coupled to a word or (part of) a sentence.

**Comment by aeharding** [comment]
Ideally, it would be nice to implement this the way that apollo did. That is, Apollo formatted the markdown code inline. It's hard to explain, so screenshot:

![IMG_3083](https://github.com/aeharding/voyager/assets/2166114/0f1f3485-d51f-49da-b1f1-a52489928410)

I'm not sure if anything like this exists in a prebuilt library we can consume, so tagging this as research.

**Comment by aeharding** [comment]
https://github.com/sparksuite/simplemde-markdown-editor seems like a good candidate
