### ISSUE TITLE
Bug: exiting web view on Android causes bottom bar to briefly freak out

### ISSUE THREAD

**Issue by aperson** [aeharding/voyager#371]
Sorry I didn't enable showing my taps, but you can see that when exiting a WebView, the bottom bar freaks out:

https://youtu.be/oi-p4P1_8zk

Edit:

It even did it when I exited out from following this GitHub's link in-app.

**Comment by mdecourcy** [comment]
Do you have your default system webview changed, or are you on default webview?

I'm on Android 13 with vanadium as my default webview, and haven't experienced this behavior

**Comment by aperson** [comment]
Default.  I am on stock android 13 on a pixel 7 pro.

**Comment by mdecourcy** [comment]
Just noticed it, using chromium on android 13.

Has this always been an issue for you, or was this behavior only apparent after a recent release @aperson

**Comment by aperson** [comment]
Only just noticed it when updating to 0.18.3.

**Comment by aeharding** [comment]
I would appreciate anyone that can take the time to checkout 0.18.0 (or whatnot) and verify if this is indeed a regression

**Comment by mdecourcy** [comment]
https://youtube.com/shorts/Qc3RjM7MbM4?feature=share

**Comment by aeharding** [comment]
It looks like some glitching of the footer did happen at the end there?

**Comment by mdecourcy** [comment]
Yeah, last two look slightly buggy. I honestly didn't notice it until this issue was submitted.

**Comment by aeharding** [comment]
I'm going to close this because I believe it is a browser bug

**Comment by mdecourcy** [comment]
@aeharding I agree, bug isn't there on FF mobile.
