### ISSUE TITLE
Bug: A single word with many characters in the title of a post pushes the upvotes / downvote buttons off screen

### ISSUE THREAD

**Issue by ryblogs** [aeharding/voyager#376]
A long, single word with no spaces in a post's title pushes the upvotes/downvote buttons off screen.

See example below from !boston@lemmy.world:
![Screenshot_20230710-232452](https://github.com/aeharding/voyager/assets/15970250/48dc5c5a-50a9-4ed0-8ef1-f49288a30333)

**Comment by Daneish** [comment]
I can replicate this issue when using Compact post size on a small screen device (iPhone 11 Pro, iOS 16.5.1, Voyager PWA 0.19.0).

Using Large post size it renders correctly, as it does in either post size on a larger screen device like an iPad or laptop.
