### ISSUE TITLE
Ellipse menu closes unexpectedly when trying to preform a second task

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#380]
If you click on the ellipse menu and preform a task suck as “Subscribe” and then open the menu again before the toaster notification disappears you are unable to open the menu again without it closing/hiding.

To replicate:
1) open a ~~channel (sublemmy?)~~ community 
2) click the ellipse menu
3) subscribe/unsubscribe to the ~~channel~~ community 
4) click the ellipse menu
5) watch in sadness as it closes before you can click something else

Only way I’ve managed to work around this is to press the back button or force close the app.

Included is a video of the issue.
https://github.com/aeharding/voyager/assets/723314/f31202e4-5494-48b8-8ce1-11e011bd3e8c

Edit:

Running:
iOS 17 Developer Beta 2

Device:
iPhone 13

Voyager version:
0.19.0

**Comment by Daneish** [comment]
I'm able to replicate this issue intermittently on iOS/iPadOS, but not Windows.

For me to replicate it I had to tap the ellipse a second time while the Subscribe toast was still rising. If I didn't get it at quite the right time and the toast had already risen I wouldn't have the issues. This is a little bit different to kerosyn's description, but it's also hard to tell exactly when they were tapping in the video.

Has issues:
iPhone 11 Pro, iOS 16.5.1, Safari, Voyager 0.19.0 installed, lemm.ee
iPad Pro 2018, iPadOS 16.5.1, Safari, Voyager 0.19.0 installed, lemm.ee

No issues:
Dell XPS 13, Windows 11, Edge, Voyager 0.19.0 installed, lemm.ee

Voyager devs please let me know if this issue replication is not useful. :)

**Comment by aeharding** [comment]
Thanks for the report. This should be solved by #392, but let me know if its not.

**Comment by kerosyn** [comment]
Updated to 0.20.0 and still seem to be having the exact same issue. Had to create a new account not on lemmy.world to confirm.

**Comment by aeharding** [comment]
It didn't make it to 0.20.0 so check the next release when it comes out :)

**Comment by kerosyn** [comment]
Still seems to be happening in 0.21.0. Including a screen recording.

https://github.com/aeharding/voyager/assets/723314/df7ba4f1-b5f6-4076-8cd1-4721c9a83c9f

**Comment by kerosyn** [comment]
It seems like it might be affected any menus. Tested with the Sort By menu, Post menus, and Comment menus.

Video included.
https://github.com/aeharding/voyager/assets/723314/74682a4f-db60-4765-8780-233e2e298a2a

After each test seen in the video I’m clicking the < Back/Communities button. Doing so bring up the menu animation and then it disappears. That seems to reset the menus so they work again.

**Comment by kerosyn** [comment]
The issue is also present in Settings for any option that bring up a menu.

https://github.com/aeharding/voyager/assets/723314/6a28abaa-a630-42e2-853d-81b3447fd26d

**Comment by aeharding** [comment]
@kerosyn can you enable recording touches I can see what you're pressing, and/or use a camera to take a video of a real device?

**Comment by kerosyn** [comment]
> @kerosyn can you enable recording touches I can see what you're pressing, and/or use a camera to take a video of a real device?

As requested. Used this [guide](https://support.screenpal.com/portal/en/kb/articles/show-finger-taps-when-recording-your-screen-on-ios) to enable recording taps.

https://github.com/aeharding/voyager/assets/723314/708ef2f0-39a9-40f3-9e48-aa53885a5036

Let me know if you need anything else.

**Comment by kerosyn** [comment]
Also happening in the new Gestures settings on 0.28.0.

**Comment by kerosyn** [comment]
Just tried this on both the iOS beta and the PWA, both latest version 1.0.1.

It doesn’t appear to be happening on the main view, but still happening in posts and settings. I don’t know if I tested it before on the main view.

Here is a video with the main view working as excepted but the bug still happening in a post.

https://github.com/aeharding/voyager/assets/723314/fa238202-77a0-4518-bff8-448572a2a942

**Comment by kerosyn** [comment]
On the latest version of iOS 17 beta 4 this seems to have been resolved. Been testing for the last day or 2. 

Closing for now.

**Comment by aeharding** [comment]
Great!
