### ISSUE TITLE
Old account identifier 👵👴

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#381]
Related to #17

I think it would be fun to have the option of identifying older accounts. And by old, I mean pre-dating the Reddit drama that caused the influx of new Lemmy users. Whether that was the date the api changes were announced, the 3pa last day, or the start of the new api policy.

It would just be fun way to see veterans of the platform at a glance.

**Comment by aeharding** [comment]
Haha. That's a fun idea. It does have the idea to be gamed though.

**Comment by kerosyn** [comment]
> Haha. That's a fun idea. It does have the potential to be gamed though.

It’s your call as it’s your project, but outside of the bot accounts that many of which were deleted, I don’t see how it can be gamed. Also only Voyager users will see it unless other clients implement it.

The idea was inspired by the game series Battlefield’s old veteran status of owners of the older games.

**Comment by aeharding** [comment]
I believe you can technically set your account age to anything if you have access to the instance DB.

But again, I think the possibility of people gaming this is fairly low :)

**Comment by aeharding** [comment]
I've thought about this more, and my main concern is that users may not want their account tagged with this badge. Unlike the new account badge, where if you wait long enough it'll go away, this badge does not.

For that reason I don't think I am going to implement this.

That being said, I am absolutely open to badges in general and thank you for bringing this idea up!!
