### ISSUE TITLE
[Feature Request] Button to jump to next top-level comment

### ISSUE THREAD

**Issue by tibuntu** [aeharding/voyager#384]
In Apollo there was a button to jump to the very next top-level comment. I personally found that very useful, especially in posts with a lot of comments. Additionally one could configure if the button was on the left, middle or right side of the screen. The button was basically in front of the actual comments. Unfortunately I do not have a screenshot of it.

**Comment by tibuntu** [comment]
Found a random google result where the button can be seen

https://images.app.goo.gl/9rztDAMjoNX3ox2c8

**Comment by aeharding** [comment]
Yeah, thanks for the request. I was planning on working on this.

**Comment by Hikiru** [comment]
Is this still happening?

**Comment by aeharding** [comment]
Yes, that is why there is a ticket :)
