### ISSUE TITLE
Allow proxy overide or default behavior to not proxy

### ISSUE THREAD

**Issue by Barusu-rem** [aeharding/voyager#387]
Hi I noticed Voyager seems to have a hardcoded list of instances that are unproxied. I was wondering if its possible to change the default behavior to not proxy instances (or add an option to allow disabling proxying). I use lemmy.fmhy.ml I noticed since it wasn't in the list it was being proxied.

https://github.com/aeharding/voyager/blob/53cb0d25e4853701063897638d2093f0836c8c85/src/services/lemmy.ts#L14

**Comment by rsammelson** [comment]
At some point soon I think we will be able to assume everyone has updated and stop proxying altogether. Because of that I'm not sure effort will be put in to something like this.
