### ISSUE TITLE
[Feature request] Multireddit support

### ISSUE THREAD

**Issue by achin** [aeharding/voyager#397]
In Reddit and in some of its clients, you can specify two or more subreddits to view posts from all of them simultaneously, interleaved, as if they were a single subreddit. 

This would be an amazing feature to have with Lemmy clients, since it would help consolidate similar communities across different Lemmy instances.

**Comment by aeharding** [comment]
This needs lemmy support - https://github.com/LemmyNet/lemmy/issues/818

**Comment by aeharding** [comment]
Closing until that is resolved ^
