### ISSUE TITLE
Firefox for Android fails to load Manifest icons

### ISSUE THREAD

**Issue by TitanNano** [aeharding/voyager#399]
Firefox for android fails to load the icons specified in the `mainfest.json` this causes users to end up with the fallback icon in their launcher.

I didn't find the time to figure out why exactly the load fails, but I noticed that on both mobile and desktop, the service worker intercepts the top-level requests (i.e. paste `https://wefwef.app/logo_minified.svg` in the URL bar) to all logo files and serves the app shell instead.

**Comment by TitanNano** [comment]
Further investigation indicates that Firefox fails at TLS negotiation with the server.

**Comment by TitanNano** [comment]
This [report shows](https://www.ssllabs.com/ssltest/analyze.html?d=wefwef.app) that the server only supports TLS 1.3 and older browsers are failing to connect to it with a similar error. Most likely, Firefox for android is (probably) using TLS 1.2 for some of the requests and that fails.

**Comment by aeharding** [comment]
Ah - thanks for the investigation of the issue!

Closing this as I don't want to support TLS 1.2 for dhparam reasons
