### ISSUE TITLE
Mark deleted/removed posts more clearly

### ISSUE THREAD

**Issue by kerosyn** [aeharding/voyager#400]
If a post is deleted, it should be more clearly marked that cannot be faked using markdown.

Currently if a user deletes their own comment it just says _deleted by creator_ in italics. That can be faked by someone easily to make it appear as they deleted their comment when it was in fact their comment. The same applies to removed comments.

My suggestion is to add an icon and/or change the colour of the text to something unique to it being deleted/removed.

Apollo did this for removed posts/threads, although removed posts was a bit more subtle compared to threads. I do not remember how it handed user deleted posts though.

![image](https://github.com/aeharding/voyager/assets/723314/52962c6f-9419-4989-9328-acdc21139939)

**Comment by aeharding** [comment]
Lemmy surfaces username of deleted post which is why the UI still shows that. But I agree, it would be nice to make it a different color at least to differentiate.
