### ISSUE TITLE
[Feature Request] Add visual hint to thumbnail type in the feed

### ISSUE THREAD

**Issue by GitBarns** [aeharding/voyager#408]
Currently, in the compact feed there is no indication whether a thumbnail is of an image (which will open in the app) or a preview of a link which will open in a new browser window. In some reddit apps there was such an indication which made browsing a lot simpler and predictable - you knew if clicking a thumbnail would open an image, a gallery, a youtube video, or an external link.

For example, below there is no distinction between the thumbnails, but two would open an image viewer, while one will open an external browser window
![no difference between thumbnails](https://github.com/aeharding/voyager/assets/136652942/527a2503-9ff3-4cdd-8b33-35fc6b25c9db)

Compared to this Boost for Reddit screen shot where you can see the small transparent triangles on every thumbnail, indicating their nature, and what would happen when I click on them 

![unnamed](https://github.com/aeharding/voyager/assets/136652942/cb5753e4-16ef-4738-ad33-6a6596ef11ff)

I'd love to see this in Voyager!

**Comment by GitBarns** [comment]
I just realized that Lemmy web actually already does this, note the small marks on the top right corner of the thumbnails 

![Screenshot_20230712_104612_Chrome](https://github.com/aeharding/voyager/assets/136652942/1969363f-0922-4fba-9c70-3ff52ca814e9)

**Comment by aeharding** [comment]
Are you up to date? There should be an indicator

**Comment by Untitled-Pribor** [comment]
Links are actually distinguished from thumbnails, they have a very faint globe icon in the bottom right corner of the preview 
![7AD2E058-7839-4A58-8872-4CA26AC6E7BB](https://github.com/aeharding/voyager/assets/111266268/dc74be4b-b148-4b1d-acb3-15da3f4150a1)

**Comment by aeharding** [comment]
The style should probably be improved

**Comment by GitBarns** [comment]
oh man, there's no way I could have noticed that and I checked it before submitting... it's so faint compared to the reddit apps and the lemmy ui.. definitely needs something a bit more visible 👍

**Comment by Untitled-Pribor** [comment]
I agree, it should be more like Apollo where it's very visible 
![9B8881DE-E456-48F6-9870-75403E889DCA](https://github.com/aeharding/voyager/assets/111266268/92e86653-5770-42fb-8103-764ec15d7bbc)
