### ISSUE TITLE
Suggestion: Remove voting from post actions menu

### ISSUE THREAD

**Issue by rsammelson** [aeharding/voyager#417]
I understand leaving reply and hide despite having swipe actions, because some people may prefer buttons. But the voting buttons, so far as I can tell, appear anywhere a post is shown. It was mentioned in #224 that the menu is getting overcrowded, which I agree with, so removing these two buttons would be an easy way to make more space.

**Comment by aeharding** [comment]
In the future there will be options to remove the vote buttons from the feed like apollo.
