### ISSUE TITLE
Post/comment history not updating when switching users

### ISSUE THREAD

**Issue by rsammelson** [aeharding/voyager#420]
Sometimes when I switch users the comment history below doesn't update until I manually refresh.

**Comment by aeharding** [comment]
Perhaps the API request was failing?

**Comment by rsammelson** [comment]
I just reproduced consistently in Firefox instead of on my phone, and the network inspector shows all 200.

**Comment by aeharding** [comment]
I haven't seen this recently, so I'm closing it. Please let me know if you see it again and I can reopen :)
