### ISSUE TITLE
Splash Screen Stretched

### ISSUE THREAD

**Issue by Daneish** [aeharding/voyager#421]
The Voyager splash screen is stretched when opening Voyager on iPad in landscape/horizontal orientation. Screenshots below.

In testing I found more edge cases where the stretching also occurs: opening Voyager in a split screen view, and when opening the app on iPhone in landscape orientation.

Opening the app in portrait orientation on both iPad and iPhone the splash screen appears correctly.

There was no splash screen displayed in Windows / Edge so issue was not effecting that platform.

Devices effected:
iPhone 11 Pro, iOS 16.5.1, Safari, Voyager 0.21.0 installed
iPad Pro 2018, iPadOS 16.5.1, Safari, Voyager 0.21.0 installed

Devices not effected:
Dell XPS 13, Windows 11, Edge, Voyager 0.21.0 installed

Thanks for an excellent app, loving all of your work! Please let me know if there is any additional information or testing I can provide.

Horizontal iPad (ignore the greying background, just related to the timing of the screenshot):
![IMG_0910](https://github.com/aeharding/voyager/assets/26273432/e2a3dd90-4590-46a3-92bc-11583addc043)

Horizontal iPad Split Screen 1:1 (with another app on the left) - slightly stretched:
![IMG_0916](https://github.com/aeharding/voyager/assets/26273432/1e00be9b-ab35-4d02-8763-def693869fae)

Horizontal iPad Split screen 2:1:
![IMG_0917](https://github.com/aeharding/voyager/assets/26273432/2f27968a-82c3-4b12-b9df-b3e01da901e3)

Horizontal iPhone:
![IMG_2114](https://github.com/aeharding/voyager/assets/26273432/bfa2da13-83b6-499d-85d3-493f4c81dbf0)

**Comment by aeharding** [comment]
I'm 99% sure that this is due to https://github.com/elegantapp/pwa-asset-generator/issues/93 unfortunately.

**Comment by Daneish** [comment]
Oof iOS 13! Apple really aren't looking after PWAs well enough.

I'm booting up my old iPad Air 1st Gen, which I think is running iOS 12. Will let you know when it has enough juice to turn on.

**Comment by aeharding** [comment]
Let me know, otherwise I'm going to close this for now since there's nothing we can do.

**Comment by Daneish** [comment]
Inconclusive, on iOS 12 the splash screen didn’t appear at all, but neither did any of the Lemmy content in the app. 

> close this for now
Fair call, makes sense.
