### ISSUE TITLE
Uploading an image in a post when the docker instance is down, fails

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#435]
Not sure if this functionality depends on the server that's hosting Voyager

I recently tried to run my own instance on localhost and I'm using it as a PWA

However when the docker image isn't running, other parts of the app like browsing, upvoting and commenting works

But when I try to submit a photo post, it fails to upload the photo until the docker instance is back up

Is there a way to get this working from the client directly?

**Comment by aeharding** [comment]
Hi thanks for the issue!

I would love to add this, but currently it is blocked by https://github.com/LemmyNet/lemmy/issues/3567. Until that is resolved, Voyager must proxy all requests for CORS reasons.
