### ISSUE TITLE
Unresponsive until App Switcher toggled

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#443]
Currently using 0.22.0 on iOS 16.5.1 and an iPhone Mini 13 on a lemmy.ee account. 

For the last week or so of Voyager updates, the UI has become completely unresponsive, usually while scrolling in my subscribed Posts feed, but I believe I've observed it in other parts of the UI. 

Bringing up the iOS App Switcher briefly and returning to Voyager immediately (i.e. without bringing a different app into focus) works around the issue every time. 

I'll admit I procrastinated reporting this because I assumed it was affecting other, more frequent users 😊, but I was surprised to not see any existing bugs here matching this description. Perhaps there is something I am taking for granted in my workflow. 

The pace of process on this project has been inspiring. Great work everyone!

**Comment by aeharding** [comment]
This is probably due to https://bugs.webkit.org/show_bug.cgi?id=222654

If you stop all interactions with the device for ~1-2seconds after it locks up the issue will be resolved. Please let me know if that solves your issue.

**Comment by gobbledygoober** [comment]
@aeharding: Yes waiting did resolve the issue. I saw your comment on bugzilla about how this gets reported frequently. Apologies for not checking the closed issues here. 

I understand it's a matter of preference, but would you consider leaving one of these open so other folks can find it easier, and to track when the upstream webkit issue is fixed? Maybe the first one that was reported?

Thanks again!
