### ISSUE TITLE
[Bug] “Show more” has negative number of comments

### ISSUE THREAD

**Issue by fayrose** [aeharding/voyager#455]
When browsing the following link, below the comment the button says “-6 more replies”. When clicked, nothing happens.  

Obviously it doesn’t make sense to expand a negative number of comments. 

Attaching links and screenshots. Currently running the 0.23 version. 

https://lemmy.world/comment/1325902

![IMG_4256](https://github.com/aeharding/voyager/assets/20001456/90750ac9-c2e8-460f-827a-521098ba482d)

**Comment by mdecourcy** [comment]
Voyager link to above post: https://vger.app/posts/lemmy.world/c/politics/comments/1549754

Presently unable to reproduce on Firefox on macOS

**Comment by aeharding** [comment]
Thanks for the report! I think its a transient lemmy issue. A brand new reply is made, and child_count from Lemmy isn't incremented yet but the child comment is returned. Luckily, there is an easy workaround :)
