### ISSUE TITLE
Setting for default inbox page

### ISSUE THREAD

**Issue by mfat** [aeharding/voyager#458]
See: https://github.com/aeharding/voyager/issues/458#issuecomment-1669146522

-------

I wish 3 taps on the inbox button in navigation bar, or a long press on it, would take me directly to "inbox (all)". 
Thanks for the amazing app.

**Comment by fer0n** [comment]
@aeharding wouldn't it make sense to have this behave the same as the profile and display the content of "inbox (all)" directly under the list items in "inbox"?

**Comment by aeharding** [comment]
@fer0n That's an option, however I have to say I like how clean the inbox page is :)

I don't see why we can't add a double tap or tap and hold to go to inbox (all) though, that should be pretty straightforward

**Comment by fer0n** [comment]
Maybe it's just me, but I'm almost exclusively using the "all" inbox and doing so quite frequently and it's always two tabs away.

**Comment by fer0n** [comment]
Someone also [suggested](https://lemmy.studio/comment/1025821) one timeline with different filters, but that would really give you the "everything is cleaned up" feeling.

**Comment by fer0n** [comment]
I think that's a great idea :)

**Comment by aeharding** [comment]
Thanks everyone for the discussion, especially @nightgolfer.

For the initial implementation, it will always open the "Inbox (all)" page when you tap the inbox tab.

In the future it could be customized, but I figure this is a good place to start!

**Comment by nightgolfer** [comment]
@aeharding just installed the update, it works perfectly! ❤️👌

Thank you very much for this, and the time you didn't on it! I'm sure it's a small thing in the Grand scheme of things, but a huge qol boost for me, at least, and I'm super happy to have it 😃🤘

**Comment by sallyFoster** [comment]
@aeharding Now this update is causing users like me who use the “unread” option more and who never use Inbox (all) to have to tap more to read messages that we want to see.

I propose to have a settings option such that each user can set their default inbox to whatever they want. 

https://github.com/aeharding/voyager/issues/1101
