### ISSUE TITLE
Phase out CORS proxy feature

### ISSUE THREAD

**Issue by Rihcus** [aeharding/voyager#459]
Most instances should be using BE: 0.18.1 fixing cors and making the proxy feature irrelevant.

https://github.com/aeharding/voyager/blob/30a31b71e6423f6249a96711be3128a87b9f7ebb/src/services/lemmy.ts#L4

**Comment by aeharding** [comment]
We're waiting on #3567

**Comment by Rihcus** [comment]
> We're waiting on [LemmyNet/lemmy#3567](https://github.com/LemmyNet/lemmy/issues/3567)

Out of curiosity for a temporary measure is it possible to use an external image uploading host instead (ex imgur or catbox.moe)?
