### ISSUE TITLE
Crossposts are not combined

### ISSUE THREAD

**Issue by kroese** [aeharding/voyager#462]
When a post is posted to multiple communities, it will show up multiple times in the feed (one time for each community).

It was better if those kind of posts were combined into a single post referencing multiple communities (like the official Lemmy UI does).

**Comment by aeharding** [comment]
If anyone could track down the code where lemmy-ui does this, that would be helpful

**Comment by mdecourcy** [comment]
@aeharding https://github.com/LemmyNet/lemmy-js-client/blob/2b757d39ec3e34fff952cc6ae2b61883f34b7d7e/src/types/GetPostResponse.ts#L6

looks like it's in GetPostResponse

**Comment by aeharding** [comment]
It might just list crossposts, I'd be surprised if lemmy-ui is deduplicating in the feed

**Comment by mdecourcy** [comment]
Yeah, after more digging it just seems to list them. Would need to be a server side function as well, otherwise comments would get duplicated or only show up on one post.
