### ISSUE TITLE
[feature request] block instance

### ISSUE THREAD

**Issue by rszyma** [aeharding/voyager#466]
Just like the options to block communities and users.

**Comment by mdecourcy** [comment]
Lemmy doesn't presently support users blocking of instances. See [lemmy#2397](https://github.com/LemmyNet/lemmy/issues/2397).

**Comment by aeharding** [comment]
Closing, this for now. We will implement as soon as implemented in lemmy!

**Comment by rszyma** [comment]
https://github.com/LemmyNet/lemmy/issues/2397 has been now closed as completed
