### ISSUE TITLE
Inconsistent font size between post list and post detail/comment

### ISSUE THREAD

**Issue by elpendor** [aeharding/voyager#481]
I think this is probably a little too specific or maybe it's just me but..

Is there any particular reason the text in the post detail (and the corresponding comments) is rendered smaller (code says 0.875em for both [these](https://github.com/aeharding/voyager/blob/main/src/features/post/detail/PostDetail.tsx#L76C14-L76C17) [elements](https://github.com/aeharding/voyager/blob/main/src/features/comment/Comment.tsx#L79C1-L80C1)).

Shouldn't these be valued as 1? Otherwise it seems like inconsistent behavior from what you expect from the post list versus what you're reading in the actual post.

An example with the lowest font scale:

![TQejpV2QPDa4c3j](https://github.com/aeharding/voyager/assets/2113610/15748fd0-869a-4b66-a186-36996bb9faea)

![1ikwfBEFed](https://github.com/aeharding/voyager/assets/2113610/eded2443-fd68-4afc-a098-3eb4e4a241bf)

Again, maybe it's just me but I often find myself setting an okay font size for the post list only to realize the content font inside is too small.

**Comment by maxpoulin64** [comment]
Just ran into this as well, it would be nice of they were customizable independently as well. Someone might want bigger fonts for one but not the other for the sake of reading comfort.

**Comment by elpendor** [comment]
> Just ran into this as well, it would be nice of they were customizable independently as well. Someone might want bigger fonts for one but not the other for the sake of reading comfort.

I thought about it but then I realized I might be a little overkill and rather go for simplicity and consistency.

But yeah, if it's something people might want I could implement it.

**Comment by aeharding** [comment]
Hi! This is a valid bug. I'm tweaking this so that comments and post title in compact mode always show as text size = 15px. It also now should have text sizes consistent with apollo.

Hopefully this solves the problem. I also found it annoying how the font size of comments was always a bit too small relative to the feed.

Please let me know if the next release resolves your problem (0.27.1 probably).
