### ISSUE TITLE
Multi community

### ISSUE THREAD

**Issue by trashhalo** [aeharding/voyager#482]
It would be amazing if I could create a multi-community. That is a community that gets posts from multiple Lemmy communities. The goal would be to pull content similar channels together talking about the same topics across different servers. 

I think you could implement this totally client side. Just pull the posts separately and then merge the lists.

Total crazy stretch goal not MVP:

If urls of posts were the same between two posts in a multi community you could merge their data together and make all the comments look like one big post.

**Comment by aeharding** [comment]
Hi thanks for the issue! I believe this is on Lemmy's radar, so I'd rather it be implemented on the backend first :) there's a bit too many edge cases for this to be implemented well client side
