### ISSUE TITLE
Mark Read on Scroll not adding to Hidden Posts

### ISSUE THREAD

**Issue by Daneish** [aeharding/voyager#483]
Posts that are hidden through an implicit action are not added to the Hidden Posts section of the profile. These implicit actions include Mark Read on Scroll, voting on a post, or clicking on a post/image/url. Only posts that are explicitly manually hidden via the Hide button/gesture, or the Hide Read Button are added.

This can be an issue where Show Read Posts is disabled on your Lemmy instance. Say you want to comment, but first want to check a source. You switch apps briefly, then when you return to Voyager and find the app has reloaded. The post is gone from your feed and also does not appear in Hidden Posts.

Due to limitations in Lemmy, the best work around seems to be to search for the post in a browser that is not logged in. Then log in via the browser to make the comment. If Voyager could save all hidden posts it would be much easier to return to your comment.

Test devices with issues:
iPhone 11 Pro, iOS 16.5.1,(c) Safari, Voyager 0.25.0 installed
iPad Pro 2018, iPadOS 16.5.1(c), Safari, Voyager 0.25.0 installed
Dell XPS 13, Windows 11, Edge, Voyager 0.25.0 installed

Thanks again for Voyager, I really appreciate all of your hard work making an awesome app! Please let me know if I can provide any more information or testing to assist further.

ETA: I am loving the scroll to read feature, thank you for implementing it! And to add that the Hide Read Button does add to the Hidden Posts.

**Comment by aeharding** [comment]
Thanks for the issue. I'm a little confused about the reproduction for this. If hide read posts is enabled in Lemmy, they won't hide client-side and thus won't be in the hidden posts section. There's not too much we can do about that. The solution would be to allow showing read posts in the Lemmy profile.

**Comment by Daneish** [comment]
Thanks for looking into this. I will reply again tomorrow when I have a bit better headspace.

**Comment by Daneish** [comment]
Hey, thank you for your explanation and sorry for the delay getting back to you.

I was conflating the Mark As Read, and hiding posts features, and misunderstanding at which level posts were being hidden.

With the Show Read Posts Lemmy setting disabled, hiding posts manually, and mark as read on scroll behave similarly. So on an app refresh (app was closed by iOS to save memory), all the read posts are “hidden”, but instead of that happening on the Voyager side like I assumed, it was happening on Lemmy side.

Because of how these settings interacted, I assumed that hiding posts in Voyager was automatic, but I now realise it’s a manual task with the Hide Read Button (or on individual posts).

I have switched the Show Read Posts setting back on. Now on an app refresh the read posts are still in my feed, and I can tap the Hide Read button and they get saved into my Hidden Posts section.

In my ideal world, it would be great if there was just one list of hidden posts, rather that one kept by Voyager, and one kept by Lemmy. That way it would be in sync whether you used Voyager or directly on Lemmy.

Is it possible to query the Lemmy API to get a list of hidden posts?

Congratulations on the v1 release! 🚀

**Comment by aeharding** [comment]
Ahh, I see.

Ideally Lemmy would provide a query param for requests so we could ignore lemmy hidden posts when fetching posts. :)

Do you want to create a feature request for that? Otherwise I can.

Thanks!!

**Comment by Daneish** [comment]
Hey there, life is a bit hectic at the moment and I haven’t been able to raise the request with Lemmy, sorry. Not sure I would be able to follow up on it, so I might leave it to you. Happy to close this issue off, or whatever you prefer.

**Comment by aeharding** [comment]
Update: Voyager now has its own automatically hide read posts functionality that works better that Lemmy's default. So if you turn off Lemmy's implementation it should behave as expected. Therefore I'm closing this. Thanks for your detailed issue reporting.
