### ISSUE TITLE
Comment box sometimes disappears on iPad

### ISSUE THREAD

**Issue by garretble** [aeharding/voyager#491]
When attempting to reply to a comment, sometimes the comment box briefly shows up then disappears. I believe the area where the comment box is supposed to be still “acts” like it’s there, but it’s simply not painted to the screen. You can still type in this invisible box, but you will not see any controls. It almost feels like — to put it in CSS parlance — a z-index issue where the comment modal is somehow being stuck behind the main content.

I wish I could say I could pinpoint exactly when this happens, but at the moment I don’t have any good steps to reproduce only to say that it does happen. I’d also provide a screenshot, except, well, it’d be a screen shot of nothing but a normal looking Voyager screen.

I do use my iPad with an external keyboard and trackpad, if that helps at all.

**Comment by kerosyn** [comment]
Just saw the video included in the duplicate issue #542. What's happing with the reply window looks to be similar if not the same issues as what is affected some of the menus as reported in #380.

**Comment by aeharding** [comment]
This is an iOS 17 beta-only issue

**Comment by aeharding** [comment]
Resolving, will be fixed in a future iOS 17 beta

https://bugs.webkit.org/show_bug.cgi?id=257861
