### ISSUE TITLE
Have an option for pagination

### ISSUE THREAD

**Issue by alexander-paterson** [aeharding/voyager#495]
I liked having the pagination option enabled in Apollo. It helped me not just continuously scroll and scroll looking at posts. I could see I got to page five and stop for example. 

Bonus if you could configure page size, ten posts, twenty five posts etc and select a page limit similar to how RES works. Where you specify to be notified when you hit a certain page number but can tap to continue if you wanted.

**Comment by aeharding** [comment]
Thanks, this is a duplicate of #334
