### ISSUE TITLE
When opening links with external app the link is also opened inside Voyager

### ISSUE THREAD

**Issue by qilto** [aeharding/voyager#506]
This is a bit of an edge case, but I am using Voyager on Android using Hermit. Hermit gives the option of opening links with the default app that is set in Android, which does work with Voyager. However, for some reason Voyager will also open the link inside itself even though the link will already be opened with the external app. 

For example, if you click on a youtube link in a post, the link will open in the youtube app if it is set to open those types of links. Voyager will also open the youtube link in itself. This kind of behavior does not happen with other PWAs I have used.

**Comment by aeharding** [comment]
That's interesting. If anyone wants to figure this out it would be appreciated.

**Comment by aeharding** [comment]
I'm closing this because I don't think it is something Voyager can solve - maybe a Hermit issue?
