### ISSUE TITLE
Left/right swipe issues

### ISSUE THREAD

**Issue by misaligar** [aeharding/voyager#511]
On my iPhone 13, I often inadvertently upvote a post when I attempt to go back to previous page. Is it possible make a change so that there is more space between the upvote and go back actions? For instance, I think it would work better if the area dedicated for going back gets larger. This would potentially eliminate the accidental upvotes.

**Comment by aeharding** [comment]
Unfortunately this logic is hardcoded in Ionic, so there's nothing was can adjust in Voyager (other than disabling swipe right completely, which will happen with the custom gestures feature).

But, Ionic has been very helpful and responsive in the past, so I remain hopeful this will be improved!

**Comment by robertafreese** [comment]
By disabling the swipes in the new Gestures settings, that left-to-right swipe is now "back" so this may be a solution? I have not accidentally voted or replied since enabling the new feature with release 0.28, it is a complete solution for me at least.

**Comment by sk4k2k** [comment]
I also would like a larger area to swipe left to "go back."  I have left swipes disabled completely now, but it would be good to set a left swipe gesture to go back or increase the swipe to go back area when left swipes are disabled. Should I create a separate enhancement ticket for it?

**Comment by aeharding** [comment]
Should be resolved in 1.9.1!
