### ISSUE TITLE
Full-page swipe action?

### ISSUE THREAD

**Issue by BluDood** [aeharding/voyager#523]
Hey! I have a feature request.
In Alien Blue / the official Reddit app, you can swipe anywhere on the screen towards the right (so long it doesn't trigger another action) as a swipe to close action. Could this be implemented into Voyager? I see it uses Ionic, not sure if they have that as a feature.

Since Voyager has quite some swipe actions to use, it should probably have less priority than other actions or maybe even be off by default. Not sure what the best solution is here

Thanks for this great app!!

**Comment by aeharding** [comment]
Hi there, thanks for the request! This is being tracked in #101
