### ISSUE TITLE
IPFS video links don’t embed properly

### ISSUE THREAD

**Issue by Ginjutsu** [aeharding/voyager#530]
I noticed that when browsing posts which contain a link to an MP4 file, Voyager very conveniently embeds the video in the post. This is an awesome feature!

Unfortunately, it doesn’t seem to work well for IPFS links, even when including an .mp4 filename at the end of the URL. Doing this will allow the video to embed just fine on the Lemmy-UI web interface, but it won’t carry over to the app interface.

I’m posting this as IPFS is a great option for decentralized video sharing online and it would be super nice to have it work just like any other MP4 url.

[IPFS Video for testing purposes](https://ipfs.io/ipfs/QmRgqE5HqLGgB2DDTdk7AcDe7qrhu55attTgf994X4gpDv?filename=celeryman.mp4)

**Comment by Generator** [comment]
You can post on testing instance https://enterprise.lemmy.ml/post/417347

**Comment by BarterClub** [comment]
Can we get this for a few other sites? 

Imgur, medal, twitch, YouTube, and so on

Also, the ability to google the feature on or off.

**Comment by carloscheddar** [comment]
> Can we get this for a few other sites?
> 
> Imgur, medal, twitch, YouTube, and so on
> 
> Also, the ability to google the feature on or off.

#571 loads Imgur in the feed and possibly a few others as long as the `embed_video_url` is being sent from the server.

**Comment by sharunkumar** [comment]
> You can post on testing instance https://enterprise.lemmy.ml/post/417347

does this video still exist? because the player seems to load but not the video itself

![image](https://github.com/aeharding/voyager/assets/715417/3dd45587-2cc5-49bc-a0b8-4501e5ba26b7)

**Comment by mandolinman137** [comment]
@aeharding I opened https://github.com/aeharding/voyager/pull/2258 for the youtube portion (it's probably the most commonly posted site on lemmy for videos). Let me know if you have any thoughts! I can adjust the implementation too if we prefer to make it optional or the toggle for "Embed External Media" site-specific.
