### ISSUE TITLE
[Feature Request] Double-Click on User icon in navbar switches to previous account

### ISSUE THREAD

**Issue by rlirli** [aeharding/voyager#532]
Also: Long-Click on navbar User icon opens the Accounts modal.

**Comment by rlirli** [comment]
My additional also open the account Switcher on long press, is already underway in #118

**Comment by aeharding** [comment]
Hi, thanks for the request! This is tracked in #85

**Comment by rlirli** [comment]
Hi @aeharding, opening the account switcher on long press of the account button was only a secondary thought to this issue.

The requested feature here in #532 was to **switch between** active and most recently used account (& instance) after a **double-tap** on the account button. I'll add that as a comment to #85.
