### ISSUE TITLE
Android.(Firefox) unresponsive

### ISSUE THREAD

**Issue by evilscarp** [aeharding/voyager#544]
Version 1.0.1, LineageOS 13 (TQ3A.230705.001); OnePlau 5T (dumpling); no mods

After two or three page loads both PWA and m.Lemmy.world code becomes unresponsive to tap and gesture input.

First manifests in text entry, where keyboard displays briefly, then dismisses, rendering text entry impossible. Proceeds to slow tap.respond, then ghost touches, then crashes (exits).

Back key and swipe gestures also become unresponsive.

**Comment by aeharding** [comment]
Hi there! I love Firefox but I've heard that it's glitchy and slow on Android with Voyager. There's not really much we can do here; I recommend trying a Chromium based browser until Firefox performance improves. Sorry!
