### ISSUE TITLE
Install button not working in Yandex Browser

### ISSUE THREAD

**Issue by murolem** [aeharding/voyager#545]
**Steps to reproduce**
1. Open web app, click on settings button → Install app → Install app.

Clearing cache does not help. Issue exist only in this browser, in Chrome everything works fine.

Device: Redmi Note 10 Pro @ MIUI 13.0.10 @ Android 12
Browser: Yandex Browser 23.7.2

**Actual**
- Install popup not showing up.
- Install app button showing up again after reload.
- Notification bubble at Settings button persist after reload.

**Expected**
- Install popup showing up, installation is available.
- Install app button not showing up again.
- Notification bubble in Settings button not showing up because of app install recommendation.

**Screenshots**
<details>
<summary>1. Opening app</summary>
<img src="https://github.com/aeharding/voyager/assets/20380250/1c4e9fea-05aa-4018-8e0d-957234cd481d"/>
</details>

<details>
<summary>2. Clicking Install app</summary>
<img src="https://github.com/aeharding/voyager/assets/20380250/a4ddd7fe-2c84-4667-a255-1493b4c19c56"/>
</details>

<details>
<summary>3. Reloading app</summary>
<img src="https://github.com/aeharding/voyager/assets/20380250/be1f08d1-cb96-4db7-87d0-a4fdc92c6368"/>
</details>

**Comment by aeharding** [comment]
Hi there! I believe this is a bug with the Yandex browser. I suggest you open an issue with them.

Otherwise, Chrome on Android works fine from what I've heard.
