### ISSUE TITLE
Optimise loading for server avatar icons on the posts/communities view

### ISSUE THREAD

**Issue by miclgael** [aeharding/voyager#550]
Thanks for the great web app!

I noticed an image performance issue this morning. 

### Context

- The [posts/communities view](https://wefwef.app/posts/lemmy.world) presents a list of Communities and their icons.
- The icons as rendered in the DOM are 28x28 pixels.
- The source of the icons can range anywhere between 300x300 to 1500x1500 pixels, and the images can be of any compression quality.
- This can cause the page to load in a sluggish manner, and the images also load progressively, as noted in #386 
- For a user with very many communities in the list - this may affect interactivity. 
- On subsequent page loads, the images load from a cache - however, this means Voyager is potentially storing a large amount of data in the users browser. 

### Suggestion

1. Add `loading="lazy"` attributes to `<img>` elements. `width="28"` and `height="28"` attributes should also help avoid layout shifting. 
2. Investigate a method of post-processing the original images so that a 28x28 pixel icon can be retrieved
3. Consider loading the assets locally, if there is no server? 🤔 
4. I'm not sure that `size` is a valid attribute for the `<img>` element? 🤔 
5. The image elements should probably also have empty `alt=""` attributes, so that screen-readers aren't reading out the image file name. 🤔 

### Screenshots

![a first screenshot showing html source alongside DOM, highlighting small icon with an large source](https://github.com/aeharding/voyager/assets/4301358/4b366380-97e6-4fb7-a062-8c868164f3aa)

![a second screenshot showing the same example on a different image](https://github.com/aeharding/voyager/assets/4301358/88292699-1c31-471e-81d7-36c9f89d27f0)

Thanks!

**Comment by aeharding** [comment]
Thanks! I am adding an optimization for avatars. Unfortunately, optimizing images relies on aspect ratio and natural image dimension information which we currently don't receive from lemmy.

Please follow this issue for updates: https://github.com/LemmyNet/lemmy/issues/3328 and once that's implemented we can definitely optimize for this.

Regarding your any other issues, please make a separate issue per ticket (or a GitHub discussion for questions).
