### ISSUE TITLE
Unable to scroll on video in feed

### ISSUE THREAD

**Issue by JDShadowline** [aeharding/voyager#551]
There appears to be a bug at least for me where scrolling does not work when touching on part of a video. This does not seem to happen within the post itself. I'm not able to show the taps in the screen recording but hopefully it gives a little more insight in case this effects more than just me.

Versions:
- Voyager: 1.0.1
- iOS: 17b4

https://github.com/aeharding/voyager/assets/52862143/bdc18cf6-5d27-4493-a14e-8b5a89992ff4

**Comment by aeharding** [comment]
I cannot replicate this - can you please try restarting your device?

Otherwise maybe it's an iOS 17 issue?

**Comment by JDShadowline** [comment]
I have yet to come across another video that does it, it seems to be just that one for some reason. I'm closing this unless I can narrow it down a bit more to be reproducible. (I'm blaming iOS 17 for now...)
