### ISSUE TITLE
Last update froze the entire app

### ISSUE THREAD

**Issue by LazaroFilm** [aeharding/voyager#554]
I just clicked update this morning and now the app freezes after a couple of seconds. The front page doesn't scroll, the bottom bar isn't responsive. I can't even get to the update button before it freezes.

**Comment by aeharding** [comment]
Hi there! That's strange, I haven't received any reports of freezing.

Can you please try restarting your device?

Also provide device make and model.

Thank you!

**Comment by LazaroFilm** [comment]
I created a new home shortcut and it works. Old one is still dead somehow...

**Comment by aeharding** [comment]
Okay great! I'm going to write this off as a strange device issue then
