### ISSUE TITLE
Main Headers blurry when using swipe gestures

### ISSUE THREAD

**Issue by jumpers775** [aeharding/voyager#559]
When using swipe gestures on my iPhone 12 on the latest iOS 17 beta the main headers don’t align correctly with other ones and hence appear blurry.

example (settings label and communities label):
https://imgur.com/a/BbUFHW0

**Comment by aeharding** [comment]
Thanks, but this is an Ionic bug and I'm sure it will be addressed there at some point. Feel free to report upstream
