### ISSUE TITLE
[Feature Request] Zoom image using double-tap gesture

### ISSUE THREAD

**Issue by deadmeu** [aeharding/voyager#570]
The Android Firefox app has a feature which allows you to zoom in/out an image by double tapping and then swiping down/up respectively. It would be great if Voyager had this feature as I use my phone one-handed and having to bring my second hand in to zoom in/out images gets annoying.

**Comment by aeharding** [comment]
Thanks for the issue, but double tap to zoom seems to be working fine for me on Android. Perhaps it's some issue with your device?
