### ISSUE TITLE
Apple Watch Login not working when multiple accounts are used

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#588]
I had two accounts logged in in the app, and the Apple watch app wouldn't let me use either of them. As soon as I removed one account it worked correctly.

Probably not the biggest priority though.

**Comment by aeharding** [comment]
It is working fine for me, perhaps your phone<->watch connection is lagging?

**Comment by fer0n** [comment]
You might be right, if no one else is experiencing this you can probably close it.
