### ISSUE TITLE
APK Download and F-Droid App

### ISSUE THREAD

**Issue by CoffeeCoder1** [aeharding/voyager#592]
I think an APK download in the GitHub releases and [F-Droid](https://f-droid.org/) app would make the Android app more accessible to some people, as some people do not have the Play Store on their device or can not use it.

**Comment by aeharding** [comment]
I'm looking into this. #594 should make the release process much more compatible for F-droid

**Comment by aeharding** [comment]
Tagging as help wanted. Repo should be ready.

If you'd like to help with this:

- Let us know on this issue if you are going to work on it same day so we don't step on toes
- Follow guide to make a PR to f-droid: https://f-droid.org/en/docs/Submitting_to_F-Droid_Quick_Start_Guide/
- The following Voyager android setup guide should help translate into F-droid yml: https://github.com/aeharding/voyager#android-native-app
- Let us know here when done :)

**Comment by shuvashish76** [comment]
RFP: https://gitlab.com/fdroid/rfp/-/issues/2503

**Comment by IzzySoft** [comment]
Fastlane is in the wrong location: `/android/metadata`, so the F-Droid process cannot find it, and must simply be moved one level up. Can you do that (and if done let me know, as with my repo the location is configurable and then needs to be adjusted)?

**Comment by aeharding** [comment]
Thanks @shuvashish76 @IzzySoft!

@IzzySoft, does this look right? Moved to fastlane folder

https://github.com/aeharding/voyager/pull/631/files

**Comment by IzzySoft** [comment]
Yes, that seems right – thanks! Once it's merged, we can send the bot again on the RFP to confirm. As for guidance with Fastlane, be welcome to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) when needed. It also lists the "official" locations supported by F-Droid.

**Comment by aeharding** [comment]
Great, merged!

**Comment by IzzySoft** [comment]
Thanks! Bot triggered. Oh, and I hope my assumption concerning the license on the lib was right; no license would trigger the scanner to yell "NONFREE!" otherwise (if there was no license), once my new library definitions have been pushed :wink:

**Comment by IzzySoft** [comment]
> Fastlane language code en-US was not found or incomplete, Fastlane can't be used without it.

Oopsa:

![image](https://github.com/aeharding/voyager/assets/6781438/6c4a1a1e-79c9-4c8f-83cc-e9f98c1cf821)

Those `*.txt` files must be **INSIDE** the `en-US` directory :see_no_evil: Apologies for having missed that, guess I need new glasses… (but as you see in the screenshot, it **looks like** they are inside, but they are only **next to** it).

**Comment by aeharding** [comment]
Oh, oops! Should be better now!

**Comment by IzzySoft** [comment]
Triggered the bot again.

**Comment by aeharding** [comment]
@IzzySoft Does the bot need to be triggered again? I pushed an update that should fix the distributionSha256Sum warning :)

**Comment by IzzySoft** [comment]
Thanks, but if it's only that: no. That hint is just for you and to secure your own builds. F-Droid uses its own "gradle setup".

**Comment by aeharding** [comment]
@IzzySoft, is there anything I can do to get this moving again? Thanks in advance! :)

**Comment by IzzySoft** [comment]
It needs someone to package it via an MR now. I've just added the "ready" label to signal that – but with the length of the current "backlog" that could take a while to be picked up. You could give it a try yourself, see [Quick path to get your app into F-Droid](https://gitlab.com/-/snippets/1896503#quick-path-to-get-your-app-into-f-droid) for some hints on that.

**Comment by aeharding** [comment]
Merged into F-droid, so we should see it show up in the F-droid store within a week! 🎉
