### ISSUE TITLE
No Material You icon for android

### ISSUE THREAD

**Issue by finally-awake** [aeharding/voyager#593]
Google has a build-in material you icon theme that looks like this: 
![Screenshot_20230805-015844_DerpLauncher](https://github.com/aeharding/voyager/assets/141446601/c322ff24-9cb9-490a-9b0d-3161a4233ac4)

The Voyager native android app currently doesn't have one. It looks like this: 
![Screenshot_20230805-015928_DerpLauncher](https://github.com/aeharding/voyager/assets/141446601/135c91e7-c22c-4c53-9f7e-3c77e2ee38f6)
 
I know this requires a separate design and stuff but it would be nice.

**Comment by bblacher** [comment]
I would love to see this, as someone using the Material You icons this makes the app not fit in with every other app.

**Comment by Donnnno** [comment]
Hi, I would love to give it a try!

**Comment by Donnnno** [comment]
Here's my first attempt. It helped that I already drew it for Arcticons :)

I've removed the mouses body, for a more minimalistic approach, fitting a material you icon more. 

Maybe some small line tweaks are necessary, or an option with the astronaut body, let me know what you think! 

![image](https://github.com/aeharding/voyager/assets/31142286/0d0d1264-c6a0-40e5-a432-3cf092eb9ad6)

**Comment by aeharding** [comment]
@Donnnno that looks fantastic! I agree, for Material You, removing the body is best for full bleed best practices. I have no notes, so whenever you're happy with it!

**Comment by Donnnno** [comment]
Wanna add the icon in android studio, but I'm getting this error:
Caused by: org.gradle.api.resources.MissingResourceException: Could not read script 'C:\Users\xxxx\xxxxx\GitHub\voyager\android\capacitor-cordova-android-plugins\cordova.variables.gradle' as it does not exist.

**Comment by Donnnno** [comment]
Tweaked the stroke around the whiskers slightly to make it work more in smaller settings 
![image](https://github.com/aeharding/voyager/assets/31142286/85dae83a-19ed-44ee-b4e4-8fe6c3dc6b9c)

**Comment by aeharding** [comment]
Have you [checked the readme setup instructions](https://github.com/aeharding/voyager#android-native-app)? You need to have nodejs and `pnpm install` `ionic capacitor build android` etc to get capacitor setup.

Otherwise I can make the PR and I will add you as a co-author :)

**Comment by Donnnno** [comment]
I haven't 😅
will take a look

**Comment by Donnnno** [comment]
Here's the SVG! You can add it yourself in android studio by converting it to an XML, it shouldn't be too much work :)


![voyager_monochrome](https://github.com/aeharding/voyager/assets/31142286/16f9f3f9-2fa9-4f74-96fe-32370bca2643)
