### ISSUE TITLE
Download images from android native app

### ISSUE THREAD

**Issue by LawsuitLigament** [aeharding/voyager#597]
Please add an option to download images and videos within the app.

**Comment by aeharding** [comment]
You should be able to download by long pressing in iOS and android as a PWA. Android native doesn't work for long press so that should be fixed.

**Comment by LawsuitLigament** [comment]
> You should be able to download by long pressing in iOS and android as a PWA. Android native doesn't work for long press so that should be fixed.

Yeah I'm using the web app to download images for now, but if an option to download images is added to the android native app then I'll happily switch over.

**Comment by Vertelleus** [comment]
Please allow long press on images to share or download in pop-up menu. Sharing the whole link is a bit messy.

**Comment by VipinVIP** [comment]
I guess with the latest release this issue is fixed. However, a progress bar for the download ( maybe as a notification ) would be good too.

**Comment by aeharding** [comment]
Thanks! I'm closing this issue for now. Extra enhancements and support for video downloads should be a separate issue
