### ISSUE TITLE
Pressing Android back button from an image exits app

### ISSUE THREAD

**Issue by forsakenpariah** [aeharding/voyager#601]
This bug seems to affect only the Android version from the play store and not the PWA version on my device. This basically renders the app useless for me.

**Comment by aeharding** [comment]
Thanks for the issue! I can reproduce this

**Comment by forsakenpariah** [comment]
After playing with it again I noticed it only happens from the initial home screen upon opening the app. If I change from Home to All or Local, or go to any community, the bug disappears. Also navigating back to Home from another community no longer produces the bug.

**Comment by aeharding** [comment]
Thanks! This should be resolved in 1.4.1.
