### ISSUE TITLE
Add support for opening Lemmy URLs

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#608]
Hoping for easier ways to use Voyager to open Lemmy URLs (from outside the app). I'm sure contributors are already thinking about this, but I didn't see this captured in an existing open/closed issue. 

Use cases: 
1. A Lemmy post URL is shared with you.
1. Comparing/testing how posts are rendered in the various emerging Lemmy clients.
1. Want to switch to Voyager after opening a post in a mobile browser.

As of 1.4.0, I believe the best workflow is to use the (pretty great) search feature and use terms that appear in tht desired post.  

I am primarily using the iOS app now, so some of these are iOS-centric, but I'm sure some are valid for PWA and Android. This is an attempt at an somewhat exhaustive list of potential implementations (inspired by [this Reddit post](https://www.reddit.com/r/apolloapp/comments/9xw2e3/how_to_open_a_reddit_link_in_apollo/) that helped refresh my memory).

I imagine that some of these are trickier than others because Lemmy URLs aren't all from a single domain. I am no developer, so the compatibility column is my best guess. 

All of these describe what to do with a Lemmy post URL:

| # | Method | Apollo Parity | App Compatibility | Notes |
| --------| --------------- | --------------- | --------------- | -------------- |
| 1 | ✅ DONE ~~Paste into Voyager search~~ | Maybe? | iOS, Android, PWA | Bean detects when a URL is pasted into search, but doesn't show any results when a lemmy.world post URL was used. <br><br>Last week I swear this worked on one of the other iOS clients (Memmy, Mlem, Avelon, Lemmios, Bean, Lemmotif, Liftoff!, Thunder, Lemur) ... but trying again with the latest versions as of this post did not work for any of them. | 
| 2 | ❌ WONTFIX ~~Prompt to open from clipboard on Voyager launch~~ | Yes | iOS, Android, maybe PWA? | Long press the URL. Copy. Open Voyager. Click yes/OK when it prompts to open the link. | 
| 3 |  ✅ DONE iOS ~~"Open in Voyager" from Share Sheet~~ | Yes | iOS, maybe Android | Believe this was implemented as an iOS Shortcut that you could install from Apollo. I am less familiar with Android but perhaps Tasker could facilitate this. 
| 4 | [Opener](https://apps.apple.com/us/app/opener-open-links-in-apps/id989565871) Support | Yes | iOS, maybe others | Requires paid "Opener" app on the App Store. Share the link to Opener. Opener will offer to open it in Voyager.<br><br>This probably has less to do with Voyager and more to do with working with the Opener developers. There is probably an Android equivalent, or perhaps that OS offers "default app" options unlike iOS. Edit: sounds like Hermit allows this, per #506 | 
5 |  ✅ DONE `vger://` ~~Something with URL schemes?~~ | No | iOS and Android probably | I am no developer so I don't know what's involved here, this sounds relevant, from [Apple's developer pages](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app):<br>*"Custom URL schemes provide a way to reference resources inside your app. Users tapping a custom URL in an email, for example, launch your app in a specified context."*  | 
6 | Safari Extension | No | iOS | I don't use Safari personally, but I know other clients like Memmy have done this |

I am happy to split this up into component issues if that's preferred over this monolithic one 🙂. 

Keep up the great work. I read every release notes entry. The pace of development is exciting to watch.

**Comment by ElRocha** [comment]
I would also would like support for this on Android. The Infinity for Lemmy app already has implemented this for a lot of lemmy instances URLs and it works really good.

For getting a list of URLs, maybe scrape them from something like lemmyverse.net?

**Comment by Efreak** [comment]
You don't need the full list of instances for Android if you can get support for Voyager in [Lemmy Redirect](https://github.com/zacharee/MastodonRedirect); for iOS, maybe @zacharee has a place you can get addresses from? A quick look doesn't tell me when Lemmy Redirect grabs the URLs (if it's at compile time, you might be able to reuse some code in a GitHub action that runs every day/week/release in another branch/repo)

**Comment by zacharee** [comment]
I don't think iOS will allow third-party apps to automatically open Lemmy URLs. There's a policy/soft limit of 20-30 associated domains for a single app, and it looks like every domain in that list needs to verify that it's associated with the app, unlike in Android where you can manually enable domains for third-party apps. For iOS, the best approach is probably to use a share target.

https://lemmyverse.net has a few data endpoints that return domains in JSON format. The Lemmy source is missing some domains, but it's possible to use a different endpoint and filter to get Lemmy instances. This is what Lemmy Redirect is doing: https://github.com/zacharee/MastodonRedirect/blob/main/lemmyredirect/src/main/java/dev/zwander/lemmyredirect/util/FetchInstancesActivity.kt.

**Comment by aeharding** [comment]
Hi! This will be partially addressed by #829. You will now be able to paste in links to posts/comments/communities/user profiles into the search to get directly to the content.

**Comment by boozook** [comment]
[There I've shortly described](https://programming.dev/post/5502472) possible proper implementation.

**Comment by 0xCmdrKeen** [comment]
This NPM package might help: [react-native-share-extension](https://www.npmjs.com/package/react-native-share-extension). It supports both iOS and Android, but the setup looks quite complex.

**Comment by gobbledygoober** [comment]
Thanks for editing the original post @aeharding to show what's been implemented! I started doing that a while back and got distracted.

**Comment by aeharding** [comment]
So update on what's coming soon:

 1. I've added support for `vger://` schema to Android and iOS
 2. I've added an Action Extension "Open in Voyager" to iOS
 3. `MastodonRedirect` has added support for Voyager: https://github.com/zacharee/MastodonRedirect/releases/tag/1.13.0

This will be released soon.

In terms of what is left -

 1. I don't think I'm going to add auto-read clipboard. Android/iOS has been clamping down on this (understandably) and I think the alternatives are good.
 2. I am interested in adding Opener support - perhaps after next release contact the dev?
 3. Safari extension seems like something for the future. I'm not sure how it differentiates from the Action Extension, however.
 4. I would like to add a list of instances to the android manifest. However, I need to figure out how to automate this, and if there is enough interest (vs using MastodonRedirect).
 5. The Voyager PWA on iOS has no options, but the Voyager PWA on Android could potentially support [Protocol Handlers](https://developer.mozilla.org/en-US/docs/Web/Manifest/protocol_handlers)? Not sure the support though. Suggestions welcome.

Thoughts? Questions? :)

**Comment by aeharding** [comment]
I think this is pretty well resolved, with solutions for both iOS and Android, so I am going to close it. There's still a couple areas that could be improved, if there's anything in particular please create a new issue.

Thanks! :)

**Comment by gobbledygoober** [comment]
> I think this is pretty well resolved, with solutions for both iOS and Android, so I am going to close it. There's still a couple areas that could be improved, if there's anything in particular please create a new issue.
> 
> Thanks! :)

I just gave "Open In Voyager" a try. It works great from Safari. When attempted from Chrome, it doesn't seem to work or provide any feedback. Is there a reason it won't work on non-Safari browsers? Thanks!

**Comment by aeharding** [comment]
This is a limitation of any "Open in X" buttons. You can try Apollo, Ice Cubes App, Mastodon, same problem there :(

**Comment by gobbledygoober** [comment]
> This is a limitation of any "Open in X" buttons. You can try Apollo, Ice Cubes App, Mastodon, same problem there :(

I'm quite certain Apollo's share sheet button worked from Chrome. Was it perhaps an iOS Shortcut in disguise or something? Safari Extensions I totally get working only in Safari. 

I can't prove it anymore (RIP Apollo), but the comments in this post are the best supporting evidence to my claim 🙃
https://www.reddit.com/r/apolloapp/comments/velwb3/any_way_to_set_reddit_links_in_google_chrome_to/

I appreciate the response!
