### ISSUE TITLE
[Feature Request] Search within community

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#610]
Similar to the other recently logged search-related issues (#608 and #609), suggest to make Voyager's search features more comprehensive by adding the ability to limit a search to a specific community. I believe Apollo had this feature.

**Comment by tobeon** [comment]
Would love this. Yes Please!

**Comment by ClassickTech** [comment]
Yes please. We need this.

**Comment by Disonantemus** [comment]
Where is it?
I can't find a way to do a search inside a community.

---

~~~ocaml
Voyager 2.17.0 (Aug 13, 2024)
~~~
