### ISSUE TITLE
[ANDROID] BUG: Tapping the bottom of the screen scrolls down by a certain amount, causing scrolling issues

### ISSUE THREAD

**Issue by Juansero29** [aeharding/voyager#612]
It's exactly what the title says. It's been there since Android app release officially. However is present both in the PWA and the official app. Whenever I scroll down there's a chance the screen just bugs and interpret it as tapping a sort of invisible button in the bottom of the screen that makes the whole app scroll down by ~2 posts.

**Comment by aeharding** [comment]
Hi there! Yes, unfortunately this is an Ionic bug. See https://github.com/ionic-team/ionic-framework/issues/21982. Closing as duplicate of #287.
