### ISSUE TITLE
Animation frame drops in the Android app

### ISSUE THREAD

**Issue by adarsh1001** [aeharding/voyager#616]
I've made a video comparing the PWA for Brave (Chromium) and the native android app. After logging in, some animations including the post open, post/comment reply and selecting an option in inbox or settings is very jittery on the Android app reproducible always.

https://github.com/aeharding/voyager/assets/8820038/40db932f-1ee3-46f4-b0cf-5d94d2ff32d5

Device: Nothing Phone 2 (Snapdragon 8+ Gen 1, 12 GB RAM)
Android: 13
App/PWA Version: 1.5.0

**Comment by khaveesh** [comment]
Reproducible even when collapsing / expanding long comment threads. Using the latest native android app.

**Comment by aeharding** [comment]
I added some optimizations in 1.9.0 that should mitigate page transition stutters. Comment collapse stutters will need more research for a different issue.
