### ISSUE TITLE
[Feature Request] Update indicator for native build

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#626]
I use TrollStore to install voyager on my device. When I was using PWA there was a handy indicator when new update was available. Maybe something similar could be done for native app? Also show direct link to the latest ipa.

btw I’m surprised how fast voyager is evolving. Thank you and contributors for awesome job!

**Comment by aeharding** [comment]
Hi! I've thought about that but it gets complicated with the various stores Voyager supports. We could just check the Github release, but that can lag by days depending on the store which would provide a bad user experience.

So, I'm closing this - thanks though!
