### ISSUE TITLE
1 more reply

### ISSUE THREAD

**Issue by KelvinCrag** [aeharding/voyager#628]
There's a bug in which clicking on the "1 more reply" button does not expand and show the reply.
> ![Screenshot_20230809-075049~2](https://github.com/aeharding/voyager/assets/64832927/426b27af-cb66-44ed-a5d7-a44aa861da1c)

**Comment by aeharding** [comment]
https://lemmy.world/post/2820061

> This is definitely a Lemmy bug. We use `child_count` to determine if there are unloaded comments, but `child_count` is incorrect in this case. (says 3 children, only 2 returned)

- [ ] Create upstream bug in Lemmy
- [ ] If nothing new returned present toast informing the user and hide more reply expander

**Comment by aeharding** [comment]
This may be fixed in lemmy v0.19, more investigation needed when publicly released

**Comment by aeharding** [comment]
This should be fixed in lemmy v0.19 so closing :)
