### ISSUE TITLE
"Show Read Posts" not available

### ISSUE THREAD

**Issue by qauff** [aeharding/voyager#632]
I've been using Voyager for a few versions now. Great app. Definitely most Apollo-like of all of them!

There is one issue I'm noticing, when I enable "Hide Read Posts" everything works as intended, but there's no way to "Show Read Posts". I can't seem to find the button. "Hide Read Posts" is just displayed every time I go into the hamburger menu. Clicking it also doesn't toggle show/hide read posts, it just seems to hide. So there's currently no way to view read posts after hiding it.

In order for me to show the posts again, I have to delete voyager and re-install, and re-setup all of my preferences. 🙏

Edit: It's also the same behaviour if I enable the floating "Hide Read Posts" button; only shows the "hide", never the "show".

**Comment by aeharding** [comment]
Hi there! So the hide read posts does just that: Hides read posts. It is not a toggle, on purpose.

You should be able to view posts that have been hidden in Profile -> Hidden :)

**Comment by qauff** [comment]
@aeharding so if I want to see read posts in my feed again, I gotta unhide each post one at a time?

**Comment by aeharding** [comment]
Yes, there is not any bulk unhide functionality right now

**Comment by qauff** [comment]
Ah, so "Hide Read Posts" is literally marking "Read Posts" as "Hide" too. Not a toggle. I was expecting a toggle behaviour. Good to know! Thank you.

**Comment by Link-69** [comment]
Also kinda disappointed it's not a toggle but it clarifies things, thanks

**Comment by aeharding** [comment]
Yeah, it follows the Apollo convention. It's mainly so people can quickly hide posts from feed as they read/scroll

**Comment by qauff** [comment]
I didn't realize that Apollo did that. Honestly, that makes the feature too intrusive for me to ever use it. I'm not looking to batch "mark as hide". Just to only display unread posts. 

Is it possible to get a new feature to filter for unread posts? 🙏
