### ISSUE TITLE
Don't add circle shapes to icons

### ISSUE THREAD

**Issue by GammaGames** [aeharding/voyager#633]
I'm on beehaw where we've got hex community icons: 
![image](https://github.com/aeharding/voyager/assets/7832163/5b14218d-154c-49dc-89cf-e22b8ff0fe8f)

Would it be possible to add an option to remove the circle shape respect an icon's transparency? I think the hexes would look really nice in the app, the white background + circle shape is meh

**Comment by GammaGames** [comment]
Is there a cache I have to clear or something? They're still not transparent 

![image](https://github.com/aeharding/voyager/assets/7832163/f0571a6a-326d-4c5e-ac9f-95b5108fed4b)

**Comment by aeharding** [comment]
Hi there,

It should just work. What's the version of Voyager you're running? And what is your device OS and version?

**Comment by GammaGames** [comment]
version 1.9.2, ios 16.3.1 on an iphone 12 mini

**Comment by GammaGames** [comment]
Maybe it's using cached images? It looks like the humor community (still on beehaw) isn't loading its image

![image](https://github.com/aeharding/voyager/assets/7832163/f95fb72c-c9a5-4ede-9ac8-668a5c746a75)
