### ISSUE TITLE
Add bottom nav functionality to comments view a la Boost/Sync

### ISSUE THREAD

**Issue by zandm7** [aeharding/voyager#634]
Boost/Sync have a bottom nav UX that I really like; essentially it allows one to jump to the prev/next parent comment without needing to collapse the current thread. See the following image:

![Screenshot_20230809-142828~2](https://github.com/aeharding/voyager/assets/996428/08d3f861-271f-461d-a8dd-b8b15562ce94)

**Comment by aeharding** [comment]
I believe this is a dupe of #384
