### ISSUE TITLE
Add Q&A comment sort to show OP discussions

### ISSUE THREAD

**Issue by gobbledygoober** [aeharding/voyager#636]
Apollo had a "Q&A" comment sort that brought comments that the OP made or to which they replied to the top. This was helpful when you wanted to see discussions that involved a post's OP (e.g.  AMA style posts). 

Suggesting that this be implemented in Voyager as well. 

Thanks again Voyager devs.

**Comment by aeharding** [comment]
Hi, thanks for the request!

This feature is best suited in Lemmy. Once Lemmy adds support, we'll support in Voyager. So feel free to check/create an issue there!
