### ISSUE TITLE
Self-Host + Android App

### ISSUE THREAD

**Issue by RandomLegend** [aeharding/voyager#663]
Heyho,

first of all, fantastic app! Favorite way to go to lemmy!

Is it possible, or will it be possible in the future to connect the Android App to the self-hosted instance? I like to have my account credentials and the work to get the new posts on my own hardware. But i also want to use the android app instead of the PWA.

Is that a thing?

**Comment by aeharding** [comment]
Hi, thanks! Since the apps directly connect to the lemmy instance, there's no middle man. :) When you use the native apps no data touches any Voyager servers.
