### ISSUE TITLE
Text colored in accent colors is hard to read / Make accent colors less saturated and bit more darker

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#666]
Letters looks blurry to me if word is colored in accent color. I suggest changing accent colors for dark theme. Light variants looks good to me.
blue looks nice
red - #db1f1f (darker and less saturated)
green looks good
orange - #DF6F0E (slightly darker and less saturated)
violet - #942AD4 (darker and less saturated. it isn't retina-burning now xd)
mint - #53C391 (slightly darker to provide more contrast for switch widget)

Comparison:
![изображение](https://github.com/aeharding/voyager/assets/70429241/77c2ad7c-73f4-47df-bae1-4e3b4eb0297e)
![изображение](https://github.com/aeharding/voyager/assets/70429241/4aebfb5e-44a5-4691-a5e5-2e4bb49a2be0)
![изображение](https://github.com/aeharding/voyager/assets/70429241/4bd0c970-3287-457d-9d47-296871409a01)
![изображение](https://github.com/aeharding/voyager/assets/70429241/1f3d015c-68d7-4864-a91f-ffdc2b88393c)
![изображение](https://github.com/aeharding/voyager/assets/70429241/8b8ff7b5-74b7-4465-9e76-e674c29245b0)
![изображение](https://github.com/aeharding/voyager/assets/70429241/a27c37cb-0ac6-4a2f-b486-ee135e76814f)
![изображение](https://github.com/aeharding/voyager/assets/70429241/ddbebaee-4914-489d-bfed-ad600a912220)
![изображение](https://github.com/aeharding/voyager/assets/70429241/514d5d64-f8b8-4a82-bba4-e009e84e8aba)

**Comment by aeharding** [comment]
Hi there! I'm happy to get this merged to a PR if you want to open one :)

**Comment by RocketRide9** [comment]
> Hi there! I'm happy to get this merged to a PR if you want to open one :)

I will try
