### ISSUE TITLE
Should themes affect the upvote indicator in feeds and comments?

### ISSUE THREAD

**Issue by sf1tzp** [aeharding/voyager#670]
Hello! Loving the new Mint theme.

Do you think the upvote indicator color should change with themes? It might be weird with Firery Mario, where upvote becomes Red, but for Mint I think it would look better if the colors matched:

![image](https://github.com/aeharding/voyager/assets/84053270/6a1c00d2-629d-493f-b658-c7e5901dbd0b)

![image](https://github.com/aeharding/voyager/assets/84053270/df6276a3-10b4-4b88-b38c-94c615ebd72b)

Your thoughts?

**Comment by aeharding** [comment]
Hi there! Themes should not affect upvote/downvote colors. So I'm going to make this as a bug!

**Comment by sf1tzp** [comment]
Oh okay. Sorry if I wasn't clear - I don't see them affecting upvote colors. I was wondering if they should - for instance, with the mint theme, if I upvoted something the arrow would be colored teal.

In that case, I don't think there's a bug here. Thanks for answering!

**Comment by sf1tzp** [comment]
I will close this - don't want to bother ya! Cheers for the great app
