### ISSUE TITLE
Can no longer comment due to two languages being set 

### ISSUE THREAD

**Issue by aperson** [aeharding/voyager#672]
The instance that I'm on has me set both English and Undetermined as my language.  If I set my language to just English, I can comment, but then can no longer view any new comments or posts on my profile.  If I have it set to both, I can no longer comment or post via voyager.  I do not want to deselect undetermined as I would like to not miss out on content.

**Comment by aeharding** [comment]
Hi there! Voyager simply doesn't set a language_id on posts/comments and leaves that up to Lemmy. So, this sounds like a Lemmy bug. Can you please make an issue with Lemmy? Thanks

**Comment by aperson** [comment]
I filed a bug with lemmy, linking here for posterity:
https://github.com/LemmyNet/lemmy/issues/3884
