### ISSUE TITLE
Difference between PWA and play store version haptics

### ISSUE THREAD

**Issue by Hikiru** [aeharding/voyager#683]
The play store version's haptics are noticably more intense and buzzy than the PWA. It's uncomfortable to me personally, and IMO either haptic customization should be added or the haptics should be toned down to be more in line with the simplicity of the android PWA and the iOS app's haptics.

**Comment by aeharding** [comment]
Have you upgraded to the latest version?

**Comment by Hikiru** [comment]
Sorry if I sound nitpicky but now the haptics are so light I could barely tell if there were any at first. I think a good point of reference is the haptics for Samsung navigation gestures, the click on them is the closest I've felt to the click for upvote gestures on iOS. I'm not sure if the gesture navigation is different across phone brands though, so if the devs don't have a Samsung phone I don't know how useful this is.

**Comment by aeharding** [comment]
I tested on a Google Pixel, so no idea about Samsung but I assume there probably are differences. I don't have a way to test

**Comment by aeharding** [comment]
Closing for now since it's not currently actionable. I would be happy to reopen to test if someone would donate (money or a physical device) for me to test with :)

Thanks for understanding!!

**Comment by Hikiru** [comment]
Then the best option would be to add a slider for haptic strength, if that's possible
