### ISSUE TITLE
[Cosmetic] Finer style controls for text bodies

### ISSUE THREAD

**Issue by xan1242** [aeharding/voyager#690]
I have these requests:

- An option to change the font weight of the title (e.g. semi-bold and bold options)
- An option to specifically adjust comment text (line spacing in particular would be my biggest request, but also font size)
- Same option as previous but for post text body specifically

Basically, something similar to what Memmy has.

**Comment by aeharding** [comment]
Hi there! Thanks for the issue. I'm happy to take a look at any confusing font styles, but fine grained spacing/weight controls isn't something I am planning on implementing.
