### ISSUE TITLE
Web app (1.10.1) some images are broken while same work in chrome

### ISSUE THREAD

**Issue by damp-canary** [aeharding/voyager#691]
Some images are broken when seen trough voyager web app v1.10.1 yet same post shows same image when seen trough chrome directly (images below).

![Screenshot_2023-08-18-13-29-39-728_com android chrome](https://github.com/aeharding/voyager/assets/136996406/7bc39c83-e5f3-4867-8c0d-9694e6d02bd2)
![Screenshot_2023-08-18-13-41-08-834_com android chrome](https://github.com/aeharding/voyager/assets/136996406/67280803-a7e5-4dba-9cd0-6295e6e95151)
![Screenshot_2023-08-18-13-30-48-801_com android chrome](https://github.com/aeharding/voyager/assets/136996406/79180f95-0173-4cb3-89f1-ecc43ea2858b)

**Comment by aeharding** [comment]
Hi! What's your device operating system and version?

**Comment by damp-canary** [comment]
Hi!
I'm on MIUI 13.0.4 on Android 12 (SKQ1.211006.001).
Thank You for Your efforts!

With regards,
Canary

**Comment by damp-canary** [comment]
Sorry, fat finger on small button.

**Comment by aeharding** [comment]
Hi! I'm still not able to reproduce this. If anyone else has the same issue I'd be happy to reopen the ticket. :)
