### ISSUE TITLE
Move user instance under username so theres more space to click to go into a thread

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#694]
Currently you can usually only go into a thread by clicking the title on voyager vs all other apps because the user instance takes so much space. If moved under the username people can click to the right of it

![image](https://github.com/aeharding/voyager/assets/114287507/6df851fe-2f2f-474b-9d0e-bd2ebb0f8618)

**Comment by aeharding** [comment]
Hi there! Thanks for the suggestion, but this is not something I'm planning on supporting.
