### ISSUE TITLE
Share Gesture

### ISSUE THREAD

**Issue by vonProteus** [aeharding/voyager#696]
can you add to "Gestures" menu option for "Share"

**Comment by 80avin** [comment]
I tried this implementing, but strangely, on mobile I get error

```
DOMException: Failed to execute 'share' on 'Navigator': Must be handling a user gesture to perform a share request.
```

It doesn't work consistently even if I call navigator.share directly or ionic's share.

**Comment by aeharding** [comment]
This has been implemented for native clients only (due to web limitations) and will be available in next Voyager release
