### ISSUE TITLE
Option to unblur NSFW images/videos

### ISSUE THREAD

**Issue by tzutoo** [aeharding/voyager#70]
Hi, is there a plan to implement option to unblur nsfw images or videos?

**Comment by aeharding** [comment]
There is now! 😂

Probably a toggle in settings?

Off = Show as normal (no blurring)
On = Current behavior

**Comment by tzutoo** [comment]
> There is now! 😂
> 
> Probably a toggle in settings?
> 
> Off = Show as normal (no blurring) On = Current behavior

Yeah, that would be great!

**Comment by driftywinds** [comment]
I would also be interested in a toggle to unblur NSFW content by default

**Comment by homer1993** [comment]
Oh that would be so wonderful to have this feature available :).

**Comment by NoXmawe** [comment]
I got this working on a local build last night, I just wanna clean it up before I submit because my implementation of the actual blur was a bit hacky.
![image](https://github.com/aeharding/wefwef/assets/85526347/5b0e9efd-b64d-48a0-8ec0-7d64d3bd5886)

**Comment by CDeLeon94** [comment]
Having this option somehow tied to account would be nice. I prefer different behavior with my different accounts.

**Comment by aeharding** [comment]
Resolved in #427
