### ISSUE TITLE
Reader mode

### ISSUE THREAD

**Issue by aeharding** [aeharding/voyager#701]
Add a setting to enable reader mode (iOS native app only)

**Comment by boozook** [comment]
Reader view is great, but
I suppose more user-friendly __customizable way__ is to open in default browser and if it Safari for example, you can simply configure there (in the browser) __what page__ should be automatically presented in reader view.

**Comment by aeharding** [comment]
PR opened: https://github.com/ionic-team/capacitor-plugins/pull/1865
