### ISSUE TITLE
Viewing this Post Can Make Voyager Unstable

### ISSUE THREAD

**Issue by owlboy** [aeharding/voyager#720]
If you view this post, or view it leave and then view it again, Voyager becomes unstable.

https://programming.dev/post/2352926

Tested in PWA, iOS (latest), v1.11.2

**Comment by owlboy** [comment]
I've been looking around at old issues and checked on this.

The post no longer causes issues. And I notice that there is now a broken image/video at the top of the post. This might mean whatever broke was the cause. Or you already addressed this issue by showing the error message.

In any case. No more instability.

Thanks!

**Comment by aeharding** [comment]
Interesting... well, thank you for the follow up! I'll close for now, feel free to open a new issue if theres more problems.
