### ISSUE TITLE
Black screen after logging in

### ISSUE THREAD

**Issue by luke911** [aeharding/voyager#721]
I’ve been loving using Lemmy with Voyager since it was first released. Recently though I’ve been unable to use the app on iOS after logging into my instance, lemmy.okla.social. After logging into it, Voyager goes all black and I’m unable to see anything in the app. I’ve tried to delete Voyager and reinstall, same issue. I’ve tried changing the theme on my Lemmy profile, thinking that this could be causing an issue with Voyager but that has not had any positive effect.

**Comment by alexwasserman** [comment]
Hey, are you seeing the same errors are #716?

**Comment by luke911** [comment]
Yes I am, exactly the same errors. I'll close this one out and watch that thread. Thank you!
