### ISSUE TITLE
Blank screen for new Lemmy instance

### ISSUE THREAD

**Issue by Showfom** [aeharding/voyager#722]
It's just a blank screen without any content shows on a new Lemmy instance [R.NF](https://r.nf/)

For example:

https://vger.app/posts/r.nf/all

**Comment by alexwasserman** [comment]
Hey, are you seeing the same errors are #716?

**Comment by Showfom** [comment]
Hi,

I didn't see any errors but just no content with the latest Lemmy 0.18.4-beta.8.

API and lemmy-ui are working fine.

**Comment by Showfom** [comment]
Seems voyager is not working with latest Lemmy 0.18.4-beta.8

For example

https://m.lemmy.world/posts/lemmy.miichelle.moe/all
https://m.lemmy.world/posts/r.nf/all

Both instances are running on Lemmy 0.18.4-beta.8 but not working with voyager

**Comment by Showfom** [comment]
Same issue from Photon but they have fixed it:

https://github.com/Xyphyn/photon/issues/140#issuecomment-1705720755

**Comment by alexwasserman** [comment]
Thanks, @Showfom, I think this is a dupe of #716 , and I've submitted a PR to fix it: #723

**Comment by aperson** [comment]
Beehaw must've updated lemmy a day or so ago because voyager now entirely blanks out when they're selected.

**Comment by aeharding** [comment]
I believe this was fixed with the most recent patch!
