### ISSUE TITLE
Remember/Don’t change last page’s Sort By

### ISSUE THREAD

**Issue by teej107** [aeharding/voyager#725]
From All/Home/Local, I go into a community and change its Sort By. When I go back to All/Home/Local, the Sort By is also changed to what it was while in the community. I change it back to what it was before but then the data reloads and I lose my place.

**Comment by aeharding** [comment]
Hi there! I think this is a dupe of another issue. Basically there is an Ionic bug that makes accomplishing this a bit harder than initially thought. See: https://github.com/ionic-team/ionic-framework/issues/26524

**Comment by aeharding** [comment]
I believe this is a duplicate of #198, so closing in favor of that. Thanks!
