### ISSUE TITLE
Touch is too sensitive while scrolling 

### ISSUE THREAD

**Issue by jonasisozen** [aeharding/voyager#726]
Everytime I try scroll posts get randomly selected. No other app does this :/ 
My setup: nothing p
hone 1, android 13 and APK from github

**Comment by aeharding** [comment]
Hi there! This is being tracked here:

https://bugs.chromium.org/p/chromium/issues/detail?id=1474135

It's a chrome webview bug with momentum scrolling.

**Comment by aeharding** [comment]
Closing as duplicate of #710
