### ISSUE TITLE
FR: Allow opening links in default browser rather than embedded one

### ISSUE THREAD

**Issue by scstraus** [aeharding/voyager#729]
Hi there. Thank you so much for Voyager, it's a pleasure to use. I have one use case which would be really great if it were accomodated. I use [lemmit](https://lemmit.online/) to add reddit content to lemmy. Unfortunately in the case of videos, this content is sometimes hosted on Reddit itself which means I will be redirected to their content and the reddit website. Visiting reddit's website makes me feel dirty. 

Fortunately, an alternative is possible in [rdx](https://rdx.overdevs.com/) which allows you to view reddit content without visiting reddit. On desktop I am able to use a redirect extension to redirect all reddit content to rdx [like this](https://imgur.com/a/o7QMq9n), so that when I'm viewing lemmit content that redirects me to reddit, I will go to rdx instead. 

This is also a possibility in safari with an extension called Redirect Web For Safari. It works perfectly if I'm browsing in safari or in anything that tries to open the link in Safari. Unfortunately it does not work with Voyager's embedded browser window for previews.

Would it be possible to make an option that allows opening external links in a safari window instead of in the builtin window? Bonus point for allowing to choose which websites do this. 

It would be so great to ensure I'm never redirected to reddit's actual website again.

**Comment by aeharding** [comment]
This should already be an option in the native apps. (It is not possible in the PWA version.) :)
