### ISSUE TITLE
Collapse gesture is really collapse to top

### ISSUE THREAD

**Issue by QuarterSwede** [aeharding/voyager#732]
When collapsing a child comment by using the swipe gesture “collapse,” the parent is collapsed instead of the intended child only. If this is the intended behavior the gesture should be renamed “collapse to top” to be in line with the 3 dot menu wording on comments.

If it’s not intended, then the collapse gesture needs to collapse only the child, as in the tapping functionality when tapping on a child comment to collapse.

**Comment by aeharding** [comment]
Thanks! I agree, we can have both gestures.

**Comment by benjistokman** [comment]
This issue appears to have not been fixed and/or has been reintroduced. It's happening on IOS mode on F-Droid latest version (as of present)
