### ISSUE TITLE
Long Press Comments/Posts to bring up contexts menu

### ISSUE THREAD

**Issue by rahulakrishna** [aeharding/voyager#734]
This was an Apollo feature and in most apps the long press feels intuitive. 

This is what it looks like on Apollo: https://share.icloud.com/photos/0549vU1dh_KuEF_y3ohDDFQkA

**Comment by PyroGenesis** [comment]
I would prefer if Long Press would be a gesture. That way, you could set it to open the context menu like Apollo, or set it to collapse the comment thread like Boost.

**Comment by aeharding** [comment]
I love the iOS specific pattern, but not sure if this is possible on web.

At least we could pull up the bottom sheet menu on long press.

**Comment by aeharding** [comment]
Resolved in #1192
