### ISSUE TITLE
Not all posts of a subscribed community are displayed

### ISSUE THREAD

**Issue by Tealk** [aeharding/voyager#736]
In a community on my home instance not all posts are displayed.
![Screenshot_20230917-101729.png](https://github.com/aeharding/voyager/assets/12276250/950e8af8-8a43-4ba6-9c1b-f11e413e5133)

![Screenshot_20230917-101658.png](https://github.com/aeharding/voyager/assets/12276250/999cef3a-c6ce-4e6d-8026-35e1e7f861ea)

**Comment by aeharding** [comment]
Hi there! Is it possible you have hidden those posts? You can check in your profile. (Profile -> Hidden Posts)

**Comment by Tealk** [comment]
ATM i can see the Post there

**Comment by aeharding** [comment]
If the posts were hidden, that is why :)

You can now reset hidden posts, too (profile -> hidden posts -> reset)
