### ISSUE TITLE
Option to show hidden posts again

### ISSUE THREAD

**Issue by Tealk** [aeharding/voyager#737]
I miss the possibility to make hidden posts visible again

**Comment by aeharding** [comment]
You can do that individually on Profile -> hidden posts (and unhide in ellipse) but there is no bulk action currently. If there's no issue for unhiding everything and that's what you're looking for, feel free to make another issue!

**Comment by Tealk** [comment]
> If there's no issue for unhiding everything and that's what you're looking for, feel free to make another issue!

why a new issue, that's why I opened this one
