### ISSUE TITLE
Keyboard Input in Browser

### ISSUE THREAD

**Issue by FriederHannenheim** [aeharding/voyager#738]
Hey. Lemmy is a great app. I use it in my Desktop browser and I would really appreciate being able to use things like the arrow keys for scrolling or backing out of posts.

**Comment by aeharding** [comment]
Thanks! Closing as duplicate of #738

**Comment by FriederHannenheim** [comment]
Sorry. I believe you have made an error. This issue is #738

**Comment by aeharding** [comment]
Sorry #733 :)
