### ISSUE TITLE
Support for keyword filtering

### ISSUE THREAD

**Issue by DaveAlton** [aeharding/voyager#746]
I'm so tired of seeing certain keywords show up on my homepage. I would love to have the ability to filter by keyword. Everyone probably has some word that they roll their eyes at when they scroll through their app, and in many cases it's not just within a specific community.

**Comment by aeharding** [comment]
So I have this implemented in an experimental branch, but I'd like feedback.

- Should the keyword block search the post body? Is it necessary?
- Should posts/comments be blocked from a user profile?
- Should posts be blocked from a specific community?

imo a keyword filter should only filter keywords in a specific community or home/all feed, and only posts (not comments).

Thoughts? :)

**Comment by DaveAlton** [comment]
Great questions. If it only searched the title, I would be pretty happy. I wouldn’t filter anything from a user profile, just the home timeline. Blocking from a specific community would be really helpful. For my keywords, they mostly come from one or two communities. Allowing users to create rules, and then let them toggle each of these for each of the rules would be a god-tier feature. For instance (these aren’t the keywords I’m looking to block, they’re just examples):“Beans”. Block from the memes community (so food communities can still show posts about beans), don’t block from user profiles, don’t block from comments or post bodies“Hitler”. Block from everything. Anything mentioning hitler can be blocked. Bonus points for regex filtering.   On Sun, Oct 8, 2023 at 7:24 PM, Alexander Harding ***@***.***> wrote:  
So I have this implemented in an experimental branch, but I'd like feedback.

Should the keyword block search the post body? Is it necessary?
Should posts/comments be blocked from a user profile?
Should posts be blocked from a specific community?

imo a keyword filter should only filter keywords in a specific community or home/all feed, and only posts (not comments).
Thoughts? :)

**Comment by aeharding** [comment]
Thanks for the feedback! I am going to to push an initial version that filters keywords from the post title of home/all/community feeds.

In the future, we can always add further support for filtering :)

**Comment by DaveAlton** [comment]
Thanks so much. It makes sense to do it that way. It’ll be useful for 90% of use cases. The other 10% can be added in due time.   On Mon, Oct 9, 2023 at 7:35 PM, Alexander Harding ***@***.***> wrote:  
Thanks for the feedback! I am going to to push an initial version that filters keywords from the post title of home/all/community feeds.
In the future, we can always add further support for filtering :)
