### ISSUE TITLE
Hiding a post only hides it for a moment

### ISSUE THREAD

**Issue by DaveAlton** [aeharding/voyager#747]
When I swipe on a post to hide it, it disappears, then reappears soon after. Then I swipe again and it hides and then shows. Usually it takes 3 times to actually hide the post.

**Comment by Nirose** [comment]
It seems that it only hides it in the local UI, it does not send a read request to the lemmy server. 

However, if you have disabled 'Show Read Posts` in lemmy settings. You could also either upvote or downvote the post. It marks the post as read server-side. You could also open the post and go back in voyager and it will not show up again. 

![image](https://github.com/aeharding/voyager/assets/426674/632e4dd3-80ec-46e2-b53e-73cd400e4649)

It would be nice if the hide option actually sent a read request for the post so lemmy itself hides the post.

**Comment by DaveAlton** [comment]
I understand that, and I agree with your points, but I was having an issue where I would hide a post locally and then it would reappear within a moment.

**Comment by aeharding** [comment]
I think the issue is if the post is half off the screen. Then swiping hides but it comes back. I can reproduce if that is the issue.

**Comment by aeharding** [comment]
I have a fix I believe. It's not perfect - the feed might "jump" in this edge case, however it should hide the post properly.
