### ISSUE TITLE
Table horizontal overflow interfering with swipe actions

### ISSUE THREAD

**Issue by dandroid126** [aeharding/voyager#758]
I am trying to scroll to the right to view more of a table that is too long to display on my phone screen, but while scrolling, the swipe gesture is also happening.

Video: https://filebrowser.dandroid.app/api/public/dl/YB7BG7DK?inline=true

Good post to test with: https://lemmy.ca/post/6778202

**Comment by dandroid126** [comment]
Attached video is using version 1.13.0, but this can be reproduced on older versions as well.

**Comment by SrivatsanSenthilkumar** [comment]
I can also confirm this behavior.
