### ISSUE TITLE
Scrolling on Video doesn't work

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#763]
Scrolling on videos that auto play inside the feed doesn't seem to work. Especially a problem if the video fills more height, it happened to me a few times that I got stuck and couldn't scroll past it.

- happens for me on [this post](https://lemmyf.uk/post/2018066) for example 
- I'm on 1.13.0, TestFlight, iPhone 12 Pro, iOS 17.0.3

**Comment by aeharding** [comment]
This is an iOS bug :/ https://github.com/WebKit/WebKit/pull/18299
