### ISSUE TITLE
Cannot upload PNG images

### ISSUE THREAD

**Issue by SrivatsanSenthilkumar** [aeharding/voyager#765]
Recently found out when uploading pictures that upload of png images (irrespective of their size) was not allowed by voyager, i.e I cannot select the png image from the file picker at least on the android. On desktop(linux), png is not shown as a supported format by the file picker but if I choose a png image it uploads regardless. I have no idea of the behaviour on iOS.

**Comment by aeharding** [comment]
Thanks, this should be fixed in the next version of Voyager
