### ISSUE TITLE
Stutters when accessing the settings menu

### ISSUE THREAD

**Issue by SrivatsanSenthilkumar** [aeharding/voyager#770]
The settings header also jumps a little after the animation finishes. This started after the most recent update. Some stutters were always there but seems to have gotten worse after 1.14.0.

Attaching video below

https://github.com/aeharding/voyager/assets/141351084/d99eea18-2e24-410e-9c5f-363cc239a247

Edit : the video is not able to capture the stutter completely because the recording is at 60 fps. It is far more noticeable at 120 Hz.

**Comment by aeharding** [comment]
Thanks! I created https://github.com/ionic-team/ionic-framework/issues/28351

**Comment by SrivatsanSenthilkumar** [comment]
Thanks
