### ISSUE TITLE
Inconsistent posts button behaviour

### ISSUE THREAD

**Issue by SrivatsanSenthilkumar** [aeharding/voyager#777]
When scrolling through a feed, the posts button in the bottom nav bar behaves inconsistently. I thought it would take me to the top of the feed but instead it scrolls up but by a different amount each time. The only consistent behaviour I could find was that once at the top of the feed, it takes to the communities side panel.

Video showing this behaviour (the lines is an Android developer option to show where I am clicking)

https://github.com/aeharding/voyager/assets/141351084/ca16907e-24c4-4dfe-bc6e-fb7897d4d3bc

**Comment by aeharding** [comment]
Thanks. This appears to be an Android bug

**Comment by SrivatsanSenthilkumar** [comment]
Since this is an android bug, i will give some specs. I am on an android 12 device with 6 GB of RAM.

**Comment by SrivatsanSenthilkumar** [comment]
This same problem happens inside post threads as well. In posts with a lower number of comments, clicking the posts button on the bottom navbar takes me to the top of the post. On  posts with a lot of comments, the posts button scrolls up a different amount each time until it makes it to the top

**Comment by SrivatsanSenthilkumar** [comment]
@aeharding This seems to be resolved by MR #831 so i will close this.
