### ISSUE TITLE
Footer menu bar flickers/becomes blank

### ISSUE THREAD

**Issue by soren446** [aeharding/voyager#780]
The footer menu bar flickers and goes blank in the latest 1.14.0 release from TestFlight in iOS. This is reproducible when doing actions like scrolling in a community or clicking your profile. The menu buttons are still interactive and functional despite being blanked out. 

Screenshot example:

![IMG_0136](https://github.com/aeharding/voyager/assets/141293054/f5a916da-cb65-46ab-91c6-cfe8666bacfa)

**Comment by aeharding** [comment]
Thanks! This should be resolved in [1.14.6](https://github.com/aeharding/voyager/commit/66986422dd5644bd16bb17ac4f041eeb5eebe8fb) (I've been investigating this bug all morning.)
