### ISSUE TITLE
Autoselect current Lemmy instance during login

### ISSUE THREAD

**Issue by arunsathiya** [aeharding/voyager#782]
When I choose a Lemmy instance different from the default one (`lemmy.world`), like `lemmy.ml`, it'd be nice to autoselect that version in the login flow. Right now, it just autoselects the default of `lemmy.world`:

<img width="1085" alt="image" src="https://github.com/aeharding/voyager/assets/18581859/5e6adbb4-fb1b-4669-beeb-3544ff04cfe9">

<img width="1147" alt="image" src="https://github.com/aeharding/voyager/assets/18581859/00710d29-891f-459b-9b5a-17cfe59a60b1">

**Comment by sharunkumar** [comment]
@arunsathiya might want to close this one
