### ISSUE TITLE
load images in feed only with manual view

### ISSUE THREAD

**Issue by nutpantz** [aeharding/voyager#789]
Those with limited internet might like the option to only see\load images with manual interaction.

**Comment by aeharding** [comment]
Hi there! You can use compact mode and turn off thumbnails completely. Is that what you're looking for?

**Comment by nutpantz** [comment]
Where use that setting? I can't find it on the latest on fdroid

**Comment by aeharding** [comment]
1. Settings -> Appearance -> Post Size -> Compact, then
2. Settings -> Appearance -> Thumbnail Size -> Hidden

**Comment by aeharding** [comment]
Closing this, feel free to open a discussion if need be!
