### ISSUE TITLE
Button on/off “Show community icon” in feed

### ISSUE THREAD

**Issue by merak7** [aeharding/voyager#794]
hello! I think its a good idea if you add button toggle on/off “show community icon” in feed. 
 Its make UI clearly. As examples two screenshots Apollo and Voyager
![IMG_1402](https://github.com/aeharding/voyager/assets/23322761/3b120492-d11f-44eb-802c-822e746fa1cc)
![IMG_1403](https://github.com/aeharding/voyager/assets/23322761/dc954ae2-ca31-4517-83e5-c02e7d74aa9a)

Thank you for Voyager!

**Comment by nanangp** [comment]
Yes please. They're distracting, and they randomly break (#1114)
