### ISSUE TITLE
Usability: easy post button / quick post gesture and widget

### ISSUE THREAD

**Issue by jaromil** [aeharding/voyager#801]
Some of us post a lot! 😅 It would be great to have the post button directly accessible rather than hidden up-right behind the three dots menu and a modal.

POST BUTTON:
- Perhaps one low on the center? (instead of lemmy server)
- Also make a gesture for it?
- How about a quick post widget?

Thanks for your consideration and all the good work!

**Comment by Sakrecoer** [comment]
i second this, love everything about this app, but the convolution of the posting mechanism made me go back to the PWA
