### ISSUE TITLE
Creating a post with text and then replying to it creates a comment with the post text in it

### ISSUE THREAD

**Issue by BryceDMonaco** [aeharding/voyager#804]
I noticed if I create a new post with text, and then reply to it, anything I entered in the "Post Text" field is copied into the new comment window. The text can easily be deleted, and this only happens on the first time you create a reply (so if you discard the reply before you post it and then reply again, it does not reoccur).

To reproduce:

1. Create a new post, link, photo, or text.
2. [Add text to the "Post Text" field](https://github.com/aeharding/voyager/assets/11812350/2ff9f669-c2f2-459c-b5be-08895269f01b)
3. [Submit the post](https://github.com/aeharding/voyager/assets/11812350/11497c6e-0a73-4f10-a438-fbc8f40996bb)
4. Press the reply button, or return to the community's page and use the swipe to reply shortcut
5. [The new comment will already be filled with the text you entered in the "Post Text" field](https://github.com/aeharding/voyager/assets/11812350/add1e082-5139-4754-880e-4cdb7aad4086)

[Posting the comment, with or without edits, keeps the text if you do not delete it.](https://github.com/aeharding/voyager/assets/11812350/a7f282b9-4fb9-40a7-8e8a-de1e095662d0)

**Comment by aeharding** [comment]
Thank you very much for the report!
