### ISSUE TITLE
Every community on all and local feeds is showing as subscribed

### ISSUE THREAD

**Issue by SrivatsanSenthilkumar** [aeharding/voyager#807]
**Describe the bug**
 Every community on any all and local feeds is showing as subscribed when the quick action ellipses menu shows the community as subscribed. 

![Screenshot_20231020-132552.png](https://github.com/aeharding/voyager/assets/141351084/b1f855b2-0df0-42f0-8ea9-8ec70c5b4277)

To be clear, I am not subscribed to technology@lemmy.world and yet it shows up as subscribed

**To Reproduce**
Steps to reproduce the behavior: Go to the all or local feed and long press on the community name in the post. The menu which opens shows that the community is subscribed to if even one has not.

**Expected behavior**
Show correct subscription status

Android native app version 1.15.4 in my case but others also seem to be facing this issue
Edit : Bug persists in 1.15.5

**Comment by SrivatsanSenthilkumar** [comment]
Funny thing is, if you go to the community and click the 3 dots, it’s correct, and if you then go back to the feed and try again, it’s correct there as well - from another user in the voyager community

**Comment by aeharding** [comment]
Thanks! This is probably a regression from #713

**Comment by SrivatsanSenthilkumar** [comment]
Dude you are amazing
