### ISSUE TITLE
[Feature request] Block & subscribe to communities without being logged in

### ISSUE THREAD

**Issue by zkyrq** [aeharding/voyager#814]
Being able to block & subscribe to communities without being logged in would
be helpful. The data related to the blocked communities and the communities subscriptions would be stored in local storage. Also exporting those in a json file to have a backup.

**Comment by aeharding** [comment]
Hello! Thanks very much for the request.

In Lemmy, an account is required to create a feed of subscriptions and there isn't a way to do that without logging in, so this isn't a feature Voyager will have.

Thanks again though!
