### ISSUE TITLE
iOS share sheet and/or Shortcuts Support

### ISSUE THREAD

**Issue by fer0n** [aeharding/voyager#818]
It would be nice being able to share something on iOS without opening the App. Either via share sheet support (which is probably more helpful for most people) or via shortcuts support (which would be more flexible, but likely useful to fewer people).

**Comment by slrgt** [comment]
It would also be great to be open to be on a lemmy post from a browser and in the share menu have the option to Open In Voyager like how Apollo had :)

**Comment by gobbledygoober** [comment]
> It would also be great to be open to be on a lemmy post from a browser and in the share menu have the option to Open In Voyager like how Apollo had :)

This is also mentioned in https://github.com/aeharding/voyager/issues/608

**Comment by 0xCmdrKeen** [comment]
It appears that there is an NPM package available for that: [react-native-share-extension](https://www.npmjs.com/package/react-native-share-extension).  Also has support for Android. Setup looks quite complex, however, and it was last updated 5 years ago.

**Comment by aeharding** [comment]
I think this is being covered under #608.

**Comment by fer0n** [comment]
@aeharding #608 is about opening Lemmy URLs inside the app, this issue was regarding a shortcut/share sheet option to post to Lemmy. There's a small intersection there, as the same "tool" (shortcuts) could support both, but the thing it does is different.

Does it make sense to open this issue or add the "post to Lemmy via voyager" to the other issue? I'm not sure if they're related enough to combine them. Unless you think this issue here doesn't make sense in which case it can stay as it is ofc.
