### ISSUE TITLE
Vibrations occur on Do not disturb mode

### ISSUE THREAD

**Issue by SuperMeepBoy** [aeharding/voyager#822]
**Describe the bug**
When smartphone is on Do not disturb mode, vibrations occur. On every other app, no vibration occurs while on this mode.

**To Reproduce**

1. Enable Do not disturb mode on your smartphone
2. Click on an action which triggers a vibration (such as subscribing to a community or downloading an image for example)
3. A little vibration occurs

**Expected behavior**
No vibration should occur.

**Smartphone (please complete the following information):**

- Device: OnePlus 6T
- OS: LineageOS 20
- Browser: stock browser
- Version: 1.15.4 (assuming this is the version of Voyager here)

I use the app which I got on F-Droid if that matters.

**Comment by aeharding** [comment]
Hi there! Typically, haptics continue to operate in do not disturb mode. For example, the swipe back haptics, or keyboard haptics.

You can disable haptics for Voyager, fwiw. Does that help?

**Comment by SuperMeepBoy** [comment]
It does help ! Didn't know it was called like that ! Issue closed !

Thanks a lot !
