### ISSUE TITLE
Allow opening links in system browser

### ISSUE THREAD

**Issue by davr** [aeharding/voyager#825]
**Is your feature request related to a problem? Please describe.**
App-based browsers have a lot of downsides. You lose access to extensions, cookies, etc, and it allows the app more tracking over your activity. 

**Describe the solution you'd like**
An option in the application settings to always open links in the system browser, not in an embedded browser inside the app.

**Describe alternatives you've considered**
Jumping to the system browser from the app-based browser requires an extra tap, and it can break sometimes, if the url redirects depending on if you're logged in or not etc, becomes frustrating to get the page to open in the system browser

**Additional context**
Many apps have this option. The ones that don't I assume it is for anti-user-friendly purposes (ie maybe Facebook wants to track my browsing activity)

**Comment by aeharding** [comment]
Hi! This option is available in `General -> Other -> Open links in`

It's for the native app only, not available in the PWA.
