### ISSUE TITLE
Pull to refresh - dead spinner

### ISSUE THREAD

**Issue by boozook** [aeharding/voyager#873]
iPad mini 6, iPadOS 17.1 (21B74)
Voyager 1.18.0

Spinner that should be presented and animated when you pull the view, glitching or just doesn't presented.

1. Just do -pull-to-refresh on any scrollable updatable view in the Voyager

**Screenshots**
https://github.com/aeharding/voyager/assets/888526/22c7fecf-187e-414b-9f38-223aae76c68e

**Comment by aeharding** [comment]
Thanks, I think this is an Ionic issue so I created https://github.com/ionic-team/ionic-framework/issues/28438

**Comment by boozook** [comment]
```text
Device: iPad mini 6
iOS: iPadOS 17.1 or 17.2
App: 1.23.1
```

https://youtube.com/shorts/LFDROzQ0H8E

Partially fixed but still not works as expected.
