### ISSUE TITLE
Webms don't seem to be rendering

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#875]
![Screenshot_20231031_143047_Chrome.png](https://github.com/aeharding/voyager/assets/715417/7b90c4f9-1e09-4dbd-8c09-8435b39b2b8d)

![Screenshot_20231031_143102_Chrome.png](https://github.com/aeharding/voyager/assets/715417/8a824bb3-8974-4bdb-8861-6e92725db3ae)

thread link: https://vger.app/profile/lemmy.ml/c/memes/comments/7270271
comment link: https://vger.app/profile/lemmy.ml/c/memes/comments/7270271/0.5378375.5380477

- Platform: PWA
- Device: Samsung S23 Ultra
- OS: Android 14
- Browser: Google Chrome 118

**Comment by aeharding** [comment]
Hi I need more information, device OS version, thread URL

**Comment by SrivatsanSenthilkumar** [comment]
Since you have added the reproduction-needed tag @aeharding, I can confirm that this is an issue. Webms wont load inline. I am on the native android app, with android 12 and voyager version 1.18.0.

Comment link - https://feddit.de/comment/4478579

**Comment by aeharding** [comment]
Thanks! I also see that PR and I'll check it out
