### ISSUE TITLE
Links from other instances are not being presented on the app

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#879]
**Describe the bug**
When presented with a link of a post or comment from another instance that is not the one the user is currently logged in, the links opens on the device native browser instead on the app.

**To Reproduce**
Trying to open a link from a different instance other than the one you are logged into

**Expected behavior**
The link opens in the app on a new window.

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/104597302/7d2d582e-307b-4eaa-8947-5edfda62a614)

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.0.3

**Additional context**

**Comment by sallyFoster** [comment]
https://hexbear.net/post/246083

**Comment by aeharding** [comment]
Thanks! I'm not sure why that's not working. When we ask Lemmy via resolveObject, it says couldnt_find_object. Maybe because it's deleted? So this is appears to be a lemmy bug. You could try reporting to Lemmy.
