### ISSUE TITLE
Image not uploading when creating a post with image on android

### ISSUE THREAD

**Issue by yussefbens** [aeharding/voyager#880]
**Describe the bug**
I'm getting this error when I'm posting an image to any community, this error is 
<img width="269" alt="Screenshot 2023-11-02 at 18 51 33" src="https://github.com/aeharding/voyager/assets/11192475/fe880c4f-aa2f-4e28-93a0-5cd730fcc60a">
even if I retried it many times I'm still getting the same error. I built it with the latest changes in the main branch and run it on android API 32. I tried to disable CapacitorHttp to view the request and I notice that the autorization header is not sent.
<img width="469" alt="Screenshot 2023-11-02 at 18 51 01" src="https://github.com/aeharding/voyager/assets/11192475/4c10a0d1-17f3-400c-8bc5-f97ab3d425cf">
 I tried in the web and its working fine.

**To Reproduce**

1. Go to any community
2. Click on more actions
3. Click on submit post
4. upload the image

**Expected behavior**
image uploaded 

**Screenshots**
<img width="469" alt="Screenshot 2023-11-02 at 18 51 01" src="https://github.com/aeharding/voyager/assets/11192475/4c10a0d1-17f3-400c-8bc5-f97ab3d425cf">

**Smartphone (please complete the following information):**

- Device: Pixel 2
- OS: Android API 32
- Browser Chrome

**Comment by aeharding** [comment]
What's your instance?

**Comment by yussefbens** [comment]
Lemmy.ml

**Comment by aeharding** [comment]
Thanks. What version shows in Settings tab?

**Comment by yussefbens** [comment]
the version is 1.18.0, I ran `pnpm install` before building.

**Comment by aeharding** [comment]
Okay. Well try clearing node modules and reinstall. There is a bug in latest capacitor that doesn't send cookies that was resolved by downgrading, so if you have stale and/or upgraded capacitor things will break.

I'm closing this since it's a developer environment issue. If you can replicate using the official builds, LMK!
