### ISSUE TITLE
Clicking on currently selected tab icon doesn't stop kinetic scroll

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#887]
**Describe the bug**
Clicking on currently selected tab doesn't stop kinetic scroll. I think side-effect of it is also not being able to double click tab icon to navigate to previous page.

**To Reproduce**

1. Got to `Posts` tab
2. Click on `All`
3. Do a long swipe 
4. Click/double click on `Posts`

**Expected behavior**
Clicking on currently selected tab should stop kinetic scroll. And double clicking should navigate back to `Communities` page

**Screencast**
https://github.com/aeharding/voyager/assets/70429241/0d83ae3a-3aa9-4c8c-9bf3-2deddeb16182

**Smartphone:**

- Device: iPhone SE 2016
- OS: iOS15.3
- Browser: Native from gh releases
- Version: 19.3

**Comment by aeharding** [comment]
What's your device details?

**Comment by RocketRide9** [comment]
> What's your device details?

oops i used wrong template. i updated description, it includes device details now

**Comment by aeharding** [comment]
I see, thanks!

I think this is an iOS 15 bug unfortunately since it's not happening on my iOS device.

Sorry :(
