### ISSUE TITLE
12.0 update won't install

### ISSUE THREAD

**Issue by scstraus** [aeharding/voyager#896]
**Describe the bug**

It keeps notifying me of an update to 12.0, I install it, and it tells me again, I install it again, and the cycle repeats.

**To Reproduce**

Click on update notification, click on update, repeat ad nauseum

**Expected behavior**
It would update

**Screenshots**

**Desktop (please complete the following information):**

IOS, safari, latest

**Smartphone (please complete the following information):**

iphone 14

**Additional context**

**Comment by aeharding** [comment]
Hello! I think this is a Safari bug where the SSL certificate renews and service worker upgrades break. Quite annoying! I guess the fix in the meantime is to use the native app. I will look into it a bit more.

**Comment by aeharding** [comment]
More context: https://lemmy.world/comment/5537375

**Comment by aeharding** [comment]
This should be resolved after updating to the next (currently unreleased) version of Voyager.

If you are having trouble updating, you can run the script in the comment here: https://lemmy.world/comment/5537375

Thanks!
