### ISSUE TITLE
Error while trying to log in to a lemmygrad.ml account

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#903]
**Describe the bug**
I get an error when I try to login in into an account in lemmygrad.ml

**To Reproduce**
Add account of lemmygrad.ml and try to log in.

**Expected behavior**
It should log in to the account 

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/104597302/46643409-758f-4868-9250-c89d0eb6b7de)

**Smartphone (please complete the following information):**

- Device: [iPhone 11 Pro Max]
- OS: [iOS 17.0.3]

**Additional context**

**Comment by aeharding** [comment]
Hi there!

Login is currently working normally in-app, so it's likely either an instance issue, or incorrect credentials!

Thanks for reporting though.

**Comment by sallyFoster** [comment]
@aeharding I was able to log in from the Memmy app and from the lemmygrad website on web, so the issue is definitely on voyager

**Comment by aeharding** [comment]
I don't think the issue is Voyager because login is working everywhere I've tried. However, if you're using Voyager 1.20.0 or less then there is a bug where it will say "connection error" when really there was a credentials or other error. So once 1.20.1 is released, please try again and let me know if the error changes.

**Comment by sallyFoster** [comment]
@aeharding The issue was with the penultimate version, the ultimate version allowed me to log in with no issues. I used the same exact credentials. And as I mentioned previously I was able to log in on another app and on web with the same exact credentials.

**Comment by paulmorabito** [comment]
@sallyFoster did you ever get a fix for this? I'm having the same issue with a hosted version of Voyager (latest version running via docker)

**Comment by sallyFoster** [comment]
@paulmorabito Yes, I was able to log in on the following version
