### ISSUE TITLE
Subscribe to threads

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#909]
**Is your feature request related to a problem? Please describe.**

I often find an interesting thread I want to receive updates on whenever there is a new comment or edit. Sometimes this is a lemmy thread and sometimes a comment thread.

**Describe the solution you'd like**

would be great to be able to subscribe to a thread or comment thread and get notifications on any new comments or edits.

**Describe alternatives you've considered**

The only possible alternative is saving every interesting comment/thread and then manually checking them one by one every day to see if there are any updates 

**Additional context**
Back in the day of forums it was common to have interesting threads that would stay active for months sometimes years with new contributions to the thread adding valuable information. This isn't really a thing on lemmy because after a day or two the thread is gone from the feed and from the minds of everyone who commented on it.

**Comment by aeharding** [comment]
Hi, thanks for the issue!

This requires Lemmy changes, which is requested in https://github.com/LemmyNet/lemmy/issues/3069, so please follow that thread for more.

Thanks!
