### ISSUE TITLE
Default inbox action

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#910]
**Is your feature request related to a problem? Please describe.**
It's a bit frustrating to always click Inbox and then have to click Unread to see my notifications instead of it defaulting to the Unread section. It's also a bit frustrating that after reading the notifications sometimes when I click on Posts it takes me to the section to choose what feed I want to browse

**Describe the solution you'd like**

Have the Posts and Inbox button default to the feed set by the user and the Unread notifications by default

**Comment by aeharding** [comment]
Hi!

There is a plan to default to inbox (all) on long press here: https://github.com/aeharding/voyager/issues/458

For the posts button, do you have a reproduction? Do you have a bookmark directing you immediately to your inbox, and then after you press posts tab?

**Comment by aeharding** [comment]
@slrgt when encountering that issue, are you browsing voyager from a desktop computer/web browser, installed PWA, or native app?

**Comment by slrgt** [comment]
Native app ios 17.1.1

**Comment by aeharding** [comment]
This should be covered under #458. Thanks for the issue!
