### ISSUE TITLE
Hold the Hide Read Posts button to unhide read posts

### ISSUE THREAD

**Issue by slrgt** [aeharding/voyager#912]
**Is your feature request related to a problem? Please describe.**

Sometimes at night I want to see all the top posts of the day but I've already hidden them throughout the day.

**Describe the solution you'd like**

Being able to hold down the Hide Read Posts button to make all the Read Posts appear again would be great :)

**Comment by slrgt** [comment]
#820 makes unhiding posts possible but I don't believe it's possible to be triggered by holding the Hide Posts button which would make it super convenient

**Comment by bjoern-tantau** [comment]
To kind of reiterate from #1131 I think this should only show the hidden posts, but keep the hidden flag so that we can easily switch between the states. If someone really wants to unhide everything they could still use #820.

**Comment by slrgt** [comment]
Good point, that would be convenient
