### ISSUE TITLE
Filtered keywords are not saved

### ISSUE THREAD

**Issue by triglav-modular** [aeharding/voyager#919]
**To Reproduce**

1. Go to Settings > Filters & Blocks
2. Add a keyword
3. Quit and relaunch the app
4. The filters are missing 

**Expected behavior**
I expect the filters to be persistent between sessions. 

**Smartphone:**

- Device: iPhone 14 Pro
- OS: iOS 17.2
- Version 1.22.0

**Comment by aeharding** [comment]
Hi, thanks for the bug however I cannot reproduce. Is it possible you're viewing a different account?

**Comment by aeharding** [comment]
Reproduction unavailable, so closing the ticket. Thanks!
