### ISSUE TITLE
Scroll back to top, and then back to where you were

### ISSUE THREAD

**Issue by huanga** [aeharding/voyager#92]
In Apollo, a really handy feature to go back to the top on long threads is to tap the comment counter area at the top of the screen. In case of accidental tap, tapping the area again brings you back to where you were in the comments section.

In Wefwef, I've not been able to do this. It would be really cool if we can have similar feature here.

Device: iPhone 14 Pro Max
OS: 16.5.1
Browser: Safari

**Comment by aeharding** [comment]
Comment counter? Do you have a screenshot?

**Comment by huanga** [comment]
This post described it and /u/iamthatis added it later: https://web.archive.org/web/20211130183531/https://www.reddit.com/r/apolloapp/comments/r5tzli/suggestion_when_tapping_on_the_top_bar_to_go_at/

I am having a hard time tracking down exactly where Christian added the feature, but basically if you're some where deep in the comment scroll, you can tap the top to go to the top, and tap again to go back down (in case of accidental tap).

**Comment by aeharding** [comment]
Oh you mean the status bar!

On the web, even installed to homescreen, we cannot intercept tap events on the status bar. :(

The workaround is to tap the active tab in the footer to scroll to top. But that doesn't address your issue regarding double tapping.

**Comment by Waraugh** [comment]
Would it be possible to have the tap captured to the left of the sort icon?

I would always tap that area in Apollo to initiate the feature. Was really helpful to jump up quickly if I had scrolled a lot and wanted to get back to the top quickly. I could then drag down to reload new content.

**Comment by mysoulishome** [comment]
This is one of my favorite features and I’m missing. Loving wefwef today and excited as it develops.

**Comment by rsammelson** [comment]
> On the web, even installed to homescreen, we cannot intercept tap events on the status bar. :(

@aeharding isn't this being done in the feed? When you click the status bar it opens the search, right?

**Comment by aeharding** [comment]
Update: With Capacitor status bar plugin, this should be fairly straightforward to implement! See: https://capacitorjs.com/docs/apis/status-bar
