### ISSUE TITLE
[Feature request] Import/Export Filter List

### ISSUE THREAD

**Issue by SocietasEvanescentes** [aeharding/voyager#927]
**Is your feature request related to a problem? Please describe.**
n/a

**Describe the solution you'd like**
Allow users to import and export filtered terms. Ideally, this would still work locally to not transmit data or add to any infrastructure costs of the vger.app

**Describe alternatives you've considered**
screenshots or backups of words, terms, etc. 

**Additional context**
n/a

**Comment by aeharding** [comment]
Hi there!

This should be covered under #366 so please follow along there :)

**Comment by erikpendragon** [comment]
#366 does not backup filter lists just the settings.

**Comment by aeharding** [comment]
It works for me. If its not working for you, please open a new issue with detailed reproduction steps. Thanks!
