### ISSUE TITLE
feature request: automatically upvote when saving a post (or a comment)

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#928]
This used to be a feature on [Boost](https://play.google.com/store/apps/details?id=com.rubenmayayo.reddit), which could be enabled using an option.

I could work on a PR for this if such a feature is good to go on this app.

**Comment by sallyFoster** [comment]
@sharunkumar Could this be an optional feature because I sometimes save content, but I don't necessarily want to upvote it?

**Comment by sharunkumar** [comment]
Yeah it was an option that you could enable if you want

**Comment by sharunkumar** [comment]
Going on a tangent here but I really want this feature too. It was on Boost as well

![image](https://github.com/aeharding/voyager/assets/715417/41a3f526-0d4a-452f-b3f0-b9dfcb4f93b9)

**Comment by aeharding** [comment]
@sharunkumar Yeah, that's difficult to get working right until https://github.com/ionic-team/ionic-framework/issues/26524 is resolved
