### ISSUE TITLE
The app cannot run gifs or videos

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#929]
**Describe the bug**
The app is not able to run gifs or videos.

**To Reproduce**
Try to open a posted gif or a posted video

**Expected behavior**
The app plays the gif of video of the post that the user is looking at

**Screenshots**

It shows a broken image when trying to open a post with a gif
![image](https://github.com/aeharding/voyager/assets/104597302/cb97b3ae-3473-4817-bbeb-b17bf23cca48)

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.1

**Additional context**

**Comment by aeharding** [comment]
Post example https://lemmy.world/comment/5195514

**Comment by sallyFoster** [comment]
Example posts

Gif: https://lemmygrad.ml/post/2663617

Video: https://lemmy.ml/post/7847654

**Comment by sharunkumar** [comment]
@aeharding it's working on my fork:
 
![Screenshot_20231114_161340_Chrome](https://github.com/aeharding/voyager/assets/715417/6d4f9cf0-58f9-4da7-b3f9-e63d9e8041c4)

possibly because of https://github.com/aeharding/voyager/pull/877

**Comment by sallyFoster** [comment]
@aeharding My video still doesn't render![image](https://github.com/aeharding/voyager/assets/104597302/91966e56-6f7f-42c8-8061-f421c5873579)


URL: https://lemmy.ml/post/7847654

**Comment by aeharding** [comment]
@sallyFoster Your video is incorrectly encoded for iOS. Other apps like Avelon have a similar problem.
