### ISSUE TITLE
Back Gesture/button during an options open/Reply open view having confusing UX.

### ISSUE THREAD

**Issue by bhavesh622** [aeharding/voyager#93]
Using an Android phone, with the app installed via Chrome. Great app by the way, feels like the most polished out of the ones I've tried so far. The issue I'm facing currently is of a confusing UX, not sure if it's a fixable problem or a problem at all, but since the back gesture on Android is much more used to get out of open menus, figured I should post it. Opening the three dots menu on any post or comment or community, and swiping using the back gesture of the device doesn't close the menu, but instead goes back from the page you were on in the background, while keeping that menu open. Can instantly close the page if it were on the home screen, opened on the browser. Similar issue with typing a reply, or a comment on a post, if I open one and swipe back, the usual flow in an other app would be to ask if I should discard or keep the comment, but instead it goes back from the thread or post entirely, while keeping the comment box open. It's not unusable, but a bit of a difference from the usual UX flow. If this is not solvable or a non-issue, please feel free to close it.
Ignore the search request, unrelated to this issue :P

https://github.com/aeharding/wefwef/assets/43331748/feb1654e-ff0c-440c-988b-6d2dec8b0876

https://github.com/aeharding/wefwef/assets/43331748/5cb8c30f-0b12-474e-aebd-d084e51f9397

**Comment by seang96** [comment]
To add to this one I noticed it on just about any popup. Most notably creating a new comment and backing out.

**Comment by aeharding** [comment]
Hmm. Not sure if there's an override for android. Needs investigation. Thanks for the issue!

**Comment by rahulakrishna** [comment]
this seems like a fundamental Android issue of the back button trying to do a lot more than just going back. Maybe https://github.com/aeharding/wefwef/issues/98 will fix this. If not, we may have to append something to the URL for every popup.
