### ISSUE TITLE
Pull to refresh - almost dead spinner

### ISSUE THREAD

**Issue by boozook** [aeharding/voyager#930]
Related issue: #873 (partially fixed but still not works as expected).

```text
Device: iPad mini 6
iOS: iPadOS 17.1 or 17.2
Voyager: 1.23.1
```

__Video:__ https://youtube.com/shorts/LFDROzQ0H8E

Spinner that should be presented and animated when you pull the view, glitching or just doesn't presented.

## Case 1:

_First half of screencast video_

1. Just do pull-to-refresh on any scrollable updatable view in the Voyager

Result: spinner and scroll are bouncing/hopping in a bad not normal native way.

## Case 2:

_Second half of screencast video_

1. Scroll to top (just simply tap to top-bar for example)
1. Scroll down a little bit for one or two lines
1. Do pull-to-refresh

Result: no spinner.

**Comment by aeharding** [comment]
I believe this is an Ionic bug - essentially, I think Ionic is falling back to the generic spinner when it should be using the iOS one.

**Comment by boozook** [comment]
❤️‍🔥
