### ISSUE TITLE
Menu text doesn't scale with 'Text Size' setting

### ISSUE THREAD

**Issue by sharunkumar** [aeharding/voyager#932]
<table class="tg">
<thead>
  <tr>
    <td class="tg-0pky">

The setting:

![Screenshot_20231114_001414_Chrome](https://github.com/aeharding/voyager/assets/715417/e77ee66c-f507-43b7-b00e-d524eef23e4c)

</td>
    <td class="tg-0pky">

Menu items (too large):

![Screenshot_20231114_001433_Chrome](https://github.com/aeharding/voyager/assets/715417/21b6e5a9-ac6e-4305-af1e-af52a52a9441)

</td>
  </tr>
</thead>
</table>

**Comment by aeharding** [comment]
Hi,

Could you confirm if this is an Ionic bug? Ionic added dynamic text scaling recently and so if it's an Ionic bug then it should be reported there. Thanks!

**Comment by aeharding** [comment]
Actually, looking a bit closer it appears that on iOS native apps like Mail, setting a font size does not change action sheet font size. So since this is consistent with iOS I am closing but feel free to investigate further an report upstream if you find examples of otherwise
