### ISSUE TITLE
Favorite communities without signing in

### ISSUE THREAD

**Issue by NiaTheCat** [aeharding/voyager#934]
**Is your feature request related to a problem? Please describe.**
Favoriting a community only works when logged into an account

**Describe the solution you'd like**
A way to subscribe to or favorite Communities locally without logging in, for a read-only experience without needing an account

**Comment by aeharding** [comment]
Hi @NiaTheCat, I've thought about this but it introduces too many edge cases when users login/logout and what would happen to favorites in those edge cases. There are many situations where this could frustrate the user if they login and their favorites disappear, for example.

For now, the best solution is to have an account. Thanks!
