### ISSUE TITLE
Restore posts after crash too

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#949]
**Is your feature request related to a problem? Please describe.**
Voyager restores comments after crash. Why not to restore posts too? 

**Describe the solution you'd like**
If an app crashes while you was writing a post, restore title, attached link/image and description on next launch. 

**Describe alternatives you've considered**

**Additional context**
Currently it restores only a post description

**Comment by aeharding** [comment]
Hi there! Post body restores for me.

It is expected that title and image won’t recover, but usually that’s easy to reconstruct versus the body.

if you are not seeing the post body recover, let me know the steps to reproduce and I’ll look into it
