### ISSUE TITLE
Add a possiblility to embed picture in post body

### ISSUE THREAD

**Issue by RocketRide9** [aeharding/voyager#962]
**Is your feature request related to a problem? Please describe.**
Currently you can press an image button while writing a comment and select an image to embed in the comment, but when you press the same button selected image replaces post image.

**Describe the solution you'd like**
Add ability to add an image to post body

**Describe alternatives you've considered**
maybe also allow a drag n drop and pasting an image.

**Additional context**
Pressing this button should embed image in post body.
![изображение](https://github.com/aeharding/voyager/assets/70429241/630a5d49-b275-4061-a64a-523a8b08ea64)

**Comment by 80avin** [comment]
Can you verify ?
I was going to work on this, but found that it already works in a way.

If you opened the Editor from <kbd>Photo</kbd> tab, then it attaches the image to post.
While if you open the editor from <kbd>Text</kbd> tab, then it embeds the image.

**Comment by aeharding** [comment]
Yes, this is expected behavior. Attaching a photo to the post body just adds it inline your markdown.

If you want to upload a photo as your post, use the photo tab and upload there.
