### ISSUE TITLE
Comment score / Post score not visible anymore?

### ISSUE THREAD

**Issue by Juansero29** [aeharding/voyager#964]
**Is your feature request related to a problem? Please describe.**
Comment score / Post score not visible anymore. It used to be visible from the profile page. Now we only have "comment count" and "post count". 

**Describe the solution you'd like**
I'd love to see my karma score again. Comment score and post score.

**Describe alternatives you've considered**
Maybe below the current counters of comment count and post count? Or maybe by accessing a new page of detailed stats of my account by tapping my username from the profile page. Both can be great.

**Additional context**
Not needed I think

**Comment by aeharding** [comment]
Hi there. Unfortunately Lemmy is removing karma so Voyager has to remove it as well. See: https://github.com/LemmyNet/lemmy/issues/3393#issuecomment-1779400639
