### ISSUE TITLE
Elipsis and number of days not showing for short comments on the Unread window

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#966]
**Describe the bug**
Elipsis and number of days not showing for short comments on the Unread window.

**To Reproduce**

1. Receive a short comment to a post or a comment
2. Click on Inbox
3. Go to Unread
4. Find the short comment

**Expected behavior**
Short comments should show ellipsis and number of days in the Unread window

**Screenshots**
![image](https://github.com/aeharding/voyager/assets/104597302/ee940aad-b280-43a4-b7ac-a8d305d4b87b)

**Smartphone (please complete the following information):**

- Device: iPhone 11 Pro Max
- OS: iOS 17.1

**Comment by aeharding** [comment]
Interesting! I am having trouble reproducing this, I have a ton of items in my inbox but they all have the ellipse.

If anyone else can confirm please lmk.

**Comment by aeharding** [comment]
Reproduction unavailable, so closing the ticket. Thanks!
