### ISSUE TITLE
Option to see communities mod log

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#979]
**Is your feature request related to a problem?

As a user I would like to see any community's mod log

**Describe the solution you'd like**

I would like to have an option in the ellipsis pop up, that would allow me to check the modlog

**Describe alternatives you've considered**

Right now, the only way is to go to the website and getting the mod log from there

**Additional context**

It would be great to have it added here

![image](https://github.com/aeharding/voyager/assets/104597302/97d8b853-fb18-42d1-97a4-fe8c3e9b7351)

**Comment by 0xCmdrKeen** [comment]
I too would like to see this, so I took a stab at implementing it. Turns out it was easier than I expected — all the required views already exist in the app, all I had to do was wire up a menu item. Will send a PR shortly.
