### ISSUE TITLE
Approve Post button appears to be causing "restored post" messages on the mod log

### ISSUE THREAD

**Issue by Mischala** [aeharding/voyager#983]
**Describe the bug**
Approve Post button on a post appears to be having unintended behavior of marking a post as "Restored"

**To Reproduce**

1. Navigate to a Community where you're account is a mod
2. Find a post
3. Tap the Approve Post button
4. Navigate to the Mod log
5. See the "Post Restored" log for the post you tapped

**Expected behavior**
The action being called on the server may be incorrect?
Or at least, incorrectly understood.

This button may need to be renamed "Restore post" and the button should only be shown on mod removed posts?

I don't think I should be prompted to restore a post that is not removed?

**Screenshots**

**Smartphone (please complete the following information):**

- Device: OnePlus 5t
- OS: Android 13
- Browser Firefox
- Version 120.0 (Build #2015986298), 039de7ef85+

**Additional context**
Voyager version: 1.25.0
I would rather not share screenshots, don't want to associate my mod account with anything else on the web.

Anything else I can do to help, I am keen.

**Comment by aeharding** [comment]
Hi, thanks for the report!

So the idea, at least I was thinking, is that it's not really "restoring" as much as it is "approving". (If you're familiar with reddit moderation, it might make more sense.)

I could disable the approve button, but IMO it can be helpful for other moderators to see if a mod has specifically "approved" a given post.

So we can definitely change wording in Voyager's mod log from restored to approved, but maybe we should also discuss this with Lemmy? What do you think?

**Comment by aeharding** [comment]
Thinking a bit more, this is a bit complicated because Lemmy's mod log is public. a Mod may want to resolve a report through voyager and not have it listed as "approved"/"restored" in the mod log. hmmmmm. Maybe I should just match Lemmy functionality for now (and then bring up with the lemmy team)

**Comment by Mischala** [comment]
You being the owner of the project have a lot more clout with the Lemmy project than little 'ol me.

But, more than willing to help out with implementation etc.

**Comment by aeharding** [comment]
Okay, in the next version:

 1. "Approve" only resolves reports [does NOT add mod log entry]
 2. "Remove" resolves reports + removes [adds mod log entry]
 3. "Restore" resolves reports + restores [adds mod log entry]

Also, you will only see the options that makes sense to do so you don't try to do the same thing twice.
