### ISSUE TITLE
Pure Black Dark Mode, isn’t.

### ISSUE THREAD

**Issue by ultratiem** [aeharding/voyager#985]
**Describe the bug**
Pure Black Dark Mode simply dims the colours on iOS, rather than using a “pure” black.

**To Reproduce**

Settings / Themes > Pure Black Dark Mode

**Expected behavior**
Darker elements should be set to 0,0,0:#00000 to make use of OLEDs efficiency. 

**Screenshots**
![IMG_0073](https://github.com/aeharding/voyager/assets/2991193/c0de1dab-8809-4709-8fc9-dd554b61e528)

**Comment by sallyFoster** [comment]
@ultratiem 

This is weird because mine looks pure black. Is your device iOS or Android? 

![image](https://github.com/aeharding/voyager/assets/104597302/cb1856fa-a879-4603-a702-10bb8a9e2115)

**Comment by aeharding** [comment]
As @sallyFoster said, pure black dark mode is not supported on Dracula.

I could add some more messaging on this, if this is causing confusion with other users too.

But I will close for now. Thanks!

**Comment by ultratiem** [comment]
I think the correct behaviour is for all themes to have a pure black mode variant that enabled with that switch or simply switch over to default theme when the toggle is enabled, but thanks for the clarification, I’ll use it as a workaround for now.

**Comment by sallyFoster** [comment]
@ultratiem Dracula doesn't have it because you can achieve the same effect of a Dracula pure dark mode just by tapping on ultraviolet.
