### ISSUE TITLE
Option to add the instance of users and communities in notifications

### ISSUE THREAD

**Issue by sallyFoster** [aeharding/voyager#993]
**Is your feature request related to a problem?

Currently in notifications only the username and community are shown without their instances next to them

![image](https://github.com/aeharding/voyager/assets/104597302/39bac61c-c877-404c-a8cb-2153a9366c6a)

**Describe the solution you'd like**

I would like to be able to see the instance of users and communities in notifications before opening them

**Describe alternatives you've considered**

Right now the only way to know the user and community instance of a notification is by opening it.

**Additional context**

Knowing the instances on notifications saves times to users because they don't have to open the message just to know the instances.

**Comment by 0xCmdrKeen** [comment]
I took a quick stab at this but the problem is that the space in the footer is very limited, and showing the instance name (especially when it's for both username AND community) is likely to exceed the available horizontal space.

However, it IS possible to at least make the current setting apply to the username in the notification header. Here's what that looks like:

![image](https://github.com/aeharding/voyager/assets/98132670/104d2944-9a8f-40f7-a980-ae7698eaa309)

**Comment by 0xCmdrKeen** [comment]
@sallyFoster yes but that would be inconsistent. Not a big fan of that.

Also it doesn't even render properly on one line if there's enough space for it for some reason:

![image](https://github.com/aeharding/voyager/assets/98132670/5c640f10-3924-43a1-ab12-6a1fd061eeb8)

While this can probably be solved, it would still run the risk of running over a single line if both the user name and the full community name are long — imagine something like oddlyspecificplaylists@sh.itjust.works (yes, that exists). 

I think this situation would warrant a more thorough discussion.

**Comment by 0xCmdrKeen** [comment]
Basically, here's the problem: even when fixing it to work for full community names that fit on one line, if the name is too long, it will still break like this:

![image](https://github.com/aeharding/voyager/assets/98132670/14c5ebe9-c679-4564-9712-58642227cec9)

And I'm not really sure how to cleanly solve that other than simply truncating it at one line. Which I have also tried, but my CSS skills aren't good enough to keep those three dots and the time indicator from disappearing.

**Comment by sallyFoster** [comment]
@0xCmdrKeen That is okay. Currently, the line also gets broken in the app.

![image](https://github.com/aeharding/voyager/assets/104597302/9e0a44f0-501f-4c1f-ba23-110fe904de54)

**Comment by 0xCmdrKeen** [comment]
I see. But not in the middle of the user/community name.

**Comment by sallyFoster** [comment]
@0xCmdrKeen  Yeah, you are right. It is okay to break the line, but not in the middle of the user or community. Hmmm... you are right. I would like to hear @aeharding thoughts on it. 

@0xCmdrKeen Thanks for all your hard work to make the features that I would love to see come to life 😄!

**Comment by 0xCmdrKeen** [comment]
@sallyFoster I appreciate your appreciation, but yes, I think this decision is a bit past my paygrade, so let's wait for Alex to chime in on that.

**Comment by sallyFoster** [comment]
@aeharding Did you ever get a chance to look into this?

**Comment by aeharding** [comment]
I have a partial solution, which will show instance name if you have it configured in settings (same setting as for comments). Doesn't work for communities yet though.

It now allows you to tap (and tap+hold) like other places, though!

**Comment by aeharding** [comment]
For the community label to show instance because there's no setting for that yet like comments.

**Comment by sallyFoster** [comment]
Oh, got it

**Comment by sallyFoster** [comment]
@aeharding Just tested it, and I really like it! Thanks!!!
